### ISSUE TITLE
Support for THnSparse

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/uproot#107]
When attempting to access a THnSparseF via uproot, the output of `repr()` and `dir()` on the object is:

```
THnSparse: <Undefined (no class named 'THnSparseT<TArrayF>', version 1) at 0x000111a3c668>
Available attributes: ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__metaclass__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_classname', '_classversion', '_copycontext', '_cursor', '_postprocess', '_readinto', 'read']
```

From exchanging a few emails with Jim, I understand that this indicates that the streamer is not yet implemented - this issue is intended to get this discussion going.

To aid in testing, a root file containing the example THnSparseF (named "testSparse") is available [here](https://github.com/ALICEYale/alice-yale-dev/raw/master/analyses/uproot/testSparse.root). It is quite trivial - it contains a number of axes and has been filled with a few entries. It can be recreated using the code [here](https://github.com/ALICEYale/alice-yale-dev/blob/master/analyses/uproot/uprootSparse.py) (note that it will fail on an assertion because it attempts to access a member which is not available yet, but the test file will be created anyway).

**Comment by jpivarski** [comment]
Thank you! I'll look at this as soon as possible, at least to determine which streamer types are missing (and therefore whether it's a small job or a big job).

**Comment by jpivarski** [comment]
Well, there were some dumb mistakes in there, like putting Python class names into the `classes` lookup and trying to retrieve C++ class names. (The sparse histogram's C++ class name is `THnSparse<TArrayF>` and its Python class name is `THnSparseT_3c_TArrayF_3e_` because Python class names need to be alphanumeric. Apparently, we haven't been trying to read templated classes yet, or we would have seen this mistake earlier.)

Only one streamer needed to be implemented, `TStreamerObjectAnyPointer`, which seems to have the same structure as a `TStreamerObjectPointer`. For now, the provisional implementation is the same and I'd like to see from your tests if that's warranted.

Since this class is in a deep class hierarchy, I've added a convenience method `_members()` to iterate over all private members, including those from superclasses:

```python
>>> import uproot
>>> f = uproot.open("/tmp/downloads/testSparse.root")
>>> h = f["testSparse"]

>>> for n in h._members():
...     print(n, getattr(h, n))
... 
fName b'testSparse'
fTitle b'testSparse'
fNdimensions 7
fAxes [<TAxis b'axis0' at 0x729482c136a0>, <TAxis b'axis1' at 0x729482c13668>, ...
fEntries 2.0
fTsumw 0.0
fTsumw2 -1.0
fTsumwx [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
fTsumwx2 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
fChunkSize 16384
fFilledBins 1
fBinContent [<THnSparseArrayChunk at 0x7294829a1080>]

>>> for n in h.fBinContent[0]._members():
...     print(n, getattr(h.fBinContent[0], n))
...
fSingleCoordinateSize 3
fCoordinatesSize 3
fCoordinates [ 21 -83  32]
fContent [2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
fSumw2 None
```

I've also added a stub for implementing THnSparse methods in hist.py: see the `THnSparseMethods` class. There's one dummy method:

```python
>>> h.hello()
('world', 51)
```

because

```python
class THnSparseMethods(object):
    def hello(self):
        return "world", len(dir(self))

# apply to everything that is a subclass of THnSparse (Python name)
uproot.rootio.methods["THnSparse"] = THnSparseMethods
```

Eventually, histogram methods will go in a separate library, but for now, you can experiment with adding methods in this branch of the uproot repository.

Let me know if anything is missing, or if it looks like something wasn't read in correctly. Thanks!

**Comment by raymondEhlers** [comment]
Excellent, thank you! I'll test this out over the next few days to check that everything is working as expected and report back

**Comment by raymondEhlers** [comment]
I began trying it out, but I wasn't able to finish before I left for vacation. I'll be back next week, but I don't want to hold you up, so please feel free to repackage as needed. I can sort it out when I'm back

**Comment by jpivarski** [comment]
Classes like `THnSparseMethods` will move to another package named "uproot-methods". I'll be adding this package in a day or two, though it will take longer to fully refactor for uproot 3.

**Comment by raymondEhlers** [comment]
Okay, thanks!

**Comment by jpivarski** [comment]
Just to let you know, the migration is done and we've been working with the newly refactored uproot/uproot-methods for a while now. [uproot-methods](https://github.com/scikit-hep/uproot-methods) is becoming a user-contributed library, so much so that I've added an AUTHORS file to keep track. (Matthieu Marinangeli just added support for all the TGraph types.) If you're interested in supporting THnSparse, [the stub](https://github.com/scikit-hep/uproot-methods/blob/master/uproot_methods/classes/THnSparse.py) is still there and the system is ready for contributions!

**Comment by raymondEhlers** [comment]
Thanks for the update! I had put this on the back burner because I wasn't certain about the state of the transition, but since it's complete, I'll try to come back to this within the next three weeks or so.

**Comment by raymondEhlers** [comment]
I started developing the methods this weekend, but I'm a bit confused behavior regarding the `_members()` behavior - it appears that the underscore is being dropped in some (but not all) cases. To be more explicit:

```python
>>> h._members()
['_fName', '_fTitle', 'fNdimensions', 'fAxes', 'fEntries', 'fTsumw', 'fTsumw2', 'fTsumwx', 'fTsumwx2', 'fChunkSize', 'fFilledBins', 'fBinContent']
>>> [x for x in dir(h) if x.startswith("_f")]
['_fAxes', '_fBinContent', '_fChunkSize', '_fEntries', '_fFilledBins', '_fName', '_fNdimensions', '_fTitle', '_fTsumw', '_fTsumw2', '_fTsumwx', '_fTsumwx2', '_fields', '_format1', '_format2']
```

For now, I'll continue to develop using the "_f" version of the variables, but could you point me in the right direction for how best to resolve this?

**Comment by raymondEhlers** [comment]
Okay, thanks for the clarification! I finished the basic methods, but properly determining the bin indices associated with the bin content takes a good deal more work. I hope that I'll finish it up next weekend
