### ISSUE TITLE
memmap error for some (large) root files

### ISSUE THREAD

**Issue by shane-breeze** [scikit-hep/uproot#108]
When trying to open a large root file with `uproot.open`, it can give the following error:

```
>>> uproot.open("nanoAOD_1.root")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hep/sdb15/.local/lib/python2.7/site-packages/uproot/rootio.py", line 59, in open
    return ROOTDirectory.read(localsource(path), **options)
  File "/home/hep/sdb15/.local/lib/python2.7/site-packages/uproot/source/memmap.py", line 43, in defaults
    return MemmapSource(path)
  File "/home/hep/sdb15/.local/lib/python2.7/site-packages/uproot/source/memmap.py", line 47, in __init__
    self._source = numpy.memmap(self.path, dtype=numpy.uint8, mode="r")
  File "/vols/build/cms/sdb15/atuproot/externals/pip/lib/python2.7/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
mmap.error: [Errno 12] Cannot allocate memory
```

The same error appears when using memmap:
```
>>> np.memmap("nanoAOD_1.root")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vols/build/cms/sdb15/atuproot/externals/pip/lib/python2.7/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
mmap.error: [Errno 12] Cannot allocate memory
```

**Comment by jpivarski** [comment]
Can you do the following? Do you still get an error?

```python
import os.path
uproot.open("nanoAOD_1.root", dtype=numpy.uint8, mode="r", shape=(os.path.getsize("nanoAOD_1.root"),))
```

**Comment by shane-breeze** [comment]
Yes, that works fine. And it seems to load the tree correctly

**Comment by jpivarski** [comment]
Wait— do you have a 32-bit operating system? (See [this bug](https://github.com/aarddict/tools/issues/17).)

**Comment by shane-breeze** [comment]
Nope, 64-bit OS

**Comment by jpivarski** [comment]
Huh. If it was a 32-bit OS problem, then I would consider making the local file option an auto-fallback. But not if I don't know what the issue is.

For now, you can use local file handles instead of memmap. I'm going to leave this issue open until I understand what it is (which could be indefinitely!). At least searchers would be able to find the work-around.

Whereas the memmap caching is handled by your OS, the `FileSource` class emulates a memmap interface with an explicit cache in Python. The default chunk-size is 8 kB and it accumulates up to 1 MB while the file object is in scope. That makes it something to tune if you have performance issues...

**Comment by jpivarski** [comment]
Maybe your OS is 64-bit, but is the Python process 32-bit?

```python
>>> import platform
>>> platform.architecture()
('64bit', 'ELF')
>>> import numpy.distutils.system_info
>>> numpy.distutils.system_info.platform_bits
64
```

**Comment by shane-breeze** [comment]
I've tested with other files and it seems like the boundary between error and no error is suspiciously close to 4 GB. But the OS is 64-bit and the Python process is 64-bit:
```
>>> import platform
>>> platform.architecture()
('64bit', 'ELF')
>>> import numpy.distutils.system_info
>>> numpy.distutils.system_info.platform_bits
64
```
