### ISSUE TITLE
Strings encoded as bytes

### ISSUE THREAD

**Issue by GilesStrong** [scikit-hep/uproot#111]
Hi Jim,
Reminder issue from our quick chat at QCHS, as requested.

Uproot encodes strings as bytes, and would be nice if there were the option to decode into UTF-8 when calling functions.
My particular issue is with the column names when exporting to a Padas dataframe, e.g.:
```
rootData = uproot.open(splitDir + "125.root")['mu_tau'].pandas.df()
rootData.head()
```
Produces a dataframe with columns names:

`b't_0_pT'  b't_0_eta'  b't_0_phi'  b't_0_mass' b't_0_mT' b't_1_pT'`

Currently my work around is to run:
`rootData.columns = [x.decode("utf-8") for x in rootData.columns]`

But it would be more convenient to be able to request UTF-8 when exporting the dataframe, and with similar functions, too.

Thanks,
Giles.

**Comment by jpivarski** [comment]
Every method that has an `outputtype` now has a `namedecode` which is by default `None` (leave names as byte strings) but could be the name of an encoding (turn names into string strings). These are:

   * `uproot.iterate`
   * `uproot.lazyarrays`
   * `uproot.daskarrays`
   * `uproot.daskframe` (default is "utf-8")
   * `TTree.iterate`
   * `TTree.arrays`
   * `TTree.lazyarrays`
   * `TTree.pandas.df` (default is "utf-8")

The methods that always return DataFrames convert to strings by default because they're really just convenience methods. `TTree.pandas.df`, for instance, just calls `TTree.arrays` with `outputtype=pandas.DataFrame`. Also, there's already precedent for these methods to differ in defaults from the more low-level ones: `TTree.pandas.df` has a default of `flatten=True` whereas `TTree.arrays` has a default of `flatten=False`. Of course, these are all documented.

Amazingly, I had to put in a correction to satisfy Python 2.6 (yes, I'm still supporting 2.6). That's the second commit.

All of this is going through the wringer and will appear in PyPI as version 2.9.8.
