### ISSUE TITLE
uproot pypi package includes "tests" folder

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/uproot#113]
At the moment uproot's pypi package is 52 MB big:
```
https://files.pythonhosted.org/packages/c3/2a/aa66b8cc7ab19b6479895e758f89ba8321038f7fd6682d7dc9439c677b07/uproot-2.9.8.tar.gz (52.2MB)
```
This is mostly due to the tests folder (55.8 MB unpacked).

As I can see per setup.py, this should be excluded:
https://github.com/scikit-hep/uproot/blob/master/setup.py#L93

And indeed, when running
```bash
python setup.py sdist bdist_wheel
```
I end up with a file < 500 KB.

Is the current pypi package built in a different way?

**Comment by jpivarski** [comment]
I thought I was excluding the tests!

For my own reference, [this might be a solution](https://stackoverflow.com/a/26547314/1623645).

Wheels might unnecessarily limit the portability of the library. It's pure Python, so it should run anywhere with Python and Numpy, but making a wheel might label it with the platform of the machine that deploys it to PyPI (currently Travis/Linux). I don't want "pip install uproot" to wrongly say, you can't install this because you're using a Mac/Windows.

The actual deployment is handled by Travis, so I don't even have a commandline to edit. I'll have to figure out how to do this through Travis's YAML.

**Comment by jpivarski** [comment]
I made a clean AWS instance and tried installing uproot from scratch (with `pip install`). It _downloads_ a 52.2 MB tar-gz package, then _installs_ just under 1 MB of code. I tried it with Pythons 2 and 3, but the Python 3 re-used the tar-gz from the previous download.

So this is not an installation burden, it's just a big download (that gets cleared whenever pip cleans its cache). Is this still a problem? I'm going to look into convincing Travis to build wheels _and_ a tar-gz, because we want to be sure that a tar-gz is available for non-mainstream cases.

**Comment by kreczko** [comment]
Ah, no that is not a problem at all. Did not realise that the installed size is smaller than the downloaded tar-gz.

**Comment by jpivarski** [comment]
Okay, I think 59b23cc126b97460a2b20448280b0f44b4c98855 (uproot 2.9.9) did it: I've added

```yaml
distributions: "sdist bdist_wheel --universal"
```

to .travis.yml. The `--universal` makes the wheel compatible with Pythons 2 and 3 (because it's pure Python) and there's still a source version in there as a backup. We see both the universal wheel and the tar-gz in [uproot's files section on PyPI](https://pypi.org/project/uproot/#files).

With another clean AWS instance, I can install from pip and get it downloads the 133 kB wheel (no tests directory inside of it) regardless of whether I do Python 2 or 3 first. After installing it for one, it doesn't have to re-download for the other Python version— this is truly a universal wheel. I think that takes care of it.

Even if it wasn't absolutely necessary, now users will have a snappier installation experience (0.1 MB download instead of 5.1 MB). That's always good.
