### ISSUE TITLE
ROOT file format per uproot

### ISSUE THREAD

**Issue by pibion** [scikit-hep/uproot#116]
I have a couple use-cases that would benefit from a ROOT-less C++ or Java interface to ROOT files, and I'm wondering if it might be possible to describe the ROOT file structure with e.g. Kaitai Struct (http://kaitai.io/) or a DFDL schema (https://daffodil.apache.org/).

It seems like this is at least close to what the uproot parser currently does; does anyone know of any documentation on the ROOT format I might refer to?

Apologies if the appropriate thing to do is buckle down and work through the uproot code!  I thought I'd ask just in case there's a great resource I just haven't been able to find.

**Comment by sbinet** [comment]
thanks for these interesting 2 links.

I think this would be interesting to discuss on the Polyglot ROOT I/O forum:
- https://groups.google.com/forum/#!forum/polyglot-root-io

(we actually had a couple of threads on this very same issue. TL;DR: there's no real documentation on the ROOT format to speak of. no specs. just the code.)

**Comment by jpivarski** [comment]
I investigated declarative file format specifications at the beginning of uproot development (the "root-from-spec-v2.0" branch). I looked at a few declarative file format specifiers, but none of them were as polished as Kaitai. That ones looks really nice!

However, the nature of the format doesn't really allow for a declarative specification. For example, nothing but a full programming language would be able to implement [_readobjany](https://github.com/scikit-hep/uproot/blob/master/uproot/rootio.py#L405): this is a history-dependent function that fills a map/dict with class and object definitions so that they can appear multiple times in the file but only be written once. History-dependence is by definition not "declarative," though a specification like Kaitai might bend that rule for expressivity.

Another thing that I wasn't able to find in declarative specifiers: the ability to read an integer value from the file and tell the specification to seek to that location. Even more so for seeking to such points in decompressed buffers drawn from the file. The ROOT format does this _everywhere!_

And finally, the thing that you'd mostly want a declarative specifier for is to describe the byte-layout of objects such as TH1 or TTree (like Kaitai's GIF example). However, ROOT does this for you: ROOT's TStreamer system puts the declarative specification of each object in the ROOT file itself, and these specifications can change. New versions of the TH1 class can, for instance, add new fields, and this happens too rapidly to keep a Kaitai file up to date. However, the Kaitai equivalent is in the corresponding ROOT file itself in the TStreamerInfo block, so if you look there, you'll always be able to read in the objects. That's what uproot 2.0 eventually ended up doing.

-------------------------------------------------------

**On Python:** I know that you wouldn't want to use a Python project in a C/C++ framework, as it adds a weird dependency with speed and parallelization issues in the middle of your stack. (I wouldn't want that either— uproot is specifically for end-user analysis.) Here are some options:

   * There's an implementation in Java: [root4j](https://github.com/diana-hep/root4j) and [spark-root](https://github.com/diana-hep/spark-root). The way it's supposed to work is that root4j is pure Java and only concerns itself with I/O while spark-root concerns itself with interfacing with Spark in Scala. However, I don't know if that distinction was maintained— I think spark-root might be doing some I/O.
    * [go-hep/rootio](https://github.com/go-hep/hep/tree/master/rootio)! Even if the rest of your stack is C/C++, I see no reason why you can't run a library implemented in Go. Go compiles to a fat binary so it's very portable— you may be able to just drop it in as an artifact.

If you want an uproot-like API ("ask for a branch, get an array"), this may be possible now or soon in go-hep: check with @sbinet.

Otherwise, yes, it would be a conversion effort, but the core part of uproot is fairly simple. All of the file I/O is in uproot/rootio.py and the actual TTree handling is a minority of uproot/tree.py. Most of uproot/tree.py is providing arrays to users in different ways. Also, it's possible to skip streamers: the "version-1.x" branch is pre-streamers and it works. You just need to put a lot of `if version >= X` branches in the object-reading, and it wouldn't be future-proof.
