### ISSUE TITLE
Maximum recursion depth exceeded for caches

### ISSUE THREAD

**Issue by shane-breeze** [scikit-hep/uproot#118]
Caches end up in an infinite loop if the user adds the memory cache as an item to itself. I realise this shouldn't be done but there's nothing stopping the user from doing this or even adding a `dict` or nested `dict` which contains the memory cache and so might not be easy to spot.

The [`sizeof`](https://github.com/scikit-hep/uproot/blob/master/uproot/cache/memorycache.py#L86) is where the the infinite recursion starts. This function can recurse over certain objects and if this object is the cache itself then it will get stuck in a loop.

My suggestion is to check that the user doesn't add an item to the cache which is the cache itself at some point or skip `sizeof` acting on the cache itself (but you might not want a nested cache anyway). This will prevent them getting the infinite recursion which spits out the error below at somepoint:

```
  File "uproot/cache/memorycache.py", line 88, in <genexpr>
    return sys.getsizeof(obj) + sum(MemoryCache.sizeof(k) + MemoryCache.sizeof(v) for k, v in obj.items())
  File "uproot/cache/memorycache.py", line 98, in sizeof
    out += MemoryCache.sizeof(x)
  File "uproot/cache/memorycache.py", line 88, in sizeof
    return sys.getsizeof(obj) + sum(MemoryCache.sizeof(k) + MemoryCache.sizeof(v) for k, v in obj.items())
  File "uproot/cache/memorycache.py", line 88, in <genexpr>
    return sys.getsizeof(obj) + sum(MemoryCache.sizeof(k) + MemoryCache.sizeof(v) for k, v in obj.items())
  File "uproot/cache/memorycache.py", line 98, in sizeof
    out += MemoryCache.sizeof(x)
  File "uproot/cache/memorycache.py", line 91, in sizeof
    elif isinstance(obj, (unicode, str)):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jpivarski** [comment]
You're right— this should be protected by a memo (maybe adding `id(self)` to a `set` as an argument to the function). That would fix the infinite recursion, but it would also fix multiple keys pointing to the same object: the second one shouldn't count against the storage capacity.

However, part of the refactoring I'm involved in now for uproot 3.0 will be removing this class entirely— I'll be replacing it with [cachetools.Cache](https://cachetools.readthedocs.io/en/latest/#cachetools.Cache). It's a widely used third-party library; they probably did a better job on it than I did. The interface ought to be the same, since they're both emulating Python dicts. But if you're using uproot's cache objects in a major way, this could be seen as a heads-up that they're being replaced. Do you see any limitations (for your work) in using cachetools?

(I'm closing this as a rare won't-fix: I recognize that it's wrong but won't be fixing it because this class doesn't have a future.)

**Comment by shane-breeze** [comment]
`cachetools` seems to cover everything I'll need

**Comment by jpivarski** [comment]
Perfect! I'm happy to not oblige.   :)
