### ISSUE TITLE
about arrays or array functions to JaggedArray or numpy arrays

### ISSUE THREAD

**Issue by sahaskn** [scikit-hep/uproot#119]
Dear developer, 

I've recently learned about uproot and found it is very useful regarding no need to install cern ROOT.

The document says that uproot is written in pure python including numpy. I am just wondering whether the functions arrays() or array() are optimized for faster operation. (I loaded a root file of  1.2 GB size, containing 5 branches and it generally tooks 20 s to distribute them to numpy arrays). 

At last, thanks for uproot.

**Comment by jpivarski** [comment]
Hi,

I'm not sure what you're asking for here— are you saying that 20 seconds to read 1.2 GB is too slow and maybe a non-Python backend would make it faster? If you really are reading all 1.2 GB (and it's not just 5 branches out of a 1.2 GB file containing 1000 branches) in 20 seconds, that's 50 MB/sec, a typical hard drive raw reading rate. Faster interpretation code won't help if the bottleneck is hardware.

If your question is just, "in principle, can compiled code help?"— there are only a few corner cases where it might. The design of uproot follows a rule that nothing involving a loop over events (entries) may be written in Python for loops. So, for instance, all the events in a TBasket are turned into a Numpy array with one Python statement: a slice of the memory-mapped array cast as the appropriate type (Numpy "view"). That can't be made more efficient with compiled code because it _is_ compiled code— the trick is to find existing Numpy functions that do what we want in one step, rather than writing custom compiled code that may be non-portable or hard to install.

There are some exceptions, however. Many Python statements are required to traverse the file, seeking to TBaskets, so if your file has a large number of small TBaskets, then it would be slow to read in uproot— and ROOT— but especially uproot. I've been thinking of writing an optional accelerator for this case in Cython (lets you mix Python and C++ objects, to only accelerate the hotspots), but that won't be happening anytime soon. For such a project, we'd need a particular case that demonstrates this effect and has an important physics application.

The other cases are particular types that have to skip bytes on every event because the data in the TBasket are not homogeneous. Some of these implementations break the rule of "no Python for loops over events" because I couldn't think of a Numpy function that could handle them. If I remember right, these would all be compiled if you have Numba installed on your system (it tries to import Numba, and if successful, compiles that for loop on the fly). If your case is one of these, you might find reading to be faster on the _second_ read it you install Numba. (The first read has to perform a compilation.)

All of these cases will be fixed soon. I'm replacing the complex ("awkward") array cases with a new implementation in a separate library called awkward-array, and these manage to avoid Python for loops for non-contiguous data. (I've learned more Numpy functions— there are ways to do it without specialized compiled code.) The advantage of this approach is that everybody gets the speedup, even if they don't have Numba installed, and there's no just-in-time compilation step. The new arrays will be available starting in uproot 3.0, which I'm working on right now.

**Comment by sahaskn** [comment]
@jpivarski: Thanks for the reply. I opened the issue just to know a bit more about uproot as I did not find any other places to get information. The root file I used is simple root file with  5 branches, all have entries at given event. 

 I will be glad if you could please give some examples of uproot io including loop to be compiled with numba. 

I used before pyroot module and also a module to convert root to numpy which gave error regarding memory eventhough  the root file I've used is few 100 MB but has 7 branches, all have entries. When I tried uproot with 1.2GB of root file, I was really impressed with the success and want to know more about the conversion of root to numpy through uproot. 

Best Regards!!

**Comment by sahaskn** [comment]
Dear @jpivarski : Thanks for explanation. Just being interested, I saved the unpacked arrays to npz format and then loaded them back. The load time is equivalent to the time it took by uproot through arrays function. So, in my case, the arrays function are equivalent to numpy load to native format. Very impressive!!!
Kudos!!!

**Comment by jpivarski** [comment]
Good— if the npz and the ROOT files were both compressed with gzip (the default until a recent version of ROOT... 6.12, I think...) then both reads should be dominated by the decompression and would be about the same. Sounds like it worked.

Cheers!
