### ISSUE TITLE
Reading custom classes

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot#124]
I really appreciate this project for obvious reasons ;)

I have one question: we have to deal with a lot of files which contain instances of custom (sub)classes of ROOT objects. Of course we get errors like `ValueError: cannot interpret branch ... as Python type`.

Is there a recommended way to somehow tell `uproot` e.g. the memory layout of such objects? Or is this just not supported at this point?

**Comment by jpivarski** [comment]
There should be no work on your side. uproot should be reading the structure of those types from the streamer info in every ROOT file and use that to learn how to interpret the branches.

What's missing in your case is not the class definitions but the interpretation of those class definitions. I don't have code to interpret all of the streamer types that describe classes because I have to see each one of them "in the wild" to be sure of its interpretation.

What you can do that would help me greatly is to send me preferably small, preferably public examples of the files you're having trouble with. The preferences are so that I can include them in the unit tests to ensure that the fix is permanent.

The object interpretation code has been considerably revamped in uproot 3, which is now in beta. Would you mind if I only fix this in beta?

**Comment by jpivarski** [comment]
Oh, wait— it's not necessarily that— it might be as simple as just not knowing that it already has a streamer. The branch metadata to deserialization code mapping is complex enough that often we have the deserializing code but just don't know that it should be invoked for a given branch. That, too, can be diagnosed with an example.

**Comment by tamasgal** [comment]
Ah ok, sounds like we don't have much trouble :D So what do you need?

**Comment by tamasgal** [comment]
Here is a dummy file with some non-sense data (e.g. 23 events): https://www.dropbox.com/s/cd35gsumxizomby/dummy.root?dl=0

**Comment by tamasgal** [comment]
So, to reproduce it, it's basically:

```
In [1]: f = uproot.open("dummy.root")

In [2]: f['KM3NET_EVENT;1']['KM3NET_EVENT']['KM3NETDAQ::JDAQPreamble'].basket(0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-0737eb596126> in <module>()
----> 1 f['KM3NET_EVENT;1']['KM3NET_EVENT']['KM3NETDAQ::JDAQPreamble'].basket(0)

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/uproot/tree.py in basket(self, i, interpretation, entrystart, entrystop, flatten, cache, basketcache, keycache)
   1123             raise IndexError("index {0} out of range for branch with {1} baskets".format(i, self.numbaskets))
   1124
-> 1125         interpretation = self._normalize_interpretation(interpretation)
   1126         entrystart, entrystop = self._normalize_entrystartstop(entrystart, entrystop)
   1127         local_entrystart, local_entrystop = self._localentries(i, entrystart, entrystop)

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/uproot/tree.py in _normalize_interpretation(self, interpretation)
   1006
   1007         if interpretation is None:
-> 1008             raise ValueError("cannot interpret branch {0} as a Python type".format(repr(self.name)))
   1009
   1010         return interpretation

ValueError: cannot interpret branch b'KM3NETDAQ::JDAQPreamble' as a Python type
```

**Comment by tamasgal** [comment]
Jim, many thanks for your efforts so far, I am really glad that you take your time!

> There's a branch called issue-124 where I'm working on this. Your file helped me find and fix a few bugs and misconceptions, but I don't know if I'll be able to fully interpret it on a short timescale.

Nice to hear that!

For us, it would be absolutely awesome if we could read our detector data also with `uproot` for several reasons (one of them is open data access); so yes, I am totally willing and interested in solving this.

A large part of the software which contains the `J`-prefixed classes is not public (yet), so it's a bit hard to point to the source code, but I'll talk to the management so that I can provide the needed information.

Nevertheless, I though it might be helpful to show some actual numbers. You were already correct with the "overlays" and "triggermask" and I see a lot of meaningful/valid vectors ;)

The **first event** in the KM3NET_EVENT tree holds a header with numbers like

detector ID: 29
frame index: 70
trigger mask: 22
overlays: 6
utc seconds: 1513069207
nanoseconds: 0

53 hits in total (snapshot hits), 34 of them are triggered (triggered hits)

Here is a sample (the first 20) of the hits, but beware, this information is read out by another software (based on PyROOT) which adds a group id and the dom ID (this is obtained by the module id...), however it might be useful for crosschecks when you look at channel_id, tot or the triggered flags:

```
    channel_id     dom_id        time  tot  triggered  group_id
0           24  808432835  63744757.0   34       True         0
1           25  808432835  63744755.0   24       True         0
2           26  808432835  63744753.0   22       True         0
3           27  808432835  63744756.0   24       True         0
4           28  808432835  63744753.0   36       True         0
5           29  808432835  63744775.0   20       True         0
6           30  808432835  63744751.0   28       True         0
7            1  808432835  63744758.0   16       True         0
8            2  808432835  63744749.0   39       True         0
9            5  808432835  63744752.0   33       True         0
10           7  808432835  63744756.0   21       True         0
11          25  808432835  63744980.0   26      False         0
12          18  808488990  63744326.0   24      False         0
13           0  808488997  63744911.0   30       True         0
14           2  808488997  63744914.0   20       True         0
15           4  808488997  63744913.0   25       True         0
16           5  808488997  63744919.0   23       True         0
17           6  808488997  63744914.0   29       True         0
18           7  808488997  63744910.0   27       True         0
19           9  808488997  63744911.0   43       True         0
```

The **second event**:

detector ID: 29
frame index: 76
trigger mask: 22
overlays: 9
utc seconds: 1513069207
nanoseconds: 600000000

38 hits in total (snapshot hits) and 18 of them are triggered)

A snapshot hit contains for example the PMT channel ID (unsigned char to save space, values are from 0 to 30), a time over threshold (ToT) with values between 0-255 (also unsigned char), a hit-time (unsigned int, can be large)...

Btw. I just googled a bit and found that there is actually public code available from the main author. It might be an older version but this part was not really changed in the past years, so I assume it's the same or at least reasonably similar to the version which produced the ROOT file above:

`JDAQPreamble`: https://www.nikhef.nl/~mjg/Jpp/html/JDAQPreamble_8hh_source.html
`JDAQHeader`: https://www.nikhef.nl/~mjg/Jpp/html/JDAQHeader_8hh_source.html
`JDAQHit`: https://www.nikhef.nl/~mjg/Jpp/html/classKM3NETDAQ_1_1JDAQHit.html
`JDAQTriggeredHit`: https://www.nikhef.nl/~mjg/Jpp/html/JDAQTriggeredHit_8hh_source.html
`JDAQSnapshotHit` (a typedef which points at `JDAQKeyHit`): https://www.nikhef.nl/~mjg/Jpp/html/JDAQKeyHit_8hh_source.html

Let me know what you need and again, many thanks in advance, no matter how far we get. I am already happy to see that you are able to access some of the numbers using `uproot` ;)

**Comment by tamasgal** [comment]
Take your time. I am fighting with this data format for a couple of years already, I can wait and glad to receive any kind of help 😅

**Comment by jpivarski** [comment]
Okay, I have a (to me) unsatisfying solution.

You can read all of your data like the following (using code checked out of the [issue-124 branch](https://github.com/scikit-hep/uproot/tree/issue-124); use master if you're reading this after I merge issue-124 into master):
```python
import uproot
from uproot import interpret, asjagged, astable, asdtype

import uproot
f = uproot.open("dummy.root")
t = f["KM3NET_EVENT"]

eventheaders = t["KM3NETDAQ::JDAQEventHeader"].array(interpret(t["KM3NETDAQ::JDAQEventHeader"], cntvers=True))
preambles = t["KM3NETDAQ::JDAQPreamble"].array(interpret(t["KM3NETDAQ::JDAQPreamble"], tobject=False))
snapshotHits = t["snapshotHits"].array(asjagged(astable(asdtype([("id", "i4"), ("pmt", "u1"), ("tdc", "u4"), ("tot", "u1")])), skipbytes=10))
triggeredHits = t["triggeredHits"].array(asjagged(astable(asdtype([("id", "i4"), ("pmt", "u1"), ("tdc", "u4"), ("tot", "u1"), (" cnt", "u4"), (" vers", "u2"), ("trigger_mask", "u8")])), skipbytes=10))
```

The first two branches are read into tables (one record per event) and the last two are read into jagged tables (multiple records per event). These are all backed by arrays, not Python objects, so it's as memory efficient and fast as Numpy. You can find out what's in these tables by asking for their `columns`:

```python
>>> eventheaders.columns
['detector_id', 'run', 'frame_index', 'UTC_seconds', 'UTC_16nanosecondcycles', 'trigger_counter', 'trigger_mask', 'overlays']
>>> preambles.columns
['length', 'type']
>>> snapshotHits.columns
['id', 'pmt', 'tdc', 'tot']
>>> triggeredHits.columns
['id', 'pmt', 'tdc', 'tot', 'trigger_mask']
```

and then indexing them with square brackets like dicts or arrays:

```python
>>> eventheaders["frame_index"]
array([ 70,  76,  80,  86,  87,  89,  90,  93,  98, 100, 106, 106, 108,
       111, 111, 117, 125, 133, 136, 139, 146, 151, 152], dtype=int32)
>>> preambles["length"]
array([1198,  760,  944, 1006, 1330,  708,  466,  796,  580, 1146,  612,
        960,  866,  796,  618,  466,  900,  804, 1614,  678,  446,  808,
        728], dtype=int32)
>>> snapshotHits["pmt"]
<JaggedArray [[24 25 26 27 28 29 30  1  2  5  7 25 18  0  2  4  5  6  7  9  9 17 13 19
 10 15  5  8 10 13 15 19  4  9 11  2 14 30  1 21 23 29 30  0  0  2  3  4
  5  6  8 10 13] [14 16 27 10  0 27  1  7  9 16  4  5  6 10  0 21 19 30 20 21  7 11 20  4
 24 26  0  1  5 15  9 11  5  9 28 22  3 18] [11 10 20 29  4  4 27  5  7 24  0  1  4  5  6  9  7 21 12 13 15 16 17 18
 19 21 30  7  8  9 10 11 12 12 13 14  7 14 17 21 22 24] ... [29  7  8 30  0  3  5  8  4 11 30 30 28  0  2  3  5 30  0 13 15], [22 30  4 20 24  4  5  8  8 10 17 26 27 24  0 29 20 26 27  2  3  5 16 18
 20 30  0  1  2  5 27  0  0  6 10  5 24  3  5 12  8], [ 4  5  7  7  9  9 10 11 27 30 20  5 11 22  8 30 24  5  8 22  6  0  9  3
 18  5  7  9 10 12 15 15 13]] at 7f9ef8040e48>
>>> triggeredHits["trigger_mask"]
<JaggedArray [[22 22 22 22 22 22 22 22 22  4 22 22 22 22 22 22 22 22 22 22 22 22 22 22
 22 22 22 22 22 22 22 22 22 22] [ 4 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22] [ 4 22 22 22 22 22 22 22 22 22 22 22 22 22 22  4 22 22 22 22 22 22 22 22
 22 22] ... [4 4 4 4 4 4 4 4 4 4], [22 22 22  4 22 22 22 22 22 22 22 22 22  4 22  4 22 22 22], [ 4 22 22  4 22  4 22  4 22 22  4  4 22 22 22 22 22 22 22]] at 7f9ef80409e8>
>>> triggeredHits["trigger_mask"][2]
array([ 4, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,  4, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22], dtype=uint64)
```

I recommend reading the [uproot-jaggedarray tutorial](https://mybinder.org/v2/gh/scikit-hep/uproot/master?filepath=binder%2Fversion-3-features.ipynb) for examples on how to use these objects without resorting to (slow) Python for loops. (There's nothing wrong with the for loops except speed— it might be fine for the size of your dataset.)

Why am I disappointed? Look at what you have to enter to get your data! All four branches have the wrong default interpretation, requiring you to provide a custom one.

   * `KM3NETDAQ::JDAQEventHeader` has object byte counts and versions in the places where you'd expect them in non-TTree data (such as histograms), but I've never seen them in TTree data before. Therefore, I added a switch to turn them on. I can't have this switch be the default because there are other objects in TTree data which do not have byte counts and versions. It must be on in your case and it must be off in other cases, and I don't yet know why.
   * `KM3NETDAQ::JDAQPreamble` descends from `TObject`, but it lacks `TObject` headers. Again, I added a switch: it must be off in your case and it must be on in other cases. I don't know why.
   * I can tell that `triggeredHits` has type `vector<JDAQTriggeredHit>` and `snapshotHits` has type `vector<JDAQSnapshotHit>`, and following the documentation you provided, I can deduce the streamer manually. However, these streamers are not in the ROOT file. That's very strange: ROOT files are supposed to be self-describing— _all_ of the streamers for objects in the file must be in the streamer info, and yet they're not there. Interpretation types like `asjagged(astable(asdtype([("id", "i4"), ("pmt", "u1"), ("tdc", "u4"), ("tot", "u1")])), skipbytes=10)` are an illustration of how to build it (`skipbytes=10` because it's an STL vector), but I really shouldn't be making you do that.

Thus, I'm a little wary of this and will have to brood over it for a while before putting the change into master. You should have no problem reading and using these data, I just wish I knew _why_ the interpretation is what it is— I wish I could find where in the headers it says to interpret it this way.

But you should be able to get to work with this.

**Comment by tamasgal** [comment]
Jim, I am really amazed for your great work. I wish I could help you somehow, but I have little knowledge (compared to yours I feel I don't know anything) about the ROOT internals.

I'll show this thread to the main author of the corresponding software package – at least he is a ROOT guru too – and hopefully he can give provide some useful thoughts. I will definitely share them...

Now I'll go through the jagged array tutorial and after that I'll write a wrapper library to make our data accessible without ROOT and any other huge, uncomfortable dependencies, halleluja!

Again, many thanks so far :)

**Comment by jpivarski** [comment]
You're welcome.  :)  And let me know if you run into any issues with the new jagged arrays. They seem solid to me, but they still need to be tested "in the wild."

**Comment by tamasgal** [comment]
I will :)

**Comment by jpivarski** [comment]
Done! The tutorial has been updated and it looks to me like it works.

**Comment by tamasgal** [comment]
Great, just downloaded it and now I'm walking throught, thanks!
