### ISSUE TITLE
issues with JaggedArray

### ISSUE THREAD

**Issue by vkuznet** [scikit-hep/uproot#125]
Jim,
playing around with new uproot I found few issues with JaggedArray code refactoring. First, it is now located in awkward package, but uproot still loads it from uproot module, e.g.
https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L458
```
if isinstance(array, uproot.interp.jagged.JaggedArray):
```

Then, the JaggedArray implementation in awkward is no longer support contents attribute, e.g.
I run my code to read root files and this block
```
        nbytes = sum(x.contents.nbytes + x.stops.nbytes \
                if isinstance(x, JaggedArray) \
                else x.nbytes for x in data.values())
```
where I passed data as `tree.iterate.next` object, I got this exception:
```
./reader.py --fin=root://cms-xrd-global.cern.ch//store/data/Run2017F/Tau/NANOAOD/31Mar2018-v1/20000/6C6F7EAE-7880-E811-82C1-008CFA165F28.root --verbose=1 --nevts=2000
Traceback (most recent call last):
  File "./reader.py", line 708, in <module>
    main()
  File "./reader.py", line 701, in main
    nevts=nevts, specs=specs, verbose=verbose)
  File "./reader.py", line 238, in __init__
    self.init()
  File "./reader.py", line 367, in init
    self.read_chunk(nevts, set_branches=set_branches, set_min_max=set_min_max)
  File "./reader.py", line 316, in read_chunk
    performance(nevts, self.tree, self.branches, startTime, endTime)
  File "./reader.py", line 134, in performance
    else x.nbytes for x in data.values())
  File "./reader.py", line 134, in <genexpr>
    else x.nbytes for x in data.values())
  File "build/bdist.linux-x86_64/egg/awkward/array/base.py", line 64, in __getattr__
AttributeError: 'JaggedArray' object has no attribute 'contents
```
Could you please have a look at fix the issues.

**Comment by jpivarski** [comment]
Right— there were two spots where `uproot.interp.jagged.JaggedArray` were referenced, and neither of them should have been referencing any version of `JaggedArray`. I fixed that in master.

As for `contents`, your last version of uproot must have been an old one because `contents` → `content` long ago (an effort at synchronizing names across packages). Everything uses the singular `content` now (or it's a bug).

Let me know if this needs to be reopened/it doesn't settle your two issues. Thanks!
