### ISSUE TITLE
uproot available for conda/osx-64?

### ISSUE THREAD

**Issue by jcatmore** [scikit-hep/uproot#144]
Hi,

I just tried to install uproot on my Anaconda installation on my Mac, but it claims not to know about the package:

```
 conda install uproot
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - uproot

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

I also looked on the Anaconda package list and wasn't able to find it. So is this package available? I ask because the documentation here does imply that it should be available: https://pypi.org/project/uproot/

and I would prefer to keep everything within the Anaconda environment if possible, as it seems to be the smoothest way of managing these various packages.

Thanks for any tips.

Best wishes,

James Catmore (ATLAS Experiment)

**Comment by jpivarski** [comment]
Sorry for the confusion. I was just in the process of removing the text about installing from conda because I had previously thought that conda would defer to pip. I myself install firstl from conda, then use the pip within my conda distribution for the rest. Dependency-management is a separate tree, but at least everything is in the miniconda3 directory that I can remove it any time, or even an environment within that.

Is it easy to deploy to conda? If so, maybe I should add that to my deployment. I currently deploy through Travis.

**Comment by jcatmore** [comment]
Thanks Jim - pip within conda worked fine and I'm now up and running! 

James.

**Comment by jpivarski** [comment]
I've methodically changed all of the READMEs (uproot, uproot-methods, awkward-array, and histbook) to say "pip-in-conda" instead of "conda". You're not the first who assumed there was a conda package.

**Comment by jpivarski** [comment]
Apparently, the following is no longer true. It could explain why I assumed it would work.

![image](https://user-images.githubusercontent.com/1852447/46147043-f2567480-c229-11e8-804f-1390057af80d.png)

From https://speakerdeck.com/teoliphant/packaging-and-deployment-with-conda (November 2013)

**Comment by jpivarski** [comment]
By the way, https://anaconda.org/conda-forge/uproot

This is maintained by @chrisburr, along with ROOT itself, XRootD, and other HEP packages.
