### ISSUE TITLE
"Masks" or "Views" of a tree.

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/uproot#159]
Is there an easy way to "mask" or create a "view" to a TTree read in through uproot?  

Currently in one stage of the processing I'm deciding whether or not events are useful, ie,creating a mask, which is just a numpy array either of bools or a list of indices.  At the moment, if some later part of the code wants to read only "good" events it needs to be given the mask directly, but it would be nice if I could attach this to the tree in some way that I still have all the normal tree methods / interpretations.  I also don't want to pass around large dataframes / structured arrays with the mask already applied since I'm not sure at the point where I make the mask which branches will actually be needed later on.  

My current solution is a wrapper around the tree object itself that applies this mask to the events when any attribute of the tree is accessed which returns events. 

This would offer functionality similar to [TEntryList](https://root.cern.ch/doc/master/classTEntryList.html) I think, though I never really used that very much.

Apologies if this is already solved or has been asked elsewhere, though I checked and couldn't see it mentioned!

**Comment by benkrikler** [comment]
Here's a gist to my current solution, though disclaimer it's under-tested and probably not functionally complete: https://gist.github.com/benkrikler/35197cbf289c791912361ab24b8f6e19

**Comment by benkrikler** [comment]
Sounds great. Thank you.  I'll update that gist as I go just in case its useful to others.

**Comment by jpivarski** [comment]
This is now possible with awkward-array, but I need to get on it.

**Comment by jpivarski** [comment]
This was finally added in uproot 3.6.0! The function names are `lazyarray(s)`. There had been lazy array functions before, but the new ones translate TTrees into `ChunkedArrays` of `VirtualArrays`, which are awkward-arrays with all the slicing methods, instead of a custom `uproot.tree.LazyArray` class.

(uproot originally had its own JaggedArray and everything; the process is one of slowly moving from custom implementations to the more general ones in the awkward-array library. Next is `StringArray`.)

Here's a fun trick: you should be able to TTree and save it as a virtual array, actually saving only the derived data you add to it:

```python
array = uproot.lazyarrays("files*.root", "treename", persistvirtual=True)
array["derived"] = ...
awkward.save("file.awkd", array)
```

and now (because we explicitly asked to persist the virtualness), the `"file.awkd"` contains array data for the derived field but only pointers to reconstruct the other fields from the original `"files*.root"`. Now we can mix data from different sources—an original ROOT dataset and a small set of corrections or other modification.

(That flexibility was one of the original motivations for the awkward-array design, but it took a long time to get around to enabling it.)

**Comment by benkrikler** [comment]
Wow!  This is a lot of super-cool new functionality!  Thanks @jpivarski!
