### ISSUE TITLE
Performance issues reading a large number of branches

### ISSUE THREAD

**Issue by MaxNoe** [scikit-hep/uproot#164]
I have a file with a very large (> 5000) number of branches holding custom objects, each branch has ~1500 entries.

I want to read the fields of those objects.

While reading a single branch is very fast, reading becomes slower and slower the more branches I have read.

Also the time it takes to read multiple branches at once using `tree.arrays(keys)` is very non-linear in the number of branches being read.
```
  10 Branches: 0.006 seconds
 100 Branches: 0.107 seconds
1000 Branches: 8.472 seconds
2000 Branches: 35.010 seconds
```

Do you know where this unefficient, nonlinear behaviuour comes from?

**Comment by jpivarski** [comment]
There's a non-linear algorithm in _finding_ the branches (it's a search through a list, not a hashtable-lookup), but I've always been assuming that the problem of searching through metadata is negligible compared to reading events. That might not be true. How big are these branches? Could you send me a copy of the file (even privately), and I'll see if it's the quadratic branch-name lookup, fixing that if necessary?

**Comment by MaxNoe** [comment]
`timing.py`:

```python
import uproot
import time

COLUMNS = [
    'MHillas_{telescope_id}.fLength',
    'MHillas_{telescope_id}.fWidth',
    'MHillas_{telescope_id}.fSize',
    'MHillas_{telescope_id}.fMeanX',
    'MHillas_{telescope_id}.fMeanY',
    'MHillas_{telescope_id}.fDelta',
    'MHillasExt_{telescope_id}.fM3Long',
    'MHillasExt_{telescope_id}.fM3Trans',
    'MNewImagePar_{telescope_id}.fLeakage1',
    'MNewImagePar_{telescope_id}.fLeakage2',
    'MNewImagePar_{telescope_id}.fConc',
]


f = uproot.open('gamma.root')
tree = f['Events']

columns = []
for telescope_id in range(1, 500):
    columns.extend([
        col.format(telescope_id=telescope_id)
        for col in COLUMNS
    ])

for N in (1, 10, 100, 1000, 2000):
    t0 = time.perf_counter()
    tree.arrays(columns[:N])
    print('{: 5d} done in {:8.3f}'.format(N, time.perf_counter() - t0))
```

And the file:
https://nextcloud.e5.physik.tu-dortmund.de/index.php/s/PqPCmn8ogiX9oWJ

**Comment by MaxNoe** [comment]
Thanks for looking into this!

**Comment by jpivarski** [comment]
28 seconds → 18 seconds by not rederiving a branch's `interpretation` each time. But it looks like there's more...

**Comment by jpivarski** [comment]
Beyond that, it _is_ the quadratic-time branch name lookup that's responsible for the timings. You can see this by running them in reverse:

```python
for N in range(2000, 0, -1):
    t0 = time.perf_counter()
    arrays = tree.arrays(columns[N:N+1])
    t = time.perf_counter() - t0
    mb = sum(x.content.nbytes + x.offsets.nbytes if isinstance(x, awkward.JaggedArray) else x.nbytes for x in arrays.values())
    nb = sum(tree[x].numbaskets for x in columns[N:N+1])
    print('{: 5d} ({: 5d} baskets, {: 5d} MB) done in {:8.3f}: {}'.format(N, nb, mb, t, columns[N]))
```

This does the last branches first, typically 30 ms per branch, and the first branches last, < 1 ms per branch. I'll put in a hashmap-based lookup for branch names.

**Comment by jpivarski** [comment]
PR #165 (will be uproot 3.2.4) fixes this problem. See the progress of that PR for updates.

Going back to your original timing.py:

```
    1 done in    0.000
   10 done in    0.002
  100 done in    0.020
 1000 done in    0.141
 2000 done in    0.256
```

**Comment by MaxNoe** [comment]
I can just repeat #162. This project changes everything!

**Comment by jpivarski** [comment]
Thanks!

The did has been deployed to PyPI gas 3.2.4.

**Comment by MaxNoe** [comment]
Works great!

I profiled again, and now at the initial tree lookup `f['Events']`, 28 seconds are spend in  the list comprehension in: 
https://github.com/scikit-hep/uproot/blob/28b6e24ee21b04ca470b11e4d77312713aa77246/uproot/rootio.py#L1222

Is that unavoidable?

**Comment by jpivarski** [comment]
I was thinking of mentioning that. It's not necessarily in that one loop you highlighted— more generally, it's the Python code to get the branch definitions. That's something that could possibly be optimized, and the part for which C++ will always be faster than Python. It's not the easy-gain optimization.

Part of the problem is "easy gain" because there's one large parameter: the number of events. We can get good performance for that because branch data are simple enough to cast as Numpy. That is, we know that a particular part of the file is a huge array of floating point numbers of a particular type, so we just slice it off the disk and use `numpy.frombuffer` to make it an array. That's what this whole project was founded on.

But to get to that point, we have to go through some complex data structures to learn where the arrays start and end and what they mean. Those data structures are too complex to be cast as arrays. The line of code you highlighted loads objects of unknown type, learns their types, and creates Python class instances for each one of them using deserialization code that isn't known until the ROOT file header is read (its "streamers"). Most of those objects, in your case, are TBranches and TLeaves.

Optimizing that code would be as hard as general code optimization. If there's an obvious hotspot (I'll take a look, for your file), then maybe I can fix it. But in general, there's not a large parameter to optimize, like the number of events.

If there isn't an obvious hotspot, then the only thing that could make a big dent would be to replace that searching-for-arrays code with C++. Presently, uproot has no compiled code and that makes it easier for some people to install, but adding a little compiled code wouldn't be terrible, especially if it's an optional add-on for performance. However, it would be a lot of work to write. To ease the transition, it should probably be written in Cython.

For the foreseeable future, I won't have time to write that Cython extension.

**Comment by jpivarski** [comment]
I tried it, and 93% of the time was spent loading TBranch objects because you have a lot of branches. The functions called within the TBranch reading function are essential— `Struct.unpack` turns bytes into Python numbers, `Cursor.string` unpacks names, etc.

It's exacerbated by the fact that your TBranches are nested within TBranchElements, so there are a lot of intermediate branches whose purpose is only to organize the `fLength`, `fWidth`, `fDelta`, etc. of each telescope. A different data structure, perhaps an array of telescopes, would create far fewer branches in the file and would therefore be faster to read by ROOT or uproot, but especially uproot.

If, in ROOT, you can get `TTree::Print` to write far less output on a new TTree definition, you'll have a faster time loading it for reasons provided in my previous comment. Or you could just live with the startup time.

**Comment by MaxNoe** [comment]
Thanks again for looking into this.

Unfortunately changing the root file structure is something that will not happen ;) 

So I will just live with the time, It's faster than the c++ code I wrote and does not require ROOT and MARS. The last part alone would make it the better solution.

**Comment by jpivarski** [comment]
You know... If have to think about what it would take to make the TTree object pickleable, and I don't know if a picked TTree would be faster to load— it would also have a weird relationship with the ROOT file (you'd have to match up the pickle file with the ROOT file)— but maybe that could be used to suffer the loading cost only once...

The fact that TTree and TBranch class definitions are discovered on the fly from ROOT streamers might also complicate that. It's just an idea.
