### ISSUE TITLE
Reading in RooFit objects

### ISSUE THREAD

**Issue by shane-breeze** [scikit-hep/uproot#169]
I'm not sure if uproot is designed to be able to read in RooFit objects yet, so first of all should this be possible in the latest version of uproot?

I gave it a go regardless: I tried reading in a `RooWorkspace` and got the following error:

```
>>> import uproot
>>> ws = uproot.open("datacard.root")["w"] # read in RooWorkspace object
...
  File "<generated from TStreamerInfo 'RooWorkspace' at 0x7fa2f8832550>", line 37, in _readinto
NameError: global name 'RooWorkspace_3a3a_CodeRepo' is not defined
```

It seems to recognise that it's a `RooWorkspace` but fails somewhere after that.

**Comment by jpivarski** [comment]
I don't actually know a lot about RooFit. In principle, uproot should be able to read them, and working through the process of making that happen would shake out some bugs in the corners of that code. The `NameError` above is probably a case of me looking for the C++ name (`RooWorkspace::CodeRepo`) instead of its Python translation (`RooWorkspace_3a3a_CodeRepo`). Those sorts of things are easy to fix with an example but hard to catch by eye.

Do you have an example? I'm rushing to meet a deadline today, but I won't be able to go anywhere with this until I have a sample. (I suppose I could look up a "first steps in RooFit" example, but it would be nice to solve your particular problem.)

**Comment by jpivarski** [comment]
Let me know if you really need this capability and are willing to iterate on eliminating the bugs for your use-case. They may be trivial (the first one looks trivial) but that's not guaranteed. I'd also need to know which classes you'll be needing to direct our search for bugs.

Keep in mind that we won't be _writing_ RooWorkspaces anytime soon— your use-case would have to have something to gain from reading RooWorkspaces in Python that were created (fitted) in ROOT. I can't think of anything right now...

(Oh, and I would of course want to eliminate _all_ deserialization bugs, but they can only be discovered by example and the space is hard to cover. Therefore, I'm doing it in response to use-cases.)
