### ISSUE TITLE
Enable compression while writing

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/uproot#181]
We set fCompress = 0 while creating a TFile using uproot - This means that the file isn't compressed. We need to add support for writing compressed ROOT files.

**Comment by jpivarski** [comment]
Yes, and to be clear: ROOT data are compressed object by object, so some objects may be compressed and others not. Individual baskets in a TTree are individually compressible objects. The file-level `fCompress` setting is just a policy for choosing compression settings for new objects. The reading code, for example, ignores it because we don't know if an object is compressed until we compare its `fNbytes` against its `fKeylen + fObjlen`.

**Comment by jpivarski** [comment]
I'm just testing a GitHub app.

**Comment by jpivarski** [comment]
@reikdas This might be helpful: https://github.com/python-lz4/python-lz4/blob/master/lz4/frame/__init__.py#L133-L136

You can open a PR with `[WIP]` in its name and I'll know that it's a work in progress. (Also, a bot won't let me accidentally merge it.) That would give me a forum where I can communicate about the branch, including line-by-line.
