### ISSUE TITLE
Tree structure

### ISSUE THREAD

**Issue by xxiang4** [scikit-hep/uproot#185]
We're trying to read this root file: 
https://www.dropbox.com/s/x22xtnx1mfw0vbn/N_test_7_100.root?dl=0

We're dealing with the `DataTree`, which has a complicated structure. It requires loading a class library to read everything in ROOT. Can uproot load class library like in ROOT. In particular, we are having trouble reading `Event.tracks.steps` via uproot properly. 

Thanks,
Xin

**Comment by jpivarski** [comment]
You're right about that complicated structure. I've been trying to figure it out today, but I have a number of unsolved questions. (I can find the data, but I can't figure out why they begin and end where they do in the byte stream.) The thing that makes this most complicated is the fact that ROOT doesn't split data deeper than one level of jaggedness: there's an arbitrary number of tracks, so the arbitrary-length strings (`sParticleName`, `sCreatorProcess`) and arbitrary-length records (`steps`) are encoded in a completely different way than they would be if they had been split.

The original error message didn't correctly express what the problem is: it was an error in error-handling code. If it had been successful, you would have gotten empty objects with a message saying, "I can't read this."

Also, if I do manage to reverse engineer this new encoding (nested objects in _unsplit_ data), it wouldn't have the performance that uproot was designed for. The motivation for uproot is that _split_ data are encoded as simple arrays that can be cast to Numpy very quickly, with little intervention from slow Python. The _unsplit_ data requires slow Python in every step, so it might not be a big improvement over PyROOT.

If you want the speed of Numpy and can change your data format, try making a new TTree of just tracks: one track is one entry, ignoring event boundaries. In each event of your Event TTree, keep track of the starting tracks TTree entry index and number of tracks in this event, so that you retain the structure of which tracks belong to which events.

By putting tracks in their own TTree without event boundaries, they'll get more deeply split by ROOT and it will be much easier— and faster— to read them in uproot.

**Comment by jpivarski** [comment]
Do you still need this? My last comment said I couldn't solve it, but I gave you suggestions for a work-around. Are you all set?

**Comment by xxiang4** [comment]
Hi Jim, yea, we are able to work around it by simplifying the tree structure.

**Comment by jpivarski** [comment]
Great. I'm sorry I couldn't help in this case, but I'm glad you're up and running.
