### ISSUE TITLE
Jagged arrays  and double32_t

### ISSUE THREAD

**Issue by fmazzasc** [scikit-hep/uproot#187]
Hi, i have issues in dealing with Double32_t in jagged arrays. The error message is:
'asdouble32' object has no attribute 'itemsize'

I don't have this problem with flat arrays. How i can fix this?

**Comment by jpivarski** [comment]
This is probably an uproot 2 → 3 hiccup that couldn't be tested for lack of examples. Could you point me to an example so that I can try it out, find the bug, and fix it? Thanks!

**Comment by jpivarski** [comment]
I just fixed it in branch "[issue-187](https://github.com/scikit-hep/uproot/tree/issue-187)" and will make a new version of it (uproot 3.2.13). Can I include your file as "issue-187.root" to use it in a unit test? The file would then be publicly accessible if someone knew where to look, which is why I'm asking.

**Comment by fmazzasc** [comment]
Yes, you can use it. If u want a smaller version we can also update this.

**Comment by jpivarski** [comment]
Great, thanks! 1 MB is already small enough. Big files are bad for git, but mostly if they change with time, which these tests do not.

**Comment by jpivarski** [comment]
The new branch (with tests) has been merged into master and the machinery has started to deploy it to PyPI as uproot 3.2.13. That will probably be done in 5‒10 minutes.

**Comment by jpivarski** [comment]
It's done: enjoy!
