### ISSUE TITLE
documentation for histogram unclear

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#193]
How to use the histogram class in uproot is not clear from the documentation here:
https://github.com/scikit-hep/uproot

Could this example please be expanded into one, which shows how to get the basic quantities: the bin edges, the bin values, and the bin variances?

From looking at the methods, it is clear how to get the values (`values` or `allvalues`) and the variances (`variances` or `allvariances`). It is not clear how to get the bin edges in the same way. The method `low` does not return the low edges of all bins, it returns just the lowest edges. Similar for `high`.

I think for consistency, there should be a field which allows to access the bin edges as an array with shape [Nx2], like `[[low_edge0, low_edge1], [low_edge1, low_edge2], ...]`

**Comment by jpivarski** [comment]
Are you writing interfaces between Python-Boost histogram and uproot? If so, you may want to limit yourself to the attributes whose names start with _f, counterintuitive as that may sound.

The public interface to histograms is defined in the uproot-methods library, is largely user-contributed, and is intended to make analysis easier (which is a different activity than programming— different API stability requirements). When users want convenience methods on histograms, I point them to the right place in uproot-methods and let them design it to fit their needs.

That could be bad for code that interfaces another library with uproot's histograms (programming, rather than analysis). An API change to make analysis more convenient would break that interface, and then there would be an issue aligning versions.

The attributes whose names start with _f, however, come directly from ROOT and are very stable. They are literal translations of the C++ private members of the corresponding class, generated automatically. For ROOT's own backward compatibility, they are only added to. As private members, their definition is not determined by convenience in analysis.

So if I were writing a histogram interface, I'd go directly to these attributes because— ironically, I know— they're the most stable across versions.

**Comment by HDembinski** [comment]
I am just trying out uproot as a data analysis user here, so I should probably go to uproot-methods to implement more convenience for working with histograms.

I have a student and I recommended her to use uproot, but she eventually chose root_numpy, saying that the uproot docs were too confusing for her. So I gave it a try myself. I am personally biased towards uproot, of course, but she has a point. The documentation for reading trees is very good, as far as I can see, but the docs for histogram reading are sparse.

**Comment by jpivarski** [comment]
I see. It is true that dealing with histograms was an afterthought to the project (it came for free because we need the flexibility of deserializing from streamers, anyway). Technically, the interface to histograms is all in uproot-methods, so it isn't clear where that documentation should go.

**Comment by jpivarski** [comment]
Here's how to get in the back door, if you're ever looking into it:

```python
>>> import uproot
>>> f = uproot.open("tests/samples/histograms.root")
>>> f._context.classes["TH1"]
<class 'uproot.rootio.TH1'>
```

This class object lives in a dictionary because it was generated from streamers. It's associated with the file that defined it. If we iterate over many ROOT files, each one defines a new set of classes. Because of things like this, I sometimes feel that what ROOT is trying to do fits the Python model better than the C++ model.

```python
>>> f._context.classes["TH1"].__bases__
(<class 'TH1.Methods'>, <class 'uproot.rootio.TNamed'>, <class 'uproot.rootio.TAttLine'>,
 <class 'uproot.rootio.TAttFill'>, <class 'uproot.rootio.TAttMarker'>)
```

That first base class, TH1.Methods, is from uproot-methods. The rest are other classes generated from streamers. The code that defined it is attached as a `_pycode` string.

```python
>>> print(f._context.classes["TH1"]._pycode)
class TH1(uproot_methods.classes.TH1.Methods, TNamed, TAttLine, TAttFill, TAttMarker):
    _methods = uproot_methods.classes.TH1.Methods
    _bases = [TNamed, TAttLine, TAttFill, TAttMarker]
    @classmethod
    def _recarray(cls):
        out = []
        out.append((' cnt', 'u4'))
        out.append((' vers', 'u2'))
        for base in cls._bases:
            out.extend(base._recarray())
        out.append(('fNcells', numpy.dtype('>i4')))
        out.extend(TAxis._recarray())
        out.extend(TAxis._recarray())
        out.extend(TAxis._recarray())
        out.append(('fBarOffset', numpy.dtype('>i2')))
        out.append(('fBarWidth', numpy.dtype('>i2')))
        out.append(('fEntries', numpy.dtype('>f8')))
        out.append(('fTsumw', numpy.dtype('>f8')))
        out.append(('fTsumw2', numpy.dtype('>f8')))
        out.append(('fTsumwx', numpy.dtype('>f8')))
        out.append(('fTsumwx2', numpy.dtype('>f8')))
        out.append(('fMaximum', numpy.dtype('>f8')))
        out.append(('fMinimum', numpy.dtype('>f8')))
        out.append(('fNormFactor', numpy.dtype('>f8')))
        out.extend(TArrayD._recarray())
        out.extend(TArrayD._recarray())
        out.extend(TString._recarray())
        out.extend(fFunctions._recarray())
        out.append(('fBufferSize', numpy.dtype('>u4')))
        raise ValueError('not a recarray')
        out.append(('fBinStatErrOpt', numpy.dtype('>i4')))
        return out
    _fields = ['fNcells', 'fXaxis', 'fYaxis', 'fZaxis', 'fBarOffset', 'fBarWidth', 'fEntries', 'fTsumw', 'fTsumw2', 'fTsumwx', 'fTsumwx2', 'fMaximum', 'fMinimum', 'fNormFactor', 'fContour', 'fSumw2', 'fOption', 'fFunctions', 'fBufferSize', 'fBuffer', 'fBinStatErrOpt']
    _classname = b'TH1'
    _versions = versions
    _classversion = 7
    @classmethod
    def _readinto(cls, self, source, cursor, context, parent):
        start, cnt, classversion = _startcheck(source, cursor)
        if cls._classversion != classversion:
            cursor.index = start
            if classversion in cls._versions:
                return cls._versions[classversion]._readinto(self, source, cursor, context, parent)
            else:
                return Undefined.read(source, cursor, context, parent, cls.__name__)
        TNamed._readinto(self, source, cursor, context, parent)
        TAttLine._readinto(self, source, cursor, context, parent)
        TAttFill._readinto(self, source, cursor, context, parent)
        TAttMarker._readinto(self, source, cursor, context, parent)
        self._fNcells = cursor.field(source, cls._format1)
        self._fXaxis = TAxis.read(source, cursor, context, self)
        self._fYaxis = TAxis.read(source, cursor, context, self)
        self._fZaxis = TAxis.read(source, cursor, context, self)
        self._fBarOffset, self._fBarWidth, self._fEntries, self._fTsumw, self._fTsumw2, self._fTsumwx, self._fTsumwx2, self._fMaximum, self._fMinimum, self._fNormFactor = cursor.fields(source, cls._format2)
        self._fContour = TArrayD.read(source, cursor, context, self)
        self._fSumw2 = TArrayD.read(source, cursor, context, self)
        self._fOption = TString.read(source, cursor, context, self)
        self._fFunctions = TList.read(source, cursor, context, self)
        self._fBufferSize = cursor.field(source, cls._format3)
        if getattr(context, "speedbump", True):
            cursor.skip(1)
        self._fBuffer = cursor.array(source, self._fBufferSize, cls._dtype1)
        self._fBinStatErrOpt = cursor.field(source, cls._format4)
        if self.__class__.__name__ == cls.__name__:
            self.__class__ = cls._versions[classversion]
        try:
            _endcheck(start, cursor, cnt)
        except ValueError:
            cursor.index = start
            return Undefined.read(source, cursor, context, parent, cls.__name__)
        return self
    _format1 = struct.Struct('>i')
    _format2 = struct.Struct('>hhdddddddd')
    _format3 = struct.Struct('>I')
    _format4 = struct.Struct('>i')
    _dtype1 = numpy.dtype('>f8')
```

All of that was generated for various purposes; `_readinto` is the main deserializing function, `_recarray` is  for attempting to read a bunch of objects from a TTree as a Numpy record array. (TH1 objects can be read from TTrees, but not as a record array because it contains variable-width structures. The `ValueError` in that function prevents it.) For performance, I made some attempt to consolidate adjacent numerical fields into single `struct.Struct.unpack` calls because the overhead of that call far exceeds the deserialization, but whenever a variable-length thing appears between two numbers, batching is thwarted.

By the time we get to the bin contents (defined in TH1F, not TH1, through its inheritance from the non-auto-generated TArrayF), we've just spent a lot more time than it would take to box a hundred numbers into a Python list, as opposed to casting it as an array. Maybe for extremely large histograms it might matter, but not for most.

The methods in uproot-methods rely on the existence of particular `_f*` attributes by duck typing. Some of them use `hasattr` and `getattr` with a third attribute to be more conservative, to protect against data from old versions of ROOT that lack a given attribute.

To get back to the point of this thread, it's the TH1.Methods that need to be documented, since these are the physicist-user's entry point. But they're also the most in flux because— as you've noticed— this interface is underdeveloped. The `_f*` attributes, however, are stable, by definition more stable than the TH1.Methods that use them. When I thought you were using this as an API, that's why I recommended writing the API against the `_f*` attributes.

**Comment by HDembinski** [comment]
Makes sense, thank you for the tour :)

**Comment by jpivarski** [comment]
Documentation of histogram methods should be hosted by uproot-methods (long README? Binder? wiki? uproot-methods.readthedocs.org?) so that it's version-controlled with that repository, rather than uproot. The uproot README should have a prominent link to it, though. As you can see above, I've moved this issue there.
