### ISSUE TITLE
TH1D class methods `values`, `allvalues`, `variances`, `allvariances` return lists, not arrays

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#194]
I think they should return numpy arrays instead of lists. numpy is strict dependency for uproot, so it would be ok to return arrays. Returning arrays is more efficient, perhaps they can be views even into the memory of the TH1D object.

**Comment by jpivarski** [comment]
uproot has fast components and slow components: fast when reading a TTree basket into an array, slow when parsing headers of objects. Reading histograms is squarely in the latter category. When uproot starts up, it doesn't even know how to deserialize a histogram— it has to generate a class from the streamers it finds in the ROOT file header. That generated code is a plodding sequence of calls to struct.unpack. The bin contents are a minority of the data at the end of the object.

Histograms return lists because histograms _are_ lists. uproot has to follow the ROOT class hierarchy because its classes are defined by streamers. All TH* classes are subclasses of a TArray*, which I've made a subclass of the Python list as the most idiomatic choice. There are many other situations where TArrays are used, and something with all the properties of a list is the right choice in those cases.

I could change the definition of uproot.rootio.TArray to be a class that _behaves_ like a list but internally keeps a view of the raw array, so that histograms can return this. (Note: the raw array is big-endian.) Due to all the muck that has to be done earlier (deserializing all the things attached to the histogram), it would only make a performance difference for the biggest histograms, like a big TH2. Without subclassing list, I'd have to write all the methods to emulate a list. (Maybe there's something in containers.abc I could use.)

It can be done, but it doesn't seem like the reward to effort is high. Is it?

**Comment by jpivarski** [comment]
This is followed up by issue scikit-hep/uproot-methods#18 and PR scikit-hep/uproot-methods#21. We agreed not to change the internal representation of `TArray*`, only the outputs of these methods as an API thing. Therefore, no changes need to be made to the uproot library itself and I can close this issue.
