### ISSUE TITLE
Reading nested TTree TBranchElement

### ISSUE THREAD

**Issue by jdbrice** [scikit-hep/uproot#198]
I am new to uproot so I may be missing something, but from documents i think the following should work. I have a ROOT TTree made by saving a c++ class as a TClonesArray into a TTree. The ttree.show() method seems to understand the relevant data inside the tree but I do not know how to read it out.

below is with python 3.6, I also tried python 2.7 with the same result.

```
>>> pairs = uproot.open("rootfiles.root")
>>> tree = pairs["PairDst"]
>>> tree
<TTree b'PairDst' at 0x000110503d30>
>>> tree.show()
Pairs                      TStreamerInfo              astable(asdtype("[(' fBits', '>u8'), (' fUniqueID', '>u8'), ('mVertexZ', '>f4'), ('mDeltaVertexZ', '>f4'), ('mGRefMult', '>u2'), ('mChargeSum', 'i1'), ('mPt', '>f4'), ('mEta', '>f4'), ('mPhi', '>f4'), ('mMass', '>f4'), ('mRapidity', '>f4'), ('d1_mYLocal', '>f4'), ('d1_mZLocal', '>f4'), ('d1_mTof', '>f4'), ('d1_mMatchFlag', 'i1'), ('d1_mLength', '>f4'), ('d1_mPt', '>f4'), ('d1_mEta', '>f4'), ('d1_mPhi', '>f4'), ('d1_mId', '>u2'), ('d1_mNHitsFit', 'i1'), ('d1_mNHitsMax', 'i1'), ('d1_mNHitsDedx', 'u1'), ('d1_mNSigmaPion', '>f4'), ('d1_mNSigmaKaon', '>f4'), ('d1_mNSigmaProton', '>f4'), ('d1_mNSigmaElectron', '>f4'), ('d1_mDCA', '>f4'), ('d1_mPid', '>f4'), ('d2_mYLocal', '>f4'), ('d2_mZLocal', '>f4'), ('d2_mTof', '>f4'), ('d2_mMatchFlag', 'i1'), ('d2_mLength', '>f4'), ('d2_mPt', '>f4'), ('d2_mEta', '>f4'), ('d2_mPhi', '>f4'), ('d2_mId', '>u2'), ('d2_mNHitsFit', 'i1'), ('d2_mNHitsMax', 'i1'), ('d2_mNHitsDedx', 'u1'), ('d2_mNSigmaPion', '>f4'), ('d2_mNSigmaKaon', '>f4'), ('d2_mNSigmaProton', '>f4'), ('d2_mNSigmaElectron', '>f4'), ('d2_mDCA', '>f4'), ('d2_mPid', '>f4')]", "[('mVertexZ', '<f4'), ('mDeltaVertexZ', '<f4'), ('mGRefMult', '<u2'), ('mChargeSum', 'i1'), ('mPt', '<f4'), ('mEta', '<f4'), ('mPhi', '<f4'), ('mMass', '<f4'), ('mRapidity', '<f4'), ('d1_mYLocal', '<f4'), ('d1_mZLocal', '<f4'), ('d1_mTof', '<f4'), ('d1_mMatchFlag', 'i1'), ('d1_mLength', '<f4'), ('d1_mPt', '<f4'), ('d1_mEta', '<f4'), ('d1_mPhi', '<f4'), ('d1_mId', '<u2'), ('d1_mNHitsFit', 'i1'), ('d1_mNHitsMax', 'i1'), ('d1_mNHitsDedx', 'u1'), ('d1_mNSigmaPion', '<f4'), ('d1_mNSigmaKaon', '<f4'), ('d1_mNSigmaProton', '<f4'), ('d1_mNSigmaElectron', '<f4'), ('d1_mDCA', '<f4'), ('d1_mPid', '<f4'), ('d2_mYLocal', '<f4'), ('d2_mZLocal', '<f4'), ('d2_mTof', '<f4'), ('d2_mMatchFlag', 'i1'), ('d2_mLength', '<f4'), ('d2_mPt', '<f4'), ('d2_mEta', '<f4'), ('d2_mPhi', '<f4'), ('d2_mId', '<u2'), ('d2_mNHitsFit', 'i1'), ('d2_mNHitsMax', 'i1'), ('d2_mNHitsDedx', 'u1'), ('d2_mNSigmaPion', '<f4'), ('d2_mNSigmaKaon', '<f4'), ('d2_mNSigmaProton', '<f4'), ('d2_mNSigmaElectron', '<f4'), ('d2_mDCA', '<f4'), ('d2_mPid', '<f4')]"))


>>> tree["Pairs"].array()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jdb/miniconda3/lib/python3.6/site-packages/uproot/tree.py", line 1269, in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
  File "/Users/jdb/miniconda3/lib/python3.6/site-packages/uproot/tree.py", line 1227, in _basket_itemoffset
    numitems = interpretation.numitems(key.border, self.basket_numentries(i))
  File "/Users/jdb/miniconda3/lib/python3.6/site-packages/uproot/interp/objects.py", line 144, in numitems
    return self.content.numitems(numbytes, numentries)
  File "/Users/jdb/miniconda3/lib/python3.6/site-packages/uproot/interp/numerical.py", line 165, in numitems
    assert remainder == 0
AssertionError

```

I also expected something like: 
```
tree["Pairs"]["mMass"]
```
or 
```
tree["Pairs.mMass"]
```
to be possible, but that simply gives a `KeyError`

**Comment by jdbrice** [comment]
also I should note that I am using uproot 3.3.0.

**Comment by jpivarski** [comment]
The assertion error is internal; you're doing the right thing.

It's not `tree["Pairs"]["mMass"]` or `tree["Pairs.mMass"]` because `mMass` is part of a leaf-list: it's not possible to read separately from the rest of its branch. (Same is true in ROOT: in a leaf-list data structure, all leaves must be read. If you want to get `mMass` without also reading everything else, you'd have to put them in separate branches.)

Without the assertion error, you could access the mass as `tree["Pairs"].array()["mMass"]`, but that's reading everything and picking out the mass.

Could you send me your file so that I can debug the assertion error? Somehow, the bytes aren't adding up to an integer multiple of the size of a single row.

**Comment by jdbrice** [comment]
Thanks for the quick response.  The data itself is pure simulation so there is no problem making it public . The files are produced with c++ compiled code (compiled against ROOT 6.14/04) using structure here: [FemtoPair.h](https://github.com/jdbrice/STARLight2PairDst/blob/master/modules/PairDstFormat/FemtoPair.h)

Here is a small sample (3Mb file) of the TTree you can get from my dropbox:
[PairDst_uproot.root](https://www.dropbox.com/s/8dn6avgre1ux2l2/PairDst_uproot.root?dl=0)
If you find it helpful it is fine with me to use it for unit tests, I can also make you an even smaller one if that helps.

The way the tree was saved results in two keys with the same name in the file with the ";1" and ";2" suffixes, I am not sure if that matters.  but maybe it is confusing the way the data is read out. Thanks for this project, I started something like this (pure python ROOT I/O) but never got this far. 

 Let me know if you need any additional info. Thanks

**Comment by jpivarski** [comment]
Okay, I can help you get started with your work, but I can't make it look like a solution you could have come up with on your own! To get your data, do this:

```python
import uproot
tree = uproot.open("PairDst_uproot.root")["PairDst"]
interpretation = uproot.asdtype([(' cnt', '<u4'), (' vers', '<u2')] + eval(str(tree["Pairs"].interpretation.content.todtype)))
data = tree["Pairs"].array(interpretation)
```

Horrible, right?

The issue is that you have simple, easy to interpret data inside a class. Classes have headers, but these headers aren't always written. The thing I don't know is why these headers are sometimes written and sometimes not. I have a standard set of rules that were derived from the ROOT files I've seen, and according to those heuristics, I expected TObject headers but not byte count and version. You have byte count and version, but not for both the `FemtoPair` and its `FemtoDstBranch` base class, just one of these and not the other.

The horrible code above adds the two fields in; I should probably create an easier way to manipulate this.

```python
tree["Pairs"].interpretation
```

gives the standard interpretation, which is missing two fields, and

```python
tree["Pairs"].interpretation.content.todtype
```

gets down to the Numpy dtype, which has many fields. (It's a [record array](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.rec.html).) To add the two extra fields at the beginning, I do

```python
[(' cnt', '<u4'), (' vers', '<u2')] + eval(str(tree["Pairs"].interpretation.content.todtype))
```

and then wrap it up as a new `asdtype` interpretation.

```python
interpretation = uproot.asdtype([(' cnt', '<u4'), (' vers', '<u2')] + eval(str(tree["Pairs"].interpretation.content.todtype)))
```

When we read an array, the first optional argument is a custom interpretation, designed to let you assert that you know how your data are laid out:

```python
data = tree["Pairs"].array(interpretation)
```

If you find that your whole dataset is too big to load into one array and want to use `uproot.iterate` or `tree.iterate`, you can still use this interpretation, but you have to associate it with the `"Pairs"` branch:

```python
for arrays in tree.iterate({"Pairs": interpretation}):
    do_something_for_subset_of_events(arrays)
```

I'm going to keep studying your file to see how it's different from the others, to see what hint the metadata can give me that these two fields are needed. But meanwhile, you can get started with your work.

**Comment by jpivarski** [comment]
Oh, you do `data["mMass"]` to get just the mass. This is a Numpy thing (see that link I gave you).
