### ISSUE TITLE
Add option in iterate method to jump files which don't have a TTree

### ISSUE THREAD

**Issue by HealthyPear** [scikit-hep/uproot#199]
Hello!

In ROOT, when issuing a TChain over many files pointing to a particular TTree, it can happen that one or more of such files are missing it (e.g. a malfunctioning subsystem).
In that case, ROOT will just print that it couldn't find the TTree in such files, and it will allow the macro or script to proceed to work on the rest.

I tried to naïvely use the *iterate* method to reproduce such TChain, but when the method encounters a file which does not have that particular TTree it crashes with a *KeyError*.

There are at least a couple of solutions (not elegant, perhaps):
* import the whole file for each file and then use only that key
* cycle through the files and check if the TTree is there - then concatenate *numpy* arrays (my current workaround)

It would be much more elegant, though, if the iterate method would be patched with an option which jumps over a file which does not have the required TTree (*treepath* in the API documentation).

I apologize if this was somewhat already present and I overlooked it.

In the meanwhile, thank you for your work!
Cheers

**Comment by jpivarski** [comment]
Sorry, this is just an oversight on my part: I didn't realize that an empty file would have no TTree object, rather than an empty TTree object. Skipping a file that lacks the requested TTree is an easy fix. (The one linked above, which closed the issue.)

Similarly, we could also skip missing files, but I think that could be a bad idea: if you don't have all the files you think you have, it's probably an analysis error that you want to be aware of. So I'll skip a missing TTree (which is given by a single, explicit path) but not a missing file (which might be buried in a file list).

The `iterate` methods don't do concatenation (you're free to do that yourself) because the purpose of the `TTree.iterate` method, at least, is to limit the memory footprint. But if you're iterating over all files in order to concatenate them in an array that spans many files, you might be interested in the (undocumented) `uproot.numentries` function, which quickly scans through a set of files and gives you the total number of entries (or broken down by file if you pass `total=False`). That way, you can preallocate an array that is just big enough for all your data and avoid doubling the memory footprint in collecting all arrays first and then concatenating. The `uproot.numentries` function takes shortcuts in reading files to get right at the number of entries.

And I just remembered to put the same check-for-missing TTree into `uproot.numentries` as `uproot.iterate`. Thanks for the bug report!

**Comment by jpivarski** [comment]
(This will be released as version 3.3.1, but I'm about to get on a plane and want to see the tests pass before publishing a release.)
