### ISSUE TITLE
cut on the converted array 

### ISSUE THREAD

**Issue by BinishB** [scikit-hep/uproot#208]
does anyone have any example to convert branch into Numpy array after applying cut

**Comment by jpivarski** [comment]
You might be looking for something like root_numpy's selection parameter, which applies a TFormula to the branch before giving it to you. uproot doesn't have anything like that: use Numpy to apply the cut.

```python
pt, eta, trigger = tree.arrays(["pt", "eta", "trigger"], outputtype=tuple)
selected_eta = eta[(pt > 30) & trigger]
```

If you're worried about performance, note that the cut arrays have to be loaded whether they're given to you to whatever you want or are used internally to apply a cut: that should be the same cost. If you need to load so many arrays to do the selection that you're running out of memory, use `tree.iterate` (for one file) or `uproot.iterate` (for many files):

```python
for pt, eta, trigger in uproot.iterate("*.root", "treename", ["pt", "eta", "trigger"], outputtype=tuple):
    selected_eta = eta[(pt > 30) & trigger]    # this array is a batch of size entrysteps
```

Unfortunately, for Numpy selections, you have to use `&` (and), `|` (or), and `~` (not), and these are whole array bitwise operations. Even more unfortunately, you have to put parentheses around comparisons because the `&`, `|`, `~` operators bind more tightly than `==`, `!=`, `>`, `>=`, `<`, `<=`.

If you don't like that syntax, see the [formulate](https://github.com/scikit-hep/formulate) project, which converts TTree::Draw syntax to and from NumExpr syntax; you could select the array using NumExpr instead.

**Comment by jpivarski** [comment]
I guess I've answered it, so I'll close this now.
