### ISSUE TITLE
TBranch->GetBasketSeek() API?

### ISSUE THREAD

**Issue by xweichu** [scikit-hep/uproot#209]
I'm trying to use uproot to analyze root files. For some reasons the offset information of baskets is needed in my project, previously I used  TBranch->GetBasketSeek(). However, looks like uproot doesn't provide such APIs? Is there a way that I can get such information?  Thanks a lot.

**Comment by jpivarski** [comment]
Right— a lot of the information about baskets is presented publicly (`basket_numentries`, `basket_numitems`, etc.) but not the seek positions. However, the seek positions are available in a private variable: `branch._fBasketSeek` is an array with valid entries from `0` to `branch.numbaskets` (beyond that, they're meaningless). Normally, you wouldn't want to depend on private variables because they might change, but in this case they won't: `branch._fBasketSeek` is a literal translation of ROOT's `fBasketSeek`, which has to stay the same for ROOT's backward compatibility.
