### ISSUE TITLE
cannot open tree with 0 baskets

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot#21]
This file is a valid ROOT file, with one TTree, which has only float Branches. It works with ROOT and root_numpy, but with uproot I get no events.

https://www.dropbox.com/s/yiyh4kosgvfgg7p/test.root?dl=0

    import uproot
    f = uproot.open("test.root")
    t = f.get("nllscan")
    print t.entries
    t.arrays()

**Comment by sbinet** [comment]
testing this with `go-hep/rootio` gives me a segfault :)

it seems the `fWriteBasket` field for all the branches of that `nllscan` tree is `0`.
@pcanal do you know what does that mean?

**Comment by chrisburr** [comment]
Is this the same issue as #14?

Uproot works as expected if I copy the tree to a new file and read that one instead:

```python
import ROOT
f = ROOT.TFile.Open('test.root')
t = f.Get('nllscan')

f2 = ROOT.TFile.Open('test-2.root', 'RECREATE')
t2 = t.CloneTree()
f2.Write()
f2.Close()
```

I guess ROOT has a method recovering files which aren't closed correctly which isn't available in uproot.

**Comment by jpivarski** [comment]
(@wiso You didn't say what error message you got when you tried that.)

uproot 2.x is a complete rewrite of 1.x, and now that it's usable, 2.x is the only supported branch. I just tried opening your file in 2.x and encountered no errors or unexpected results:

```python
>>> import uproot
>>> f = uproot.open("/tmp/downloads/test.root")
>>> list(f)
['nllscan;1']
>>> t = f["nllscan"]
>>> t
<TTree 'nllscan' at 0x700428311ad0>
>>> list(t.keys())
['status', 'nll', 'mH', 'mu_ggH', 'mu_VBF', 'mu_VH', 'mu_ttH']
>>> print t.format()
status                     NoneType                   asdtype('>i4')
nll                        NoneType                   asdtype('>f8')
mH                         NoneType                   asdtype('>f8')
mu_ggH                     NoneType                   asdtype('>f8')
mu_VBF                     NoneType                   asdtype('>f8')
mu_VH                      NoneType                   asdtype('>f8')
mu_ttH                     NoneType                   asdtype('>f8')
>>> t.array("status")
array([], dtype=int32)
>>> t.array("nll")
array([], dtype=float64)
>>> t.array("mu_ggH")
array([], dtype=float64)
>>> t.array("mu_VBF")
array([], dtype=float64)
>>> t.array("mu_ttH")
array([], dtype=float64)
>>> t.arrays()
{'status': array([], dtype=int32), 'mu_ttH': array([], dtype=float64),
 'mu_VH': array([], dtype=float64), 'mH': array([], dtype=float64),
 'mu_VBF': array([], dtype=float64), 'mu_ggH': array([], dtype=float64),
 'nll': array([], dtype=float64)}
```

So whatever was causing a problem for you is not duplicated in 2.x. I don't have a copy of 1.x easily available for a quick test.

I suspect that @chrisburr is right: it could be related to the reading-incomplete-file bug. It's easy to forget to `t->Write(); f->Close()` when writing the file, and this leads to some inconsistent information in the TBranch:

```python
>>> t.numentries              # high-level Python @property
61
>>> t.fEntries                # directly read in via streamer info
61
>>> t["status"].fEntries
61
>>> t["status"].fEntryNumber
61
>>> t["status"].fWriteBasket  # this is "t.numbaskets"
0
>>> t["status"].fBasketBytes
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)
>>> t["status"].fBasketEntry
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
>>> t["status"].fBasketSeek
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

Anything that takes the number of entries as 61 at face value could run off the end of an array.

**Comment by chrisburr** [comment]
@jpivarski Could uproot raise an exception for inconsistent files like these to avoid subtle bugs?

**Comment by wiso** [comment]
Thank you everybody for the prompt answers.
@chrisburr : I am not sure the file hasn't closed properly. I am creating the TTree merging other files:

    chain = ROOT.TChain(tree_name)
    for filename in input_filenames:
        chain.Add(filename)

    tree_out = chain.CloneTree()

    of = ROOT.TFile.Open(args.output, "recreate")
    tree_out.Write()

and I get no errors by ROOT when reading it.

@jpivarski: I get no errors, both in ROOT or uproot, I just get an empty set of arrays (while the number of entries is ok)

@jpivarski: I hope `f.Close()` is called when the destructor is called

**Comment by sbinet** [comment]
@wiso b/c of the way the CPython VM manages memory (ref-counting), there are no guarantees that a given `__del__` method will be called in time.
that's why there's the `__enter__`/`__exit__` pattern (and its `with foo() as bar: ...` context manager).
and that's why `rootpy` has implemented such a context manager. (I vaguely remember)

**Comment by sbinet** [comment]
@jpivarski still, I think it would be very interesting to see where and how ROOT/C++ is doing its magic to recover the data (and where it is?)

**Comment by jpivarski** [comment]
@chrisburr: In this case, the file contains no meaningful data, and it presents that as an empty dataset (like ROOT itself). As a user, I don't think I'd want an exception in this case. Deciding whether something is an error or not is subjective, but I prefer a relaxed attitude of throwing exceptions only when the program can't go on— there's no way to proceed. In this case, we can proceed by returning empty arrays, regardless of what `fEntries` says.

The problem is that TTree's `fEntries` and TBranch's `fEntries`, `fEntryNumber`, and `fBasketEntry[fWriteBasket]` can, in principle, disagree with each other and with the actual number of array elements you get out of the baskets. The user might want to know about such inconsistencies, if they exist. However, this is just one validity-test somebody might want to make— if we continue down this road, what we're really asking for is a ROOT-linter. It's nice to be able to separate the functions of "read anything you can out of this file" versus "tell me everything that's wrong with this file." As an extreme example, web browsers can do a lot with broken HTML, but if you want to verify that an HTML sample is good for publication, you'd go to a linter, not a web browser.

@wiso: By `f.Close()`, you mean ROOT, right? (uproot doesn't write anything, yet.) I'm pretty sure that ROOT does not close files in the TFile destructor because I have seen this behavior before. I personally don't know if C++ guarantees that all destructors will be called, but if it does, then adding `Close()` to the TFile destructor wouldn't be a bad idea. In Python, you cannot guarantee that `__del__` will ever be called, so this would be a bad practice in Python. The fact that you're controlling ROOT from Python (PyROOT) could confuse that issue: Python won't explicitly free the TFile proxy when it shuts down because everything is eliminated in the end of process anyway— memory and file handles alike. ROOT might be left holding onto the TFile because the TFile proxy was never destroyed.

On second thought, maybe ROOT *does* `Close()` in the TFile destructor in pure C++, but PyROOT prevents it. That could account for the observation of unfinished files in the wild. Maybe they were all made in PyROOT.

**Comment by jpivarski** [comment]
Wait, are we saying that ROOT finds data there? That the proper behavior is to return non-empty arrays?

**Comment by chrisburr** [comment]
Yes! (And the it's the same for #14)

**Comment by jpivarski** [comment]
Okay, if you do a `CloneTree()` in ROOT, it *does* find some data. And since the "mH" array (Higgs mass?) scans from 124.0 to 126.0, I'm inclined to believe it's finding the correct data. But that data *has no pointer* from the TBranch:

```python
>>> import uproot
>>> f = uproot.open("tests/samples/no_baskets.root")
>>> t = f["nllscan"]
>>> b = t["mH"]
>>> b.__dict__
{'_context': <uproot.rootio._FileContext object at 0x70209e9cf250>, 'fEntries': 61, 'fZipBytes': 0, 'fFillStyle': 1001, 'fFillColor': 0, 'fMaxBaskets': 10, 'fLeaves': [<TLeafD 'mH' at 0x70209e9f9f90>], 'fFirstEntry': 0, 'fEntryOffsetLen': 0, '_source': <uproot.source.compressed.CompressedSource object at 0x70209e9f9a90>, 'fBasketEntry': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'fTotBytes': 0, 'fBasketSeek': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'fBasketBytes': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), 'fOffset': 0, 'version': 1, 'fCompress': 1, '_streamer': None, 'fBranches': [], 'fEntryNumber': 61, 'fWriteBasket': 0, 'fName': 'mH', 'fSplitLevel': 0, 'fTitle': 'mH/D', 'fFileName': '', 'fBasketSize': 32000}
```

(All the attributes starting with "f" are directly from the file, deserialized by the streamer info.)

I don't see any seek points in the TTree, either:

```python
>>> t.__dict__
{'fMarkerStyle': 1, 'fLineColor': 602, 'fZipBytes': 0, 'fFillStyle': 1001, 'fFillColor': 0, 'fSavedBytes': 0, 'fEntries': 61, 'fBranchRef': None, 'fAutoFlush': -30000000, 'fFlushedBytes': 0, 'fMarkerColor': 1, 'fLineStyle': 1, 'fLeaves': [<TLeafI 'status' at 0x70209e9b6fd0>, <TLeafD 'nll' at 0x70209e9b6f90>, <TLeafD 'mH' at 0x70209e9f9f90>, <TLeafD 'mu_ggH' at 0x70209e9f9cd0>, <TLeafD 'mu_VBF' at 0x70209e9f9c10>, <TLeafD 'mu_VH' at 0x70209e9f9610>, <TLeafD 'mu_ttH' at 0x70209e9f9d90>], 'version': 1, 'fNClusterRange': 0, 'fLineWidth': 1, 'fAutoSave': -300000000, 'fClusterSize': array([], dtype=int64), 'fBranches': [<TBranch 'status' at 0x70209e9cf150>, <TBranch 'nll' at 0x70209e9cf050>, <TBranch 'mH' at 0x70209e9b6f50>, <TBranch 'mu_ggH' at 0x70209e9f94d0>, <TBranch 'mu_VBF' at 0x70209e9f9c50>, <TBranch 'mu_VH' at 0x70209e9f9dd0>, <TBranch 'mu_ttH' at 0x70209e9f9590>], 'fDefaultEntryOffsetLen': 1000, 'fClusterRangeEnd': array([], dtype=int64), 'fUserInfo': None, 'fMaxEntryLoop': 1000000000000, 'fIndex': [], 'fMaxVirtualSize': 0, 'fName': 'nllscan', 'fWeight': 1.0, 'fIndexValues': [], 'fAliases': None, 'fEstimate': 1000000, 'fUpdate': 0, 'fTitle': 'nllscan', 'fTreeIndex': None, 'fMaxEntries': 1000000000000, 'fTimerInterval': 0, 'fTotBytes': 0, 'fMarkerSize': 1.0, 'fScanField': 25, 'fFriends': None}
```

Wherever `CloneTree()` is getting that information from, it's not the TBranch or TTree as deserialized from the streamers. Perhaps it scans the whole file, looking for anything that looks like a TKey header? @pcanal, what is ROOT doing in such a case?

**Comment by jpivarski** [comment]
It could be `TFile::Recover()` (called automatically upon opening a file).

https://root.cern.ch/doc/master/classTFile.html#ae5f85941cbcb48048de3b8d2df24540b

**Comment by wiso** [comment]
Even if this is probably OT, I have tried to add `of.Close()`: nothing changed, 0 baskets.

**Comment by jpivarski** [comment]
Apparently, you can walk through all the TKeys in a file by starting at fBEGIN and stepping in sizes of each TKey's nbytes (i.e. there's no padding between key-value pairs). TFile::Recover checks to see if the class name is "TBasket" and presumably attaches them to their parent branches.

This could become an opt-in feature, or one that is invoked by a discrepancy between the stated number of entries and the fBasketEntries. It would be a heavyweight operation, though, since it would touch many of the pages on disk, while making use of only a few bytes (the key headers).

**Comment by jpivarski** [comment]
There's enough information in hidden members (starting with underscores) to do this walk through all the TKeys in the file:

```python
>>> import uproot
>>> f = uproot.open("tests/samples/no_baskets.root")
>>> 
>>> source = f._keys[0]._source.parent()
>>> cursor = uproot.source.cursor.Cursor(f._context.tfile["fBEGIN"])
>>> 
>>> keys = []
>>> while cursor.index < f._context.tfile["fEND"]:
...   print "pos", cursor.index
...   key = uproot.rootio.TKey.read(source, cursor.copied(), f._context)
...   cursor.skip(key.fNbytes)
...   print key.fClassName, repr(key.fName), key.fNbytes, key.fVersion
...   keys.append(key)
... 
pos 100
TFile 'merged__AsimovSB_mH12509__ADD__LARCELLNONLINEARITY.root' 206 4
pos 306
TTree 'nllscan' 3290 4
pos 3596
TList 'StreamerInfo' 4484 4
pos 8080
TFile 'merged__AsimovSB_mH12509__ADD__LARCELLNONLINEARITY.root' 141 4
pos 8221
TFile 'merged__AsimovSB_mH12509__ADD__LARCELLNONLINEARITY.root' 99 4
```

The second TKey really is the TTree, and we can load it in a non-standard way (through this exhaustive list of keys, rather than through directories as you usually would). But it is exactly the same TTree we saw before: no pointers to basket keys.

```python
>>> t = keys[1].get()
>>> t
<TTree 'nllscan' at 0x796350396890>
>>> list(t.allkeys())
['status', 'nll', 'mH', 'mu_ggH', 'mu_VBF', 'mu_VH', 'mu_ttH']
>>> t["mH"].fBasketSeek
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
>>> t["mH"].fBasketEntry
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

Baskets are supposed to be free-floating key-value pairs in the file. Therefore, I would have expected something more like this (using the "tests/foriter.root" file, which has many small baskets):

```python
>>> import uproot
>>> f = uproot.open("tests/samples/foriter.root")
>>> source = f._keys[0]._source.parent()
>>> cursor = uproot.source.cursor.Cursor(f._context.tfile["fBEGIN"])
>>> 
>>> keys = []
>>> while cursor.index < f._context.tfile["fEND"]:
...   print "pos", cursor.index
...   key = uproot.rootio.TKey.read(source, cursor.copied(), f._context)
...   cursor.skip(key.fNbytes)
...   print key.fClassName, repr(key.fName), key.fNbytes, key.fVersion
...   keys.append(key)
... 
pos 100
TFile 'foriter.root' 120 4
pos 220
TBasket 'data' 98 1004
pos 318
TBasket 'data' 98 1004
pos 416
TBasket 'data' 98 1004
pos 514
TBasket 'data' 98 1004
pos 612
TBasket 'data' 98 1004
pos 710
TBasket 'data' 98 1004
pos 808
TBasket 'data' 98 1004
pos 906
TBasket 'data' 90 1004
pos 996
TTree 'foriter' 435 4
pos 1431
TList 'StreamerInfo' 4355 4
pos 5786
TFile 'foriter.root' 122 4
pos 5908
TFile 'foriter.root' 56 4
```

It is curious— for both files— that the last two keys in the file are TFile. Going back to the file with missing baskets, I print out their keys and their contents:

   * second-to-last TKey, which is called a TFile, but has a different structure

```python
>>> print uproot.source.cursor.Cursor(keys[3].fSeekKey).hexdump(source,
...                                 keys[3].fKeylen)   # key header
```
```
00017620  00 00 00 8d 00 04 00 00  00 34 5a f7 73 d0 00 59  |.........4Z.s..Y|
00017640  00 01 00 00 1f 90 00 00  00 64 05 54 46 69 6c 65  |.........d.TFile|
00017660  37 6d 65 72 67 65 64 5f  5f 41 73 69 6d 6f 76 53  |7merged__AsimovS|
00017700  42 5f 6d 48 31 32 35 30  39 5f 5f 41 44 44 5f 5f  |B_mH12509__ADD__|
00017720  4c 41 52 43 45 4c 4c 4e  4f 4e 4c 49 4e 45 41 52  |LARCELLNONLINEAR|
00017740  49 54 59 2e 72 6f 6f 74  00                       |ITY.root.       |
```
```python
>>> print uproot.source.cursor.Cursor(keys[3].fSeekKey + keys[3].fKeylen).hexdump(source,
...                                 keys[3].fNbytes - keys[3].fKeylen)   # key contents
```
```
00017751  00 00 00 01 00 00 0c da  00 04 00 00 1f 25 5a f7  |.............%Z.|
00017771  73 d0 00 30 00 01 00 00  01 32 00 00 00 64 05 54  |s..0.....2...d.T|
00020011  54 72 65 65 07 6e 6c 6c  73 63 61 6e 07 6e 6c 6c  |Tree.nllscan.nll|
00020031  73 63 61 6e                                       |scan            |
```

   * last TKey, which is called a TFile, but it has only 10 bytes!
```python
>>> print uproot.source.cursor.Cursor(keys[4].fSeekKey).hexdump(source,
...                                 keys[4].fKeylen)   # key header
```
```
00020035  00 00 00 63 00 04 00 00  00 0a 5a f7 73 d0 00 59  |...c......Z.s..Y|
00020055  00 01 00 00 20 1d 00 00  00 64 05 54 46 69 6c 65  |.... ....d.TFile|
00020075  37 6d 65 72 67 65 64 5f  5f 41 73 69 6d 6f 76 53  |7merged__AsimovS|
00020115  42 5f 6d 48 31 32 35 30  39 5f 5f 41 44 44 5f 5f  |B_mH12509__ADD__|
00020135  4c 41 52 43 45 4c 4c 4e  4f 4e 4c 49 4e 45 41 52  |LARCELLNONLINEAR|
00020155  49 54 59 2e 72 6f 6f 74  00                       |ITY.root.       |
```
```python
>>> print uproot.source.cursor.Cursor(keys[4].fSeekKey + keys[4].fKeylen).hexdump(source,
...                                 keys[4].fNbytes - keys[4].fKeylen)   # key contents
```
```
00020166  00 01 00 00 20 80 77 35  94 00                    |.... .w5..      |
```

I wonder if these are partial TFiles created by AutoSave. The first of these (`key[3]`) is just the number 1 followed by a well-formed TKey for the TTree. This is consistent with being a list of TDirectory keys with one element (just as the main TFile is, for this file). We can parse it:

```python
>>> mysterykey = uproot.rootio.TKey.read(source, uproot.source.cursor.Cursor(
...                  keys[3].fSeekKey + keys[3].fKeylen + 4), f._context)
```

but it yields no new information:

```python
>>> t2 = mysterykey.get()
>>> t2
<TTree 'nllscan' at 0x79635036c450>
>>> list(t2.allkeys())
['status', 'nll', 'mH', 'mu_ggH', 'mu_VBF', 'mu_VH', 'mu_ttH']
>>> t["mH"].fBasketSeek
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
>>> t["mH"].fBasketEntry
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

because it's exactly the same TTree:

```python
>>> mysterykey.fSeekKey
306
>>> keys[1].fSeekKey
306
```

So in the end, I don't see where that data could be hiding!

**Comment by pcanal** [comment]
So the data is written as a sub-part of each TBranch.

**Comment by jpivarski** [comment]
Thank you @pcanal !

I'm in the midst of working through this and can see why I had a blind spot. There were only two compressed blocks because the data I wanted was *inside* one of them. There's no way to predict what the byte pattern of 125.0 would be, since it's not only compressed, it's inside a larger compressed block with different contents than the separated-TBasket cases I've been looking at so far.

I'm working through the consequences of this now to get a better understanding.

**Comment by jpivarski** [comment]
Okay, it's done: you can now recover an incompletely written branch. It's an opt-in feature until I get more comfortable with it (test more example ROOT files, see that they work the same way— for example, the file from #14).

Usage is shown in this unit test: https://github.com/scikit-hep/uproot/blob/master/tests/test_issues.py#L42

Basically, when you first read a file, behavior is as before: no basket data as TKeyed objects means empty arrays. If you want to try to recover, you do `branch.recover()` for one branch or `tree.recover()` for all branches. Then embedded baskets will be included and you get non-empty arrays.

Expecting the user to know when they have one case or the other is asking a little too much, I know. If this is the correct thing to do in all cases, recovery will later be enabled by default and the explicit function will be deprecated. But for now, I just want to get more experience with it and not apply a possibly bad correction to all files.

**Comment by jpivarski** [comment]
I'm comfortable enough with the `recover()` function that it is now called automatically on affected branches: https://github.com/scikit-hep/uproot/releases/tag/2.6.1. This function had never been publicized, but now that it's redundant, it has been renamed to `_recover()` (and you'll probably never call it directly).
