### ISSUE TITLE
Inconsistency in branch names between Python2 and 3

### ISSUE THREAD

**Issue by HealthyPear** [scikit-hep/uproot#216]
**_uproot==3.3.4
uproot-methods==0.3.3_**

**Python 2.7.15**

```
for arrays in uproot.iterate("Zmumu.root", "events", ["px1"]):
    print(arrays)
```

returns

```
{'px1': array([-41.19528764,  35.11804977,  35.11804977, ...,  32.37749196,
        32.37749196,  32.48539387])}
```

so if I do,

```
for arrays in uproot.iterate("Zmumu.root", "events", ["px1"]):
    print(arrays["px1"])
```

I will get the values:

`[-41.19528764  35.11804977  35.11804977 ...  32.37749196  32.37749196, 32.48539387]`

**Python 3.7.0**

```
for arrays in uproot.iterate("Zmumu.root", "events", ["px1"]):
    print(arrays)
```

returns

`{b'px1': array([-41.19528764,  35.11804977,  35.11804977, ...,  32.37749196, 32.37749196,  32.48539387])}`

so the same way to extract the data will fail systematically with a Key error,

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-2b0e186326ee> in <module>()
      1 for arrays in uproot.iterate("Zmumu.root", "events", [var]):
----> 2     a = arrays["px1"]
      3

KeyError: 'px1'
```

**Comment by jpivarski** [comment]
Actually, this is not a bug— you'll encounter this in any code based on byte strings (character data without an encoding) between Pythons 2 and 3.

The names of branches in a ROOT file have no encoding, and so their Python equivalents are byte strings. (If we assume an encoding like "ASCII" or "UTF-8", deliberate use of the eighth bit could result in errors. Also, there are old ROOT files around, it's not even unlikely that someone's used French characters in a branch name encoded in "Latin-1" or something.)

Python 2 ignored the difference between byte strings and encoded strings, which is one of the major backward-incompatible issues they wanted to fix with Python 3. Python 3 makes a clear distinction between them. You'd have to access these dictionary keys as `b"px1"` because `"px1"` is a different thing.

I'm sure this can get annoying, so I included an opt-in parameter to turn the branch names into strings: `namedecode="utf-8"` lets you assume the encoding of branch names is "UTF-8". Since it's opt-in, you know better than me if there are "Latin-1" French characters to be worried about.

**Comment by HealthyPear** [comment]
Yes, I confirm that usign _namedecode="utf-8"_ works for both versions of Python.
