### ISSUE TITLE
highlight performance of uproot in README.md

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#219]
I remember seeing some presentations from Jim which demonstrated uproot's performance is on par (or was it even better?) with C++ ROOT IO. I suggest to put such a graph into the README, to fight the prejudice that any pure Python implementation must be much slower than something written in C++.

**Comment by jpivarski** [comment]
The main plot I touted last summer showed the memory use and time to process a jagged array in various frameworks. That one made an impression because of its log scales— PyROOT was some five orders of magnitude slower than the fastest methods. (Understandably: it does a lot of dynamic work in each step.)

This wouldn't be the appropriate plot for the uproot README because it's really about processing. uproot read time is on that plot for a fair comparison with ROOT— in its normal mode, ROOT reads and processes at the same time and can't be compared with awkward-array, which only processes.

I do have some older plots of just reading, as a function of basket size, so that you can see the string dependence. (For small baskets, you spend most of your time in pure Python, running around looking for basket boundaries, and you pay for Python's dynamism. For large baskets, you spend most of your time in Numpy doing pure math.) I think they used to be in the README— I can't remember why I removed them.

(Or maybe they were in a tutorial?)

Anyway, I'll see if I can find a place for them in the text, somewhere that doesn't get in the way of a user looking for how-to examples. (Based on bug reports and general questions, I don't think many people notice the readthedocs— most people get everything from this one long page.)

**Comment by HDembinski** [comment]
This is so cool, thank you!
