### ISSUE TITLE
namedecode for elements in branches

### ISSUE THREAD

**Issue by sdporzio** [scikit-hep/uproot#228]
Maybe not an issue, but I am still trying to figure out how to fix this.
`namedecode` option correctly decodes branch names but root branches with `std::vector<std::string>` are left as bytes strings.
E.g.

```

rTree = uproot.open(path)[tree]
df = rTree.pandas.df(flatten=False,namedecode='utf-8')
example = df['trigger_triggerName'].iloc[0]
print(example)
print(type(example[0]))

[b'swtrigger_BNB_FEMBeamTriggerAlgo', b'swtrigger_BNB_2017Dec_SWTrigger5PE_FEMBeamTriggerAlgo', b'swtrigger_BNB_HSN_c0_FEMBeamTriggerAlgo']
<class 'bytes'>

```

Should the `namedecode` option apply also to any string in the file?

P.S.: This is fixable in my case, with:
```
df[branchWithListOfStrings] = df[branchWithListOfStrings].apply(lambda strings: [s.decode('utf-8') for s in strings])
```
but I wonder whether it would be desirable to have uproot take care of that.

**Comment by jpivarski** [comment]
It's only supposed to decode names.

However, what you suggest would be a reasonable option to add to `asstrings`. If you look at `yourbranch.interpretation`, you'll see that it's `asstrings()` or `STLVector(asstrings())` or something. The default must always be bytes (because a bytestring with odd 8th bit characters would raise exceptions if we try to decode it with ascii or utf-8), but without too much work, a `decode` option could be added to `asstrings` that a user could manually apply as an Interpretation for their branch.

What do you think?

**Comment by sdporzio** [comment]
I see. Yes, that sounds like a good proposition!
For reference, in my case it's `STLString()` rather than `asstrings()`

```
rTree['trigger_triggerName'].interpretation
asgenobj(STLVector(STLString()))

```

**Comment by jpivarski** [comment]
I don't know when I'll get to it, but I can point you to what would change (in case you want to try it): the `STLString` class (https://github.com/scikit-hep/uproot/blob/master/uproot/interp/objects.py#L81) takes one optional argument. You can add another (`decode=None`) before the one that's there now, because string-decoding is more likely something you'd want to change than the choice of `awkward` library.

If a `STLString` carries this `decode` parameter, it can apply it to the string it returns on line 94 (https://github.com/scikit-hep/uproot/blob/master/uproot/interp/objects.py#L94). That's all there is to it (in a class of 11 lines)!

To use it, you'd just construct a `asgenobj(STLVector(STLString(decode="utf8")))` manually and pass it as the `interpretation` parameter of `array`, `arrays`, `iterate`, etc. If you're reading many arrays, this parameter takes a dict mapping branch name to interpretation.

**Comment by sdporzio** [comment]
Thanks for the suggestion! I'll try it out.
