### ISSUE TITLE
uproot raises `TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'` when root file doesn't have TTrees or TBranches

### ISSUE THREAD

**Issue by rklasen** [scikit-hep/uproot#234]
Hi,

I have a a root file [(uploaded to Dropbox)](https://www.dropbox.com/s/usc2nxxcbfiz22q/misalignMatrices-SensorsOnly-100.root?dl=0), that doesn't have a TTree or TBranches but instead contains a `std::map<TString, TGeoHMatrix>`. I wrote it in a C macro with this code:

```c
std::map<std::string, TGeoHMatrix> matrices;

[... fill the map here ...]

TFile *misalignmentMatrixRootfile = new TFile((misMatFileName).c_str(), "NEW");
	if (misalignmentMatrixRootfile->IsOpen()) {
		gDirectory->WriteObject(&matrices, "PndLmdMisalignMatrices");
		misalignmentMatrixRootfile->Write();
		misalignmentMatrixRootfile->Close();
	}
```

When I try to read this file with uproot, I cannot access the "PndLmdMisalignMatrices" key, instead I get a TypeError:

> TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

This is the code to read the root file:

```python
#!/usr/bin/env python3

import uproot, sys, os
import numpy as np

def readMatrices():
    matrixFile = uproot.open('./misalignMatrices-SensorsOnly-100.root')
    print(matrixFile.keys())
    matrices = matrixFile[b'PndLmdMisalignMatrices']
    print(matrices)

if __name__ == "__main__":
    readMatrices()
```

Am I reading the file a wrong way, or is this supposed to work like that? Thanks in advance!

**Comment by jpivarski** [comment]
Unfortunately, I won't be able to help you; I just gave you a better error message. The type you want to read is `std::map<std::string, TGeoHMatrix>` and I've never tried to deserialize STL collections of objects outside of a TTree or `std::map` at all (only `std::vector`). This can probably be fixed (raise a feature request issue), but not at the moment.

The incomprehensible error message came from the fact that while an unrecognized object like this would ordinarily give you a (fairly useless) `Undefined` object, it can't even do that because its byte count is not in the normal format—probably related to the fact that it's an STL collection of streamer-defined objects, rather than the streamer-defined object itself.

I added some code to detect that situation and write a proper error message, but that doesn't help you get to work. If you need this type, raise a feature request.

Note: if you can reformat your file, a directory full of `TGeoHMatrix` objects is very likely to work. I'm looking at its streamer structure and it's very simple. If you just needed a mapping from names to objects, a plain directory will do that.
