### ISSUE TITLE
`TNamed` attributes

### ISSUE THREAD

**Issue by l-althueser** [scikit-hep/uproot#236]
Hi,

I was always using the `fTitle` and `fName` attributes of the `TNamed` objects but they seem to deleted now. It is still possible to use `TNamed._fTitle` to get the title. To put it in code:
```
uproot.open(<file>)["<TNamed_key>"].fTitle
```
is not working anymore but
```
uproot.open(<file>)["<TNamed_key>"]._fTitle
```
is still ok.

**Comment by jpivarski** [comment]
That was intentional: the variables that we can automatically import into Python are C++ private members, so the appropriate idiom for that in Python is to start them with an underscore. If it's a `TTree` or a `TBranch`, the high-level `.title` should work, too. [uproot-methods](https://github.com/scikit-hep/uproot-methods) defines high-level methods for certain objects. (`title` is a `property` that exposes `_fTitle`.) If you want to customize acessors to your objects, you can add to uproot-methods.

But anyway, answer your question about the name change, this was one of the breaking changes from uproot 2 → uproot 3.
