### ISSUE TITLE
Some branches cause numpy broadcast errors

### ISSUE THREAD

**Issue by imandr** [scikit-hep/uproot#24]
With the NOvA CAF files, specifically, fardet_r00021429_s37_t00_R16-03-03-prod2reco.f_v1_data.caf.root, I get these errors:

can not get array for rec.spill.spill.intx: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.spill.inty: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.spill.bposx: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.spill.bposy: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.intx: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.inty: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.bposx: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)
can not get array for rec.spill.bposy: <type 'exceptions.ValueError'> could not broadcast input array from shape (2898) into shape (3501)

**Comment by imandr** [comment]
Here is the piece of code which causes this:

utree = uproot.open("/data/NOvA/fardet_r00021429_s37_t00_R16-03-03-prod2reco.f_v1_data.caf.root")
tree = utree["recTree"]
tree["sel.cvn.output"].array()

**Comment by jpivarski** [comment]
This was a serious bug: missing 10 bytes per event in the calculation of the number of items for `std::vector<numbers>`. It was hidden in small files with fewer than 3 baskets (because the first and last baskets get clipped to the right size, anyway). I'm glad Numpy complains about trying to assign the wrong sizes, rather than taking some default action. It serves as a useful check.

Now all arrays from that file (that currently have an interpretation) can be read out.

**Comment by imandr** [comment]
This may be related to the same bug because it seems to be happening for the same branches. The branch.fLeaves[0].fLeafCount is None for at least some of them:

x = tree["sel.cvn.output"]
a = x.array()
print x.fLeaves[0].fLeafCount

**Comment by jpivarski** [comment]
Have you tried uproot 2.3.3 (or later) and do you still see this bug? If so, reopen the issue. I'm under the impression that we don't get broadcast errors anymore. (At least, I don't, when I look at the same NOvA files.)

Many leaves will legitimately have no fLeafCount. For example, all std::vector<number> leaves have no fLeafCount because they're essentially rowwise serializations of the std::vector data, not columns with a separated count.

**Comment by imandr** [comment]
Yes, this is version 2.3.3

Here is the code:

print uproot.version.__version__
x = tree["sel.cvn.output"]
a = x.array()
print x.fLeaves[0].fLeafCount

and here is the output:

2.3.3
None

**Comment by jpivarski** [comment]
This output is correct. The "sel.cvn.output" branch is a `std::vector<float>`, which has no counter-leaf. `std:vector<numbers>` are not split into data and counter the way that branches like `"sel.cvn.output[sel.cvn_]"` are. For STL containers, the vector sizes are stored inline in the same branch as data, unlike counted branches.

**Comment by beojan** [comment]
I get the same `could not broadcast input array` error when I do 

```python
tree.arrays("Jet.*")
```

with a Delphes produced ROOT file.

**Comment by jpivarski** [comment]
This is not necessarily (not likely) related to the error reported nearly a year ago. **Please open a new issue**, and try to narrow down which branch is causing the error (or the first one; any one will do). If possible, could you send me an example of the file? Thanks!
