### ISSUE TITLE
Memory Usage with XRootD

### ISSUE THREAD

**Issue by zhenbinwu** [scikit-hep/uproot#247]
I noticed some continuously increasing in memory while reading via xrootd. The code snippet used for the testing as below.
```
it = uproot.iterate(lines, "Events", namedecode= 'utf8',  xrootdsource=dict(chunkbytes=80*1024, limitbytes=100*1024**2))
while True:
    try:
        tt = next(it)
    except StopIteration:
        print("End of the loop", sys.exc_info()[0])
        break
```

![test_nocache](https://user-images.githubusercontent.com/1052165/53995126-b3dab500-40f9-11e9-90de-210785753f04.png)

The memory increase much faster if I use cache:
```
# cache = uproot.cache.ArrayCache(1024**3)
# it = uproot.iterate(lines, "Events", namedecode= 'utf8',  cache=cache,  xrootdsource=dict(chunkbytes=80*1024, limitbytes=100*1024**2))
```

![test](https://user-images.githubusercontent.com/1052165/53995170-d967be80-40f9-11e9-813a-0bfe397f5d30.png)

**Comment by jpivarski** [comment]
The first one doesn't strike me as an obvious increase. You've asked for the XRootDSource cache to be limited at 100 MB and the process spends most of its time well above that, but I don't know how much of that is general Python memory use. Python decides when it will clear its garbage collector, which makes it very hard to judge what a measure of memory means.

The second one is obvious growth. If the first plot represents a quiescent state of Python memory usage (bouncing around a GB), the second plot speeds past it in half the time. It's exactly what I'd expect of using a dict as a cache—that is, never marking anything as available for the garbage collector to delete.

It's troubling because you tell the cache to use 1 GB as an upper limit. It's clearly not deleting anything. `ArrayCache` is a thin wrapper around `cachetools.LRUCache`, which should drop items when [its total getsizeof](https://github.com/scikit-hep/uproot/blob/master/uproot/cache.py#L37) exceeds the limit. I have `getsizeof` defined to be the Numpy array's `array.nbytes`.

Ah, crud! Not all of the arrays uproot returns are Numpy arrays! If they're JaggedArrays, they don't have a `nbytes` property. That's quite an oversight. I must have written this, thinking, "And now I will have to implement `nbytes` on all the awkward arrays." And then didn't.

Without an `nbytes` property, it defaults to `1`, which means that the cache is waiting for you to get a billion _arrays_, rather than a billion _bytes_.

I'm closing this issue and opening scikit-hep/awkward#92, because that's where it will be fixed.
