### ISSUE TITLE
JaggedArray method _broadcast has changed to public method tojagged

### ISSUE THREAD

**Issue by gregbarbour** [scikit-hep/uproot#250]
Hi,

I've run into the following error using the latest versions of uproot and awkward:

~\Anaconda3\lib\site-packages\uproot\_connect\to_pandas.py in futures2df(futures, outputtype, entrystart, entrystop, flatten, flatname, awkward)
    151             arrays.append(array)
    152 
--> 153         index = pandas.MultiIndex.from_arrays([index._broadcast(numpy.arange(entrystart, entrystop, dtype=numpy.int64)).content, index.content], names=["entry", "subentry"])
    154 
    155         df = outputtype(index=index)

AttributeError: 'JaggedArray' object has no attribute '_broadcast'

By the looks of things, the package awkard has changed the name of this method but the code hasn't changed in uproot:

https://github.com/scikit-hep/awkward-array/commit/c692546257d6bb984d3d3de7c4dcc2fc13f00ad8#diff-73e1845c17301820ef8803a3e92fa750

Best
Greg

**Comment by jpivarski** [comment]
Sorry about that. As an underscored method, it should not have been used outside of awkward itself. The fact that uproot used it was a mistake that I need to correct now.

The fast correction is to push a new version of awkward, and then the awkward versions 0.8.9 and 0.8.10 break uproot; version 0.8.11 will come out as soon as possible.

The long-term correction is to make a new semi-major version of awkward and set uproot to depend on that, using the new public method instead of private methods.

Again, mea culpa.

**Comment by jpivarski** [comment]
(If you hadn't told me, I would have noticed at exactly the same time because uproot continuous integration is failing! But thanks!)

**Comment by jpivarski** [comment]
awkward 0.8.11 is deployed, so (if pip picks up the right version; do `-U` and maybe `--no-cache` explicitly), the problems should be fixed. I'm still waiting on uproot's continuous integration for confirmation.

**Comment by gregbarbour** [comment]
Thanks very much!

On 11 Mar 2019 18:06, Jim Pivarski <notifications@github.com> wrote:

awkward 0.8.11 is deployed, so (if pip picks up the right version; do -U and maybe --no-cache explicitly), the problems should be fixed. I'm still waiting on uproot's continuous integration for confirmation.
