### ISSUE TITLE
Best way to produce awkward.Table from tree.arrays

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/uproot#252]
I'm wondering what is the best way to get `tree.arrays` to produce an `awkward.Table`?

The easiest option is to just do:
```python
data = tree.arrays(branches, outputtype=awkward.Table)
```
except that the columns names are `"0"`, `"1"`, etc, rather than the original branch names, which would be nice.

I can also do:
```python
data = tree.arrays(branches, outputtype=tuple)
data = awkward.Table({b: col for b, col in zip(branches, data)})
```
which gives me more meaningful names, but is obviously an extra step with an explicit for-loop.  

Is there an alternative to these that I've missed?

**Comment by jpivarski** [comment]
```python
data = tree.arrays(branches, outputtype=awkward.Table)
```

is a good idea; I hadn't thought of that and it could be enabled with a small adaptation.

I'm up to my elbows right now, but if you want this nice kind of access, there are five places in [uproot/tree.py](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py) that could be updated to support it.

Those five places match the search string `"issubclass(outputtype, dict)"` (I always use the same names and spacing): [here](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L475), [here](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L512), [here](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L577), [here](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L1697), and [here](https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L1762). Immediately after checking for `dict`, it would check for `awkward.Table`, and instead of returning `outputtype((?, ??) for ...)`, it would return `outputtype.frompairs((?, ??) for ...)`.

That would work equally well for subclasses of `awkward.Table`.

**Comment by jpivarski** [comment]
Oh! This might not be what you want: if some of the arrays you get out of the TTree are jagged, you would get a "table of jagged arrays," not a "jagged table." If the data are related; if they share cardinality-per-event, then you most likely want a jagged table.

Here's the difference:

```python
>>> import awkward
>>> a = awkward.fromiter([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
>>> b = awkward.fromiter([[100, 200, 300], [], [400, 500]])

>>> tablejagged = awkward.Table(a=a, b=b)
>>> jaggedtable = awkward.JaggedArray.zip(a=a, b=b)

>>> tablejagged.tolist()   # this is a flat array of rows, each of which contains a subarray
[{'a': [1.1, 2.2, 3.3], 'b': [100, 200, 300]}, {'a': [], 'b': []}, {'a': [4.4, 5.5], 'b': [400, 500]}]
>>> jaggedtable.tolist()   # this is a jagged array of rows
[[{'a': 1.1, 'b': 100}, {'a': 2.2, 'b': 200}, {'a': 3.3, 'b': 300}], [], [{'a': 4.4, 'b': 400}, {'a': 5.5, 'b': 500}]]
```

At the level of data types,

```
>>> import awkward.type
>>> # if you pass an integer, then 'a' or 'b', then an integer, you get a float
>>> print(awkward.type.fromarray(tablejagged))
[0, 3) -> 'a' -> [0, inf) -> float64
          'b' -> [0, inf) -> int64
>>> # if you pass an integer, then an integer, then 'a' or 'b', you get a float
>>> print(awkward.type.fromarray(jaggedtable))
[0, 3) -> [0, inf) -> 'a' -> float64
                      'b' -> int64
```

If you want a jagged table, here's how to get it:

```python
awkward.JaggedArray.zip(**tree.arrays("Muon_*"))
```

**Comment by benkrikler** [comment]
Hmm that's a good point!  I was thinking of building a table of jagged arrays (ie. no constraint on equivalent jaggedness), and assuming (though I'm not sure why) that if they all agreed, or were at least broadcastable, awkward.Table would make this a jagged table.  

Are jagged tables and tables of jagged arrays equivalent if all the jagged arrays in the latter have the same jagged-ness ?  

Similarly, what would happen if I use your last solution on a list of branches:
```python
awkward.JaggedArray.zip(**tree.arrays(branches))
```
where the branches had different jagged-ness (or perhaps in this instance I mean dimesions) but they can all be broadcast together?  Would the `zip` constructor take care of the broadcasting or complain?

I suspect your final suggestion there using `zip` will be fine for my current needs, these extra questions are more for my current understanding.

**Comment by jpivarski** [comment]
`JaggedArray.zip` should throw an error if they don't fit together. It's what I wish Python's `zip` would do: check that the lengths match. `JaggedArray.zip` has to check a lot more lengths, though.

**Comment by jpivarski** [comment]
I think this is done.
