### ISSUE TITLE
Reading TCanvases without streamer info

### ISSUE THREAD

**Issue by SimoneMender** [scikit-hep/uproot#260]
We have a root file here written by the MAGIC Mars software with the following structure

```
MStatusDisplay (MStatusArray, thin wrapper around TObjectArray)
  - ...
  - IntMeanPedEx (TCanvas)
    - pad 1 (TPad, canvas.GetPad(1))
         - IntMeanPedEx Mean (MH Camera, a wrapper around TH1)
    - ...
  - ...
```

Any chance for reading this data using uproot?

Example file here: 
[example_mars_file.zip](https://github.com/scikit-hep/uproot/files/2979412/example_mars_file.zip)

**Comment by jpivarski** [comment]
I was looking at this file today. The issue you encountered trying to read this object was a bug, and a rather simple one. It will be fixed in the next version (PR #262).

Beyond that, we can read the array, but not the objects in it:

```python
>>> import uproot
>>> f = uproot.open("issue260.root")
>>> print(f["MStatusDisplay"])'
[<TNamed b'' at 0x77bc282710b8>, <Undefined (failed to read 'TCanvas' version 8) at 0x77bc28271400>,
<Undefined at 0x77bc27a14278>, <Undefined at 0x77bc27a142e8>, <Undefined at 0x77bc27a14358>,
<Undefined at 0x77bc27a143c8>, <Undefined at 0x77bc27a14438>, <Undefined at 0x77bc27a144a8>,
<Undefined at 0x77bc27a14518>, <Undefined at 0x77bc27a14588>, <Undefined at 0x77bc27a145f8>,
<Undefined at 0x77bc27a14668>, <Undefined at 0x77bc27a146d8>, <Undefined at 0x77bc27a14748>,
<Undefined at 0x77bc27a147b8>, <Undefined at 0x77bc27a14828>, <Undefined at 0x77bc27a14898>,
<Undefined at 0x77bc27a14908>, <Undefined at 0x77bc27a14978>, <Undefined at 0x77bc27a149e8>,
<Undefined at 0x77bc27a14a58>, <Undefined at 0x77bc27a14ac8>, <Undefined at 0x77bc27a14b38>]
```

The first is a `TNamed` with title `b'/data/M1/OSA/Analysis/2019/02/27/sequence_M1_05080236.txt'`, the second is a TCanvas that can't be read due to missing features in uproot, and the others I don't know. Even the process of identifying what their types are didn't succeed.

If this contains mostly TCanvases or other graphics, I don't see how that would be very useful in Python without the C++ functions that draw them. I'm wondering what would be gained by going through the process of identifying why they couldn't be read and fixing those issues.

(Other than the goodness of doing things right, which is hard to do all the time...)

**Comment by MaxNoe** [comment]
There are histograms in those tcanvases. De would like to get to the data of the histograms.

**Comment by jpivarski** [comment]
Looking into it, the reason all of those class instances are Undefined is because the file has no streamer for TCanvas. Without streamers, I would have to write the "which byte means what field?" code by hand, accounting for different versions of the class. ([This is what I would have to convert to Python and maintain.](https://github.com/root-project/root/blob/ffbaa25ff1f523a814ae8482c453618d987e176c/graf2d/gpad/src/TCanvas.cxx#L2034-L2137))

I don't know why streamers are sometimes missing—the statement that ROOT files are self-describing relies on those streamers being present; without them, the meaning of the file depends on the C++ (or Python) code that interprets it. In some of these cases, the streamers are in the original ROOT file but missing in a file that was combined by hadd.

How important is it to read these via TCanvas, rather than some other list of histograms, like a TObjArray of TH1F?

**Comment by MaxNoe** [comment]
> How important is it to read these via TCanvas, rather than some other list of histograms, like a TObjArray of TH1F?

The way those files were created is out of our control.

**Comment by MaxNoe** [comment]
> Looking into it, the reason all of those class instances are Undefined is because the file has no streamer for TCanvas. 

How would that be changed? Is it an option somewhere for the TFile or how is it determined if thoses streamers are written or not?

**Comment by jpivarski** [comment]
I was at first going to say "no," because the streamers are supposed to be automatically added, but I did some digging.

First of all, you can check for the existence of a streamer in ROOT as `TFile::ShowStreamerInfo()` and uproot as `file.showstreamers()`. TCanvas isn't in there.

I found this: https://root.cern.ch/doc/master/classTStreamerInfo.html#a1a95df423cc1c955372c82c4e391d87e

```
TClass::GetClass("TCanvas")->GetStreamerInfo()->ForceWriteInfo(output, kTRUE);
```

made the difference between a file being written with TCanvas streamers and without.

So then I tried applying it to your file—just opening it in UPDATE mode, calling the above to force writing of TCanvas's streamer, and then `TFile::Write` and `TFile::Close`. Attempting to read it back in uproot led to an error that I tracked down to a line in TAttCanvas (a TCanvas dependency). Your TAttCanvas object has a different version than the TAttCanvas streamer that I put into the file. Well, that's to be expected: I wrote a _particular version_ of the canvas streamers into the file, which very likely differs from the particular version of the objects you wrote.

So at the least, we might be able to do it if you `ForceWriteInfo` the TCanvas streamer into your file in the same version of ROOT that was used to make the file. This sounds fragile and version-dependent, but that's exactly why streamers are supposed to be automatically written to ROOT files: the version dependence is supposed to be shipped with the file so that another version of ROOT (or uproot) can read it.

**Comment by MaxNoe** [comment]
Thanks for the feedback!



So, in root i did the following:

```
root [0] gSystem.Load("libmars.so")
(int)0
root [1] TFile* output = new TFile("ssignal05080236.001_M1.root", "UPDATE");
root [2] TClass::GetClass("TCanvas")->GetStreamerInfo()->ForceWriteInfo(output, kTRUE);
root [3] output->Write();
root [4] output->Close();
root [5] .q
```

And then I tried opening in uproot:

Which gives me

```
In [1]: import uproot

In [2]: f = uproot.open('ssignal05080236.001_M1.root')

In [3]: print(f['MStatusDisplay;1'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-a3dc7540616e> in <module>()
----> 1 print(f['MStatusDisplay;1'])

~/.local/lib/python3.6/site-packages/uproot/rootio.py in __getitem__(self, name)
    236 
    237     def __getitem__(self, name):
--> 238         return self.get(name)
    239 
    240     def __len__(self):

~/.local/lib/python3.6/site-packages/uproot/rootio.py in get(self, name, cycle)
    347                 if key._fName == name:
    348                     if cycle == key._fCycle:
--> 349                         return key.get()
    350                     elif cycle is None and last is None:
    351                         last = key

~/.local/lib/python3.6/site-packages/uproot/rootio.py in get(self, dismiss)
    914 
    915         try:
--> 916             return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
    917         finally:
    918             if dismiss:

~/.local/lib/python3.6/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent, asclass)
   1269             context = context.copy()
   1270         out = cls.__new__(cls)
-> 1271         out = cls._readinto(out, source, cursor, context, parent, asclass=asclass)
   1272         out._postprocess(source, cursor, context, parent)
   1273         return out

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent, asclass)

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent, asclass)
   1279         name = cursor.string(source)
   1280         size, low = cursor.fields(source, struct.Struct(">ii"))
-> 1281         self.extend([_readobjany(source, cursor, context, parent, asclass=asclass) for i in range(size)])
   1282         _endcheck(start, cursor, cnt)
   1283         return self

~/.local/lib/python3.6/site-packages/uproot/rootio.py in <listcomp>(.0)
   1279         name = cursor.string(source)
   1280         size, low = cursor.fields(source, struct.Struct(">ii"))
-> 1281         self.extend([_readobjany(source, cursor, context, parent, asclass=asclass) for i in range(size)])
   1282         _endcheck(start, cursor, cnt)
   1283         return self

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readobjany(source, cursor, context, parent, asclass)
    479 
    480         if asclass is None:
--> 481             obj = fct.read(source, cursor, context, parent)     # new object
    482             if isinstance(obj, Undefined):
    483                 obj._classname = cname

~/.local/lib/python3.6/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent)
    856             context = context.copy()
    857         out = cls.__new__(cls)
--> 858         out = cls._readinto(out, source, cursor, context, parent)
    859         out._postprocess(source, cursor, context, parent)
    860         return out

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent, asclass)

~/.local/lib/python3.6/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent)
    856             context = context.copy()
    857         out = cls.__new__(cls)
--> 858         out = cls._readinto(out, source, cursor, context, parent)
    859         out._postprocess(source, cursor, context, parent)
    860         return out

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent, asclass)

~/.local/lib/python3.6/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent, classname)
   1374             context = context.copy()
   1375         out = cls.__new__(cls)
-> 1376         out = cls._readinto(out, source, cursor, context, parent)
   1377         out._postprocess(source, cursor, context, parent)
   1378         out._classname = classname

~/.local/lib/python3.6/site-packages/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent)
   1384         start, cnt, self._classversion = _startcheck(source, cursor)
   1385         if cnt is None:
-> 1386             raise TypeError("cannot read objects of type {0} and cannot even skip over this one (returning Undefined) because its size is not known\n  in file: {1}".format("???" if self._classname is None else self._classname.decode("ascii"), context.sourcepath))
   1387 
   1388         cursor.skip(cnt - 6)

TypeError: cannot read objects of type ??? and cannot even skip over this one (returning Undefined) because its size is not known
  in file: ssignal05080236.001_M1.root
```

There are streamers for TCanvas and TPad in the file now:

```
StreamerInfo for class: TCanvas, version=8, checksum=0x80c291f4
  TPad            BASE            offset=  0 type= 0 A Graphics pad
  fCatt           TAttCanvas      offset=  0 type=62 Canvas attributes
```

Here is the updated file:
[mars_file_with_tcanvas_streamer.zip](https://github.com/scikit-hep/uproot/files/2993122/mars_file_with_tcanvas_streamer.zip)

**Comment by jpivarski** [comment]
This is the same thing I tried on my own, with the same result. (Same error message, but when I use Python, not iPython, it gives me more information, that the error occurred in the generated code for TAttCanvas.) Without knowing the ROOT version number that created the TCanvas, I couldn't be sure that the TCanvas streamer I added is exactly the same as the TCanvas objects in the file.

For that matter, I can't be sure of it from your description, either, unless you independently verified that. The place where this fails is where it compares the TAttCanvas object version against the TAttCanvas class-streamer version, sees that it doesn't have a compatible match, and then goes into the "Undefined" code—which wouldn't help you because it's simply trying to skip the object and give you a placeholder—and finds that it can't get the number of bytes it would need to skip.

If you're sure that you have the same ROOT version, do you want to keep pursuing this? I don't know how many issues away from the solution we are—if it's just a matter of getting that version number right or if it's a long chain of fixes for complex graphical object types.

If you have the capability in your workflow to add a streamer to the file, do you also have the capability to copy the histograms to some TObjArray? (In UPDATE mode, just like adding the streamer?) ROOT does some referencing, so it might only "simlink" the histograms. If this kind of intervention—either copying the histograms or adding the streamers—would defeat the purpose of using uproot, maybe it's time to use PyROOT for this part of your workflow.

**Comment by MaxNoe** [comment]
> would defeat the purpose of using uproot, maybe it's time to use PyROOT for this part of your workflow.

I agree. Sadly, I think this will be the way to go. Would have been nice to just get it with uproot.

> Without knowing the ROOT version number that created the TCanvas, I couldn't be sure that the TCanvas streamer I added is exactly the same as the TCanvas objects in the file.

Should be 5.36 something, I used the latest 5.36 branch on gihub to write the streamer info, might have been wrong.

**Comment by jpivarski** [comment]
Oh, that's also a very old version. There might have been additional difficulties crossing the ROOT 5 → 6 border that I didn't think of.

Sorry that this didn't work out.
