### ISSUE TITLE
Jagged array elements without fLeafCount

### ISSUE THREAD

**Issue by imandr** [scikit-hep/uproot#27]
There are some elements, interpreted as jagged array, for which LeafCount can not be found, for example:

```
import uproot
print uproot.version.__version__

utree = uproot.open("/data/NOvA/fardet_r00021429_s37_t00_R16-03-03-prod2reco.f_v1_data.caf.root")
tree = utree["recTree"]

x = tree["sel.cvn.output"]
a = x.array()
print type(a)
print x.fLeaves[0].fLeafCount

```

Output:

```
2.3.3
<class 'uproot.interp.jagged.JaggedArray'>
None

```

**Comment by jpivarski** [comment]
Thanks for opening a new issue for this (since it is a different topic than #24). However, this is correct behavior. Branches that have `fLeafCount` are interpreted as jagged arrays and `std::vector<float>`, which do not have `fLeafCount` (because they really don't have any counter-leaf) are also interpreted as jagged arrays. It's not a bijection.

**Comment by imandr** [comment]
I thought you recommended to use fLeafCount to assign parents for jagged array elements. So what do I assign to be the parent of such jagged array ?

**Comment by jpivarski** [comment]
This type doesn't have a parent, even in C++ (except possibly flat structs, which is arbitrary structure that can be changed at will with metadata). To get a `std::vector<float>`, the author of this dataset had to manually split the contents— this is not something that was automatically split by ROOT.

Its counts are in its `.stops` array, and no other branch is guaranteed to have the same stops.

Like, maybe three `std::vector<floats>` representing `px`, `py`, and `pz` are always in lock step and always have the same number of elements per event, but we only know that because of domain specific knowledge or a familiarity with how the dataset was made. When the author of this dataset explicitly created each variable as a separate `std::vector<float>`, they broke any necessary connection between them. In principle, they could all have different sizes.

Thus, they should not be assigned the same parent. The author of the dataset went out of their way to make that impossible.
