### ISSUE TITLE
memmap caching of uproot arrays

### ISSUE THREAD

**Issue by jpata** [scikit-hep/uproot#276]
I've seen that ROOT file decompression can dominate the runtime of uproot/awkward workflows. Caching the arrays in python memmap files can lift uproot/awkward runtimes from ~50 kHz to ~1 MHz [attached image]. As I discovered that uproot already supports caching for xrootd, I was wondering if and how memmap caching of arrays would fit into the core uproot library or an extension (being mindful of feature creep).

What I'm doing now is something like: `tree.arrays(["Jet_pt", "Jet_eta"], cache=True)` which creates an uncompressed memmapped cache in a predetermined location, but I'm sure you would have better ideas how to structure the possible API.

On the attached picture, the gap between the black and dashed red histograms illustrates the time spent on ROOT file decompression.
![Screenshot 2019-05-10 at 13 03 55](https://user-images.githubusercontent.com/69717/57553681-1af82e00-7324-11e9-8c80-1e5bd9f71ba7.png)

I appreciate your thoughts!

**Comment by jpivarski** [comment]
I don't know what `cache=True` means, but maybe it was `c = {}` and then `cache=c`?

Otherwise, the cache keyword argument is definitely the right thing to be looking into. The question is just what kind of dict-like object to use as the `c`. If these things are large enough that they have to live on disk, then you might want to consider the [diskcache](http://www.grantjenks.com/docs/diskcache/tutorial.html) library. I was just talking with @nsmith- about it (maybe you heard us through the microphone in the meeting).

The diskcache library uses pickle to store the values in its key-value store, but presents a dict-like interface and should be compatible with uproot's `cache` keyword. Numpy arrays and awkward arrays both overload the default pickle behavior to do something reasonable, though it's an open question whether that's as good as the memmapping examples you're comparing against now. The diskcache library also has a [diskcache.Disk](http://www.grantjenks.com/docs/diskcache/tutorial.html#disk) interface for overriding the default serialization.

awkward-array has a zipfile-based serialization (like Numpy's NPZ files) that should be almost like memmapping raw data when no compression is used. The functions are named `awkward.save` and `awkward.load`. The saving step is configurable with compression policies: the default policy is to only compress integers (since it's much less helpful for floats). I think it also saves JaggedArrays via compressed counts, rather than separate starts and stops.

There's also a wrapper for h5py: `awkward.hdf5(put-h5py-group-here)` and an interface to Parquet: `awkward.toparquet`/`awkward.fromparquet`.

The nice thing about pointing uproot's cache keyword argument at a diskcache object is that it's a minimal change from naive code that reads from ROOT files every time. That way, the caching logic doesn't have to be managed manually.

**Comment by jpata** [comment]
Thanks for the thorough explanation! `cache=True` was meant to be pseudocode, I understand now that uproot expects a dict interface. Given the description, it seems as long as I implement a dict-like interface to disk-based memmapped arrays, uproot can already make use of that. I will try that.
Please feel free to either close or archive/tag the issue as you see fit.

**Comment by jpivarski** [comment]
You might want to look at uproot 2's diskcache: https://github.com/scikit-hep/uproot/blob/version-2.x/uproot/cache/diskcache.py

I removed it in uproot 3 because of separation of concerns (uproot should not do caching; I use the external cachetools library for that) and the disk-based cache was susceptible to cross-platform errors (even some Python standard library imports fail on Windows; it's when I started using AppVeyor).

I remember now that it uses a rather clever directory-filling algorithm that should be atomic, relying on the fact that filesystem operations are atomic. Unlike the diskcache library I pointed you to (in which you'd have to override the default pickle behavior), this one is made for arrays with a memmap interface. Actually, this algorithm was ported over from _several_ previous projects, cleaning it up more each time, but I eventually decided that even uproot isn't a good home for it. It could be a very good start for your project.
