### ISSUE TITLE
index dtype error in compact

### ISSUE THREAD

**Issue by jpata** [scikit-hep/uproot#277]
On compacting a masked JaggedArray of floats, I'm getting a dtype error from core uproot.
I've been trying unsuccessfully to create a minimal reproducible version, so I'm posting here what I currently observe, perhaps you already have insights or suggestions on what could be going wrong:

~~~
  File "/nfshome/jpata/gpu-analysis/hepaccelerate/utils.py", line 189, in compact_struct
    ja_reduced = ja[mask].compact()
  File "/usr/local/lib/python3.6/dist-packages/awkward/array/jagged.py", line 1315, in compact
    out = tmp._tojagged(offsets[:-1], offsets[1:], copy=False)
  File "/usr/local/lib/python3.6/dist-packages/awkward/array/jagged.py", line 840, in _tojagged
    index += increase
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint64') with casting rule 'same_kind'
~~~

Going in with PDB:
~~~
-> ja_reduced = ja[mask].compact()
  /usr/local/lib/python3.6/dist-packages/awkward/array/jagged.py(1315)compact()
-> out = tmp._tojagged(offsets[:-1], offsets[1:], copy=False)
> /usr/local/lib/python3.6/dist-packages/awkward/array/jagged.py(840)_tojagged()
-> index += increase

(Pdb) index
array([     31,      31,      72, ..., 2235098, 2235108, 2235108],
      dtype=uint64)
(Pdb) increase
array([0, 1, 0, ..., 1, 0, 1])
(Pdb) increase.dtype
dtype('int64')

(Pdb) up
(Pdb) tmp
<JaggedArray [[48.76737594604492 41.7457389831543] [30.168916702270508 30.107635498046875] [40.9498405456543 31.542665481567383] ... [46.60263442993164 42.470794677734375] [53.8294792175293 34.471214294433594] [93.6303482055664 22.601713180541992]] at 0x7f54a6a5b940>
(Pdb) offsets
array([     0,      2,      4, ..., 112586, 112588, 112590])

(Pdb) up
(Pdb) ja
<JaggedArray [[13.416550636291504] [26.130809783935547] [3.865323066711426] ... [32.84395980834961] [31.43795394897461] [25.133100509643555]] at 0x7f549f45ada0>
(Pdb) mask
array([False, False, False, ..., False, False, False])
~~~

**Comment by jpivarski** [comment]
This seems to be purely an awkward-array error, so if the conversation is long, we should perhaps take it over there.

However, I see that the two types that are being compared are `uint64` and `float64`, neither of which is the `INDEXTYPE`, signed `int64`, that awkward-array defaults to. Did you change that? The reason that we use signed index types is because sometimes we need to subtract them. In those cases, we know that the indexes won't become negative, but Numpy doesn't know that, and to be safe it turns `uint64` into the next larger type, `float64`. But `float64` can't be used as an index. The extra factor of 2 of dynamic range isn't worth all the corrections that would be needed to reverse that, so we use signed `int64` for all indexes (except those that come from ROOT or Arrow, which are `int32`).

**Comment by jpata** [comment]
I'm sorry, this is my mistake in getting uproot and awkward mixed up, it should be moved there.

I feel like some index type is not correctly propagated and , I did not change it myself (stock awkward). I'm creating a JaggedArray like this: `ja = awkward.JaggedArray.fromoffsets(offsets, flat_array)`. Numpy is then getting confused on  adding `index::uint64` and `increase::int64`. Closing here, will open in awkward.
