### ISSUE TITLE
Select entrysteps base on Cache size

### ISSUE THREAD

**Issue by zhenbinwu** [scikit-hep/uproot#285]
I am using the uproot iterate for reading Filelist via xrootd as below.

```
self.cache = uproot.cache.ArrayCache(200 *1024**2)
self.it = uproot.iterate(lines, treename, branches=branches,
                                 cache=self.cache,  namedecode=decode,
                                 entrysteps=entrysteps, reportpath=True,
                                 reportfile=True, reportentries=True,
                                 xrootdsource=dict(chunkbytes=80*1024, limitbytes=100*1024**2))
```

There are several ways for the iterating. By default, uproot can auto select entrysteps by syncing each basket. However, this could results in large memory for samples with large event size, which eventually leads to memory exceeding the memory limit when running on LPC condor job and jobs got killed.

To prevent the crash above, I added the cache with 200Mb. But it seems not working as I hope from https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L606
The current iterative is base on start and stop. So I have to fine tune the entrysteps to a small value for all jobs (different MC processes). 

Hopefully in the future, uproot can adjust the entrysteps base on the cache size, for condor jobs etc with fixed memory.

**Comment by jpivarski** [comment]
Actually, if you're interested in, I don't see why you have a high-level **cache** at all. (A **basketcache** is useful for that case because it keeps the old half baskets from being lost when you go into the next step of iteration and are using the next half of those baskets, but if you don't specify a **basketcache** in `iterate`, when is created for you.)

The purpose of a high level **cache** is to hold onto arrays that you're going to use again before they would get evicted from that cache. If you're interesting, then by definition each chunk is to fill up memory and therefore the last one should you go away. By caching them, you prevent the previous iteration from going away. You might find that removing the cache solves your memory problem.

The other issue is that fixed number of entries produces the wrong sizes for your Monte Carlo samples—some event sizes are large and some are small, so no single number of entries fits all. By default, if you don't specify a **entrysteps**, it will use the basket/cluster size. For well-designed data files, this is optimal, but there are a lot of non-optimal basket sizes in the wild. The **entrysteps** parameter can take a list of start/stop pairs, but it would be awfully nice if there were a way to select that parameter automatically based on the number of bytes in the baskets.

That _would_ be possible, at least approximately. We don't know the byte size of every entry, but we do know the byte size of every basket and the number of entries in each basket, so an optimal list of start/stop pairs can be automatically derived.

That will need to be a new method on TTree and TBasket, which can be passed as the **entrysteps** parameter, just as `TTree.clusters()` is automatically passed when **entrysteps=None**.

So I take this issue to be a request for that function.

**Comment by jpivarski** [comment]
`tbranch.basket_numentries(i)` and `tbranch.basket_numbytes(i)` for `i` in `range(tbranch.numbaskets)`

The function can be designed to produce entry start/stops that come as close as possible to a target `numbytes` in each step (possibly above, possibly below—can't guarantee below) for all branches in a set of branches under the constraint that all branches have to start and stop on the same entry number.

**Comment by jpivarski** [comment]
It would be even cooler if we could find some token that can be used to select this case, similar to the way that `None` selects `tree.clusters(relevant_branches)`.

Something like `entrysteps="3 GB"`, but I don't like the string parsing. Maybe `entrysteps={"GB": 3}`.

Any suggestions? (@henryiii?)

**Comment by zhenbinwu** [comment]
Thanks @jpivarski ! OK, I impose a wanted functionality to cache. 

Yeah, I think this is a very useful feature of uproot for running on batch system.

**Comment by jpivarski** [comment]
The implementation, as described above, doesn't have anything to do with the cache, and you shouldn't be using cache with the `iterate` function. (I'm working on a new front-page tutorial and I'm addressing that point there, since caching is subtle.)

The latest PR (#287) implements this and a few other odds and ends, mostly inspired by the fact that I'm writing documentation. That always forces me to noticed little things that need fixing.

There's a new `tree.mempartitions` method that returns a list of `(start, stop)` pairs like `tree.clusters` (which is used when `entrysteps=None`). There's an `entrysteps`-based shortcut for `mempartitions`: a string with memory-size units. So now you can say

```python
for data in uproot.iterate("files*.root", "treepath", entrysteps="1 GB")
```

and the `data` dict-of-arrays will be as close as possible to 1 GB. There's no guarantee that the dict-of-arrays will be _smaller_ than 1 GB, just close to it. The approximation is linear over the whole file (well, everything between `entrystart` and `entrystop`), so a file with big events at the beginning and small events at the end would systematically miss the mark. In principle, the approximation could get finer by taking advantage of the fact that we know the number of bytes and number of entries in each basket, not just the whole file, but I've left that as a `NotImplementedError` if you try to set `linear=False` in `mempartitions`.

The number of entries depends on the set of branches you select because they'll all be loaded into memory: when it targets 1 GB, it tries to get all selected branches near 1 GB.

Also, a few other interfaces that take a number of bytes integer can now optionally take a memory size string with the same format. Prefixes up to yoctobytes are supported. (kB, MB, GB, TB, PB, EB, ZB, YB :)

**Comment by jpivarski** [comment]
This will be in uproot 3.6.3, which might take about half an hour to send to PyPI.
