### ISSUE TITLE
processing list of files via `uproot.iterate` with `executor` - no speedup?

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/uproot#289]
I have a list of files that I would like to process as fast as possible. For this I run this code

```
import uproot
import glob
fname = glob.glob('../exported/data16/*.root')
treename = 'data16'


import concurrent.futures
executor = concurrent.futures.ThreadPoolExecutor(max_workers=5) 

gen = uproot.iterate(
        fname,
        branches = ['n_jet'],
        treepath = treename,
        namedecode="utf-8",
        executor = executor
)

for g in gen:
    print(len(g['n_jet']))
```

but I fail to see a speedup as a function of the workers in the `ThreadPool`. Am I misunderstanding *what* is being parallelized. Does the speed-up only happen for multiple variables / arrays? Could it be extended to process multiple files in parallel?

**Comment by jpivarski** [comment]
It parallelizes the reading and decompression of all baskets (for all branches) in one step of iteration. But it's still a Python for loop: iteration `n` has to complete before iteration `n+1`. So if you're reading 3 baskets each of 5 branches in each step of the loop, it would work on those 15 baskets in parallel (as 15 tasks for however many workers you have in the thread pool), blocking until they're all done reading, then enter the body of your for loop until that finishes, then start reading the next 15 baskets the same way.

I've revamped the introductory tutorial—the [section on parallelization](https://github.com/scikit-hep/uproot#parallel-array-reading) is now last because it's not often useful. For it to provide a speedup, the reading/decompression steps _outside of Python_ have to be dominating the work because it (a) doesn't parallelize anything but the reading and decompression and (b) the Python steps are hindered by the GIL—only calls to externals like `lzma.decompress` truly run in parallel. I've described that in the section.

You do have some handles to loosen this, if non-Python reading/decompressing is really the limiting factor. You can set `blocking=False` so that an iteration step does not wait until reading is done before handing you control. However, the `g` in each step is no longer a dict of arrays but a zero-argument function returning a dict of arrays. Evaluating that function blocks until the reading is done. That lets you do other work while it's reading.

You can then set up an iterator that does the `n` step of your work while the `n+1` step is being read. Or if you have more memory, you can set it up so that several steps are in flight, all by doing non-blocking `next` calls on the iterator before starting the `n` step of your work. With `uproot.iterate`, a "step" can only be as large as a file, so this would be the only way to use it to read multiple files at once.

As an alternative, maybe you'd want to use Dask. Without creating any `ThreadPoolExecutor`, you can ask for `uproot.daskarray("files*.root", "treename", "branchname")` and work with the Dask arrays (maybe [adding a cache](https://github.com/scikit-hep/uproot#lazy-arrays-with-caching) to control memory usage). Dask arrays can't be jagged, and only provide a speed-up if the DAG of your work is not too complicated (see [this demo](https://nbviewer.jupyter.org/github/jpivarski/2019-06-10-usatlas-argonne-python/blob/master/misc-fractal.ipynb), which shows how to simplify the DAG with `numba.vectorize` to get a speedup).

It's also likely that you'll get a better speedup by completely parallelizing your reading + analysis as processes. @nsmith- has had a lot of success with Numpy's multiprocessing module. Each process independently reads and does work without significant communication with each other.

**Comment by nsmith-** [comment]
Small correction: `multiprocessing` is a python core library.
And yeah, with appropriate setup, one can use multi-core pretty effectively.  See muonspectrum_v3 and up in https://github.com/CoffeaTeam/coffea

**Comment by ramankhurana** [comment]
@nsmith- I have been using multiprocessing in uproot3 and works fine, while porting code to uproot 4 i am facing strange situation that setup works without multiprocessing, and does not work with uproot 4 [only when introduced multiprocessing]. I wonder if you are doing it in uproot 4 and have a setup to use it?

**Comment by nsmith-** [comment]
Coffea [futures executor](https://coffeateam.github.io/coffea/api/coffea.processor.FuturesExecutor.html) uses multiprocessing and uproot4 since some time
