### ISSUE TITLE
Error with Lazy arrays with caching

### ISSUE THREAD

**Issue by zhenbinwu** [scikit-hep/uproot#296]
I am trying  to use lazy array for reading. Below is my testing code
```
bg_files = "/uscms_data/d2/lpctrig/benwu/AutoEncoderSample/Phaes2L1Ntuple/NeutrinoGun_E_10GeV_V7_5_2_MERGED.root"
nocache_data = uproot.lazyarrays(bg_files, "l1PhaseIITree/L1PhaseIITree", PhysicsObt.keys(), entrysteps=100)
print(nocache_data[1]["jetEt"])
cache = uproot.cache.ArrayCache(1024**2)
data = uproot.lazyarrays(bg_files, "l1PhaseIITree/L1PhaseIITree", PhysicsObt.keys(), entrysteps=100, cache=cache)
print(data[1]["jetEt"])
```

It seems the first reading without cache is working fine. But the second test with cache is giving me error as below. I think I am following the [example](https://github.com/scikit-hep/uproot#lazy-arrays-with-caching). 

```

[139.000001 123.500001 108.500001 100.000001  98.500001  97.500001
  94.500001  90.000001  88.000001  87.500001  83.500001  82.500001]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-4a637b7bbea9> in <module>
      4 cache = uproot.cache.ArrayCache(1024**2)
      5 data = uproot.lazyarrays(bg_files, "l1PhaseIITree/L1PhaseIITree", PhysicsObt.keys(), entrysteps=100, cache=cache)
----> 6 print(data[1]["jetEt"])

~/.local/lib/python3.6/site-packages/awkward/array/table.py in __getitem__(self, where)
     70             if isinstance(where, awkward.util.string):
     71                 try:
---> 72                     return self._table._contents[where][self._index]
     73                 except KeyError:
     74                     raise ValueError("no column named {0}".format(repr(where)))

~/.local/lib/python3.6/site-packages/awkward/array/chunked.py in __getitem__(self, where)
    310         if self._util_isinteger(head):
    311             chunk, localhead = self.global2local(head)
--> 312             return chunk[(localhead,) + tail]
    313 
    314         elif isinstance(head, slice):

~/.local/lib/python3.6/site-packages/awkward/array/virtual.py in __getitem__(self, where)
    349 
    350     def __getitem__(self, where):
--> 351         return self.array[where]
    352 
    353     def __setitem__(self, where, what):

~/.local/lib/python3.6/site-packages/awkward/array/virtual.py in array(self)
    275         if self._array is None:
    276             # states (1) and (3)
--> 277             return self.materialize()
    278 
    279         elif self._cache is None:

~/.local/lib/python3.6/site-packages/awkward/array/virtual.py in materialize(self)
    326             # states (3) and (4)
    327             self._array = self.key
--> 328             self._cache[self._array] = array
    329 
    330         return array

~/.local/lib/python3.6/site-packages/uproot/cache.py in __setitem__(self, where, what)
     36 
     37     def __setitem__(self, where, what):
---> 38         self._cache[where] = what
     39 
     40     def __delitem__(self, where):

~/.local/lib/python3.6/site-packages/cachetools/lru.py in __setitem__(self, key, value, cache_setitem)
     19 
     20     def __setitem__(self, key, value, cache_setitem=Cache.__setitem__):
---> 21         cache_setitem(self, key, value)
     22         self.__update(key)
     23 

~/.local/lib/python3.6/site-packages/cachetools/cache.py in __setitem__(self, key, value)
     47         size = self.getsizeof(value)
     48         if size > maxsize:
---> 49             raise ValueError('value too large')
     50         if key not in self.__data or self.__size[key] < size:
     51             while self.__currsize + size > maxsize:

ValueError: value too large

```

Another naive question, is Lazy array most suitable for random accessing in root file from uproot?

**Comment by jpivarski** [comment]
The error message is saying that at least one of the chunks is larger than the whole cache—the cache can't hold that one item, let alone any others. You've allocated a 1 MB cache (`1024**2`), a size that was possibly used in one of the tutorials in order to demonstrate the effect of limited cache. As a result of #285, you can now specify memory sizes as a string: `"1 MB"`, or more likely, `"1 GB"`.

I think you asked @nsmith- earlier today about whether lazy arrays are a good idea for random access. Random access is generally slower than sequential access for any system with caching—even a plain C array is slower to access randomly than sequentially because chunks of it get cached in the CPU's L1/L2/L3 caches. Sequentially, you find all but the first item of a chunk when you look for it in cache; randomly, you have to load a new chunk on nearly every request, and loading a chunk is much slower than finding what you need in cache. Lazy arrays, which are `ChunkedArrays` of `VirtualArrays` do the same thing at a larger scale, where the "slow chunk-loading" is not copying from RAM into the CPU but reading from disk into your `ArrayCache` (and then from RAM into CPU).

If it's at all possible to load everything in memory at once, by supplying no cache or `cache=None`, then do so. You'll definitely get better results if your random-lookup function is in RAM, rather than on disk.

Although `chunkedarray[indexes]` for an integer `indexes` array is vectorized—the number of Python instructions scale with the number of chunks, not the number of entries/events—that still might not be satisfactory if you have many chunks due to many files. (If you have only one file, set `chunksize=numpy.inf` to load it all into one chunk to minimize the number of Python instructions.) If your data are logically a jagged array, i.e. a `ChunkedArray` of `VirtualArray` of `JaggedArray`, then you can concatenate all of the chunks with

```python
awkward.JaggedArray.concatenate(lazyarray.chunks)
```

If it's logically flat, i.e. a `ChunkedArray` of `VirtualArray` of plain old Numpy arrays, then you can concatenate all of the chunks with

```python
numpy.concatenate(lazyarray.chunks)
```

I hope to unify these sorts of things so that I can provide only one recipe in the future (`awkward.concatenate`), but this is where things stand right now.
