### ISSUE TITLE
Add `.array` to `TMatrix`

### ISSUE THREAD

**Issue by MaxNoe** [scikit-hep/uproot#302]
Right now, this is a bit tediuous:

```
import uproot

f = uproot.open('truee_data_result.root')
m = f['RealDataResults']['Tcovar_matrix_bins_11_knots_20_degFree_14']
print(type(m))
array = m._fElements.reshape(m._fNrows, m._fNcols)
```

m is
```
<class 'uproot.rootio.TMatrixT_3c_double_3e_'>
```

[truee_data_result.root.zip](https://github.com/scikit-hep/uproot/files/3355226/truee_data_result.root.zip)

**Comment by jpivarski** [comment]
Okay, there's a path for adding things like this: in uproot-methods (we should probably move the conversation there), there's a directory full of "methods" classes:

    https://github.com/scikit-hep/uproot-methods/tree/master/uproot_methods/classes

Each submodule has the name of a ROOT class (`TMatrixT_3c_double_3e_` in this case) and contains a class named `Methods`. When uproot reads such a class from a ROOT file (creating the `uproot.rootio.TMatrixT_3c_double_3e_` on the fly), it adds `Methods` as a superclass.

These superclasses are "mix-ins," meaning that they can define functions of the internal state, such as

```python
class Methods(uproot_methods.base.ROOTMethods):
    def array(self):
        return self._fElements.reshape(self._fNrows, self._fNcols)
```

The only thing that I can foresee going wrong is that the `hasmethods` lookup in [uproot-methods/classes/__init__.py](https://github.com/scikit-hep/uproot-methods/blob/master/uproot_methods/classes/__init__.py) might try to use the ROOT name of the class (`TMatrixT<double>`) rather than the Python name of the class (`TMatrixT_3c_double_3e`). This is the first class we're trying to add methods to that has such a distinction—so far, nothing else has needed special characters like `<` `>`. However, I'm looking in [uproot/rootio.py](https://github.com/scikit-hep/uproot/blob/358dfa5871a9fb2252ed01942dc75e3c4ea2ce3e/uproot/rootio.py) where `hasmethods` gets called, and I see it being called with `pyclassname` everywhere—it should be okay.

**Comment by jpivarski** [comment]
If you're interested in this, post on uproot-methods. Thanks!
