### ISSUE TITLE
Get tree/branch size on disk

### ISSUE THREAD

**Issue by mverzett** [scikit-hep/uproot#309]
Hi,

is there a way with uproot to get the size a TTree occupies on disk, as well as the size of the single branches?

Thanks!

**Comment by jpivarski** [comment]
There are two things you might mean by that: there's the TTree as an object in itself and there's the physics data it contains in its branches.

The TTree as an object in itself is generally small, only taking up as much data as necessary to describe the names and types of the branches, and any other metadata that might be hanging off of it. A total number of bytes for this object exists in the ROOT file and I use it to double-check that the TTree was read correctly, but I never thought to save it. On [this line](https://github.com/scikit-hep/uproot/blob/master/uproot/rootio.py#L798), I could have saved `cnt` (the number of bytes) as an internal attribute of the instance, but I didn't.

The physics data in the branches, however, would not be included in that count, and it's much larger and likely what you really want to know. Each [branch](https://uproot.readthedocs.io/en/latest/ttree-handling.html#branch-information) has an `uncompressedbytes` and a `compressedbytes`, which is the number of bytes (before and after compression). To get all of the branches, you can write a loop over `ttree.allvalues()` like

```python
sum(x.uncompressedbytes() for x in tree.allvalues())
```

Let me know if that answers your question.

**Comment by mverzett** [comment]
Indeed that's what I was looking for! I just see some small, but not negligible difference with respect to what `ROOT::TTree::Print()` provides, is this expected?

**Comment by jpivarski** [comment]
It could be, depending on what they're counting. If `ROOT::TTree::Print()`'s output is about 80 bytes per basket (`branch.numbaskets`) larger, then they're probably counting the TKey header on each basket. I'm not.

(I hadn't thought about making my counts of the basket sizes conform to `ROOT::TTree::Print()`. I use them internally to determine the size of the arrays to allocate and decided to make them public functions because it's in-principle useful information. Since the arrays don't contain any TKey headers, they're not included in the number of bytes.)

((There's yet more subtlety: any variable-width data contains (32-bit) integer offsets for each entry, and these data are stored in the same baskets with the contents (irrespective of the fact that they're often also stored in a counts variable, like `nMuon` for `Muon_pt[nMuon]`). The number of uncompressed bytes quoted by uproot includes content, offsets, and 8 more bytes due to a couple of 32-bit integers used as boundaries between the content and offsets. With the exception of that extra 8 bytes per basket, the numbers returned by uproot are purely for the physics data, not any metadata.))

**Comment by mverzett** [comment]
OK, thanks for the explanation.
