### ISSUE TITLE
Problem Opening TH1F in TTree

### ISSUE THREAD

**Issue by lukepolson** [scikit-hep/uproot#310]
I am having an issue opening a TTree which has histograms as its entries. The file I am looking at is included below.

[example.zip](https://github.com/scikit-hep/uproot/files/3480561/example.zip)

When I run 
`file = uproot.open('LArPhysWave_350000_FCAL.root')`
`tree = file['PulseShapes']`
`tree.array('pulse_shapes', entrystop=2)`

 <ObjectArray [<Undefined (failed to read 'TH1F' version 7) at 0x7f3744c2d278> <Undefined (failed to read 'TH1F' version 7) at 0x7f3744c2d208>] at 0x7f3744c2d7f0>

Since I have a feeling this is related to https://github.com/scikit-hep/uproot/issues/260, I suspect that `file.showstreamers()` might provide some clarity. I have checked this myself and see that TH1 and TH1F both seem to be included.

**Comment by lukepolson** [comment]
Thought I would add some further clarification. Actually the TH1F is included in the steamers but it is only version 2: 

![image](https://user-images.githubusercontent.com/39573086/62756478-cc465700-ba2c-11e9-82f5-eb42f2112836.png)

I wonder why UPROOT wants to read these as version 7...

**Comment by jpivarski** [comment]
Thanks for digging more deeply. I was wondering about this because I've used TTrees containing TH1F as an example.

Each object's header contains its version number, and the error you see is what happens if an object of a particular class and version number exists in the file but there's no streamer for that specific combination. It looks like your objects are TH1F version 7 (a believably recent-sounding version number for a popular class like TH1F) but there's only a streamer for version 2 (sounds very old).

Can ROOT open the file? In principle, it sounds like it shouldn't be able to because the particular TH1F version the objects need isn't available. But maybe it works in ROOT anyway because your version of ROOT might have TH1F 7 in the C++ code. (In which case, I should probably bake in some recent versions of popular classes, rather than always relying on the self-describing streamer mechanism.)

ROOT sometimes loses streamers if data are produced in one run and then copied or otherwise manipulated in another run. You also have a somewhat unusual situation in having histograms inside a TTree, a situation that may be less well-tested.

**Comment by lukepolson** [comment]
Thanks for the in depth reply.  Two things: 

1) I tried to force write the streamers using the technique you discussed in https://github.com/scikit-hep/uproot/issues/260. My code is as follows:

```
void force_streamers() { 
  TFile* output = new TFile("LArPhysWave_350000_FCAL.root", "UPDATE");
  TClass::GetClass("TH1F")->GetStreamerInfo()->ForceWriteInfo(output, kTRUE);
  output->Write();
  output->Close();
}
```

The only difference this made was it seemed to add version 8 for TH1 in the file streamers (in addition to version 7) but still left TH1F at version 2.

2) Yes I am able to open the histograms in ROOT. Here is a little macro which I quickly wrote up to draw an example of one.

```
TFile *f;
TTree *t;

void try_hist() {

  f = new TFile("LArPhysWave_350000_FCAL.root",  "READ");
  t = (TTree*)f->Get("PulseShapes");

  TH1F *histo = new TH1F;

  t->SetBranchAddress("pulse_shapes", &histo);
  t->GetEntry(0);

  histo->Draw();
}
```

If worse comes to worst, I'll probably end up just copying and instead of having histograms, I'll just have arrays in  the pulse_shapes branch of the TTree. Is it reasonable to bake in a version of the TH1F 7 class into the UPROOT code in the near future?

**Comment by jpivarski** [comment]
If you have the option to remake the files, I think you'd be much better off creating a fixed-length array branch: uproot will read this directly into a 2-dimensional Numpy array, providing a lot more versatility (and speed) than a collection of histogram objects. (I'm assuming that all of the histograms in the TTree have the same binning.)

The idea of putting specific versions of streamers into uproot is speculative. I'd have to survey a suite of ROOT versions to find out what are the most recent versions of a hand-picked set of types, and I'll need to use all of those ROOT versions to generate the streamers. (The only way I know of to make a streamer is to install the version of ROOT that has it somewhere and make a file. I don't know any way to find which ROOT versions are associated with with class versions—I'd have to run an ensemble of ROOTs on a suite of virtual machines. That's how I made the test files in the samples directory, generated by ROOT versions from the past 5 years. At that time, I didn't think to put enough objects in those sample files to force the generation of streamers as well. It looks like your ROOT version produces TH1F 8, rather than 7.)

For multiple reasons, I think your best option is to make a TTree of fixed-size arrays: your data analysis downstream of that will be easier and faster as well.

**Comment by lukepolson** [comment]
Cheers, thanks for all your help.

**Comment by jpivarski** [comment]
Good luck!
