### ISSUE TITLE
Loading aligned data from multiple TTrees - friending in uproot?

### ISSUE THREAD

**Issue by pibion** [scikit-hep/uproot#314]
We're interested in using uproot to load several root files that have trees that we would typically "friend" together when analyzing in ROOT - and are particularly wondering if there is an analogy to this in uproot that would also let us read in chunks of data that are aligned along their eventID axis.

It seems that loading data chunked by byte size or number of events would lead to data from different trees getting mismatched - I've attempted to illustrate this in the figure below, where it seems like reading three events at a time would result in e.g. event 2198 from "Det 1 Energy" being matched up with event 2130 from "Det 2 Energy".

Do you have any suggestions for friending branches in this case, or friending branches in general?  Lazy loading would be great, but being able to read in aligned data from across trees is our major concern.

<img width="232" alt="lazy-load-across-branches" src="https://user-images.githubusercontent.com/1872784/63039524-bac3db80-be80-11e9-9bf8-e77d165b9b9b.png">

**Comment by jpivarski** [comment]
If alignment is an issue (i.e. the friend TTrees don't begin and end on the same event number), then what you want to do is an SQL-like join. Uproot doesn't have any code to do that, but that's what Pandas is for.

The primary difference between Pandas and Numpy is that Pandas has SQL-like indexing. (The other major difference is that Pandas is more "batteries included" with respect to statistical analysis.) The Pandas equivalent of a Numpy array is a Series, which is a Numpy array with an index array indicating what each row means. You would want the index to be event number. A Pandas DataFrame is just a bunch of Series that share an index.

Pandas has a [suite of functions](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html) for merging Series and DataFrames on their indexes—what you're calling alignment. In my reading of that page, it looks like what you want is `pandas.concatenate` with `join="outer"` (the default). In SQL terminology, that's a full outer join, meaning that data from both friend TTrees are included in the output and if one TTree doesn't have a given event, it's included in the result with its columns as `NaN`. Pandas has a lot of tools for dealing with `NaN` (see `fillna`).

Uproot can output as Pandas DataFrames (see [tutorial](https://github.com/scikit-hep/uproot#filling-pandas-dataframes) and [reference](https://uproot.readthedocs.io/en/latest/ttree-handling.html#id7)). When it does so, it uses TTree entry number as an index, which is not the same thing as event number. You'll have to load your event number branch along with the branches you want and then change the index in place. (It's a matter of replacing a Numpy array in Pandas's index object.)

If the data are jagged, the default behavior is `flatten=True`, which puts the jaggedness into a subentry number in Pandas's index. You'll want to replace the entry with event number, but not the subentry. Also, if any of the branches you read are jagged, all of them have to have the same jagged structure. To read, for example, electrons and jets, you need to call `ttree.pandas.df` twice and make two DataFrames. Since Pandas represents jaggedness in its index and a DataFrame can have only one index, you'll need a separate DataFrame for every quantity that's differently jagged: electrons, muons, jets, genParticles, etc. Also, you'll need a separate DataFrame for non-jagged branches if you're interested in event-level values when the number of particles is zero. (Try it out with a branch that is empty for some events and you'll see what I mean.)

It's funny that you write exactly as I'm working on a prototype for how a future awkward-array could do indexing—I'm up to my elbows in inner and outer joins. At the moment, though, the most readily available tool that does SQL-like indexing well, even for MultiIndex (event numbers × subentry numbers), is Pandas.

**Comment by bloer** [comment]
@jpivarski I think you're missing the essential point of the question.  If my data is in a single tree, I do my analysis via 
```python
for frame in uproot.pandas.iterate(files, treename):
    my_analysis(frame)
```
If I have multiple trees, I can merge them together with something like:
```python
for frames in zip( uproot.pandas.iterate(files, treename) for files in array_of_filenames) ):
    for frame in frames: 
        frame.set_index('Event ID', inplace=True)
    merged = pandas.concatenate(frames, axis=1)
```

That works great, but **only if the chunk boundaries align.**.  Let's say I give `entrysteps=3` to `uproot.pandas.iterate`, to match what Amy has illustrated.  Then in the first pass through the loop, the data for event 2130 will be properly aligned, but there won't be any data in the first frame yet to match 2135 and 2136 that have already been loaded in the second frame.  By time those entries are loaded into the first frame in the third loop iteration, they are no longer loaded in frame 2. 

Of the existing `entrysteps` options, only `Inf`, i.e. load one-file-at-a-time, can control chunk borders in this way, and that of course assumes your entire file can fit in memory.  But maybe there could be an additional option to `uproot.pandas.iterate`, like `index`, that could change the chunking, so that if I call 
```python
uproot.pandas.iterate(files, treename, entrysteps=1000, index='Entry ID')
```
I would get variable-sized chunks corresponding to each 1000 entry IDs.  (As a bonus, an arg like this could set the DataFrame's index on construction, which would be cheaper than re-setting it on a constructed object).  

Does this make more sense?

**Comment by jpivarski** [comment]
Okay, so you're already using Pandas to align indexes at an event-by-event level, but you need to ensure that those indexes are available at the chunk-by-chunk level, so that you don't lose events in the cracks between the chunks.

Uproot needs the `entrystart` and `entrystop` to read (derived from `entrysteps`) before it can begin a read because (a) it has to preallocate arrays to fill and (b) it needs to jump to the right baskets. If ROOT were a rowwise format like CSV, then we'd just read each row until we get to the next `'Entry ID'`, but it's columnar: reading any amount of a basket means reading the whole basket.

Columnar database formats like Parquet solve this problem by adding "zone map" metadata on each basket/page: the minimum and maximum index value is added to the metadata, so if we're not interested in any index values in that page, we don't have to read it. As far as I know, ROOT doesn't have any zone map (but it might be a special feature for friend trees that I'm unaware of).

However, there may be yet another way, by taking advantage of ROOT's columnar nature. No matter how big your files are, I believe that you can read the entire `'Entry ID'` columns for all of your friend trees. A gigabyte of RAM would hold a quarter million int32s. For friend trees `A` and `B`, suppose you read the entire `A.EntryIDs` and `B.EntryIDs` into memory, then slice `A.EntryIDs` into equal-sized chunks.

These will be the right chunks for all of `A`'s other columns, but not `B`'s. If this column is sorted, you could use [numpy.searchsorted](https://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html) to translate your equal slices of `A.EntryIDs` into not-quite-equal slices of `B.EntryIDs` that work for all of `B`. This function does bisection search on all of the indexes given.

After that, you can iterate through all columns of `A` and `B` using the equal slices of `A` and the not-quite-equal slices of `B`, and they will be aligned so that each contains the same ranges of `'EntryIDs'`. The `entrysteps` parameter of [tree.pandas.df](https://uproot.readthedocs.io/en/latest/ttree-handling.html#uproot._connect._pandas.TTreeMethods_pandas.df) can be a list of not-quite-equally spaced `(entrystart, entrystop)` pairs—it doesn't have to be a constant number. That's where you can put the output of `numpy.searchsorted`.

You would have to do that separately on each pair of files, as a script. (Also, do you have just two friend trees `A` and `B` or more?)

This sounds like a bit of work, something that the library ought to handle for you. However, I've never worked with ROOT friend trees (or have any examples), so I'm not the best person to develop the convenience method. If you get this working in your case as a script, I can help you get it into uproot as a contributed feature. What do you think?
