### ISSUE TITLE
Preskim root file 

### ISSUE THREAD

**Issue by alefisico** [scikit-hep/uproot#321]
Hi,
Sorry for the very basic question but I am still new to this package. I was wondering if there is a simple way to make a "preskim" of the root file before I start processing the data. Something like this: https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/preskimming.py#L50-L73
thanks!

**Comment by jpivarski** [comment]
I assume that you mean (1) read a ROOT file, (2) drop some of the events (skim) and possibly some of the branches (slim), and (3) write a new ROOT file. Steps (1) and (2) are easy enough:

```python
import uproot
selected_branches = uproot.open("file.root")["Events"].arrays(["branch1", "branch2"], namedecode="utf-8")
cut_expression = ... # Numpy logic on selected_branches["arrayname"]
selected_events = {name: array[cut_expression] for name, array in selected_branches.items()}
```

and if the file or files are large, put the whole thing inside of

```python
for selected_branches in uproot.iterate(["files*.root"], "Events", ["branch1", "branch2"], namedecode="utf-8"):
    ... # Numpy logic on chunks of events
```

But what's missing is step (3), writing to ROOT files. You can see, for example in PR #313, that this is in development; it's @reikdas's summer project. But at the moment, you either have to make skim files in ROOT/PyROOT or include the skimming as part of your analysis. (Making skim files as a separate step is only helpful if you're dropping a lot of the _events_, like 50% or more. If you're dropping _branches_, don't worry about it because ROOT and uproot do not read branches you don't explicitly ask for.)

There are alternatives... When you install uproot, you also get a package called awkward-array (the JaggedArrays are defined in awkward-array, so it's a strict dependency). This library can write to various formats, such as Parquet, HDF5, and ZIP:

```python
import awkward
events_as_table = awkward.Table(selected_events)
awkward.toparquet("file.parquet", events_as_table)

import h5py
hdf5_file = awkward.hdf5(h5py.File("file.hdf5", "w"))
hdf5_file["events"] = events_as_table

awkward.save("file.awkd", events_as_table)   # awkd is a specialized ZIP file, like Numpy's npz
```

And then you can read these files directly with awkward-array (`awkward.fromparquet`, `awkward.hdf5`, `awkward.load`) since they're not ROOT files. uproot is only for ROOT.

If your data are "flat" (purely Numpy arrays, not jagged, only one number per entry), then it's even easier: Numpy has its own ZIP format.

```python
import numpy
numpy.savez_compressed("file.npz", *selected_events)
```

which can be read back with `numpy.load`. The Numpy format is especially fast and small.

If you need ROOT files, use ROOT/PyROOT or wait about 3 weeks.  :)

Hope that helps!

**Comment by alefisico** [comment]
Thank you Jim, I'm actually just need 1) and 2) but for some reason I couldn't do it. I'll try your suggestion now.
thanks again!

**Comment by jpivarski** [comment]
In that case, [this tutorial](https://github.com/jpivarski/2019-07-29-dpf-python#readme) might be helpful, particularly `03-columnar-data-analysis` (working with arrays and jagged arrays, after you've read them from uproot).

**Comment by alefisico** [comment]
sorry again but still I cannot make it. I am able to open the root file (it is a simple nanoAOD root file), and open the `selected_branches` as you mentioned. The content is something like this:
`{b'Jet_pt': <JaggedArray [[200.625 191.25 76.125 ... 28.703125 24.609375 15.3046875] [160.25 88.1875 74.0 ... 30.875 22.734375 19.640625] [98.625 87.25 51.8125 ... 29.640625 29.015625 15.078125] ... [92.75 72.0 58.9375 ... 23.59375 19.34375 19.1875] [99.25 94.8125 88.3125 ... 17.8125 16.875 15.5546875] [191.625 80.375 49.875 ... 17.296875 16.5625 15.0859375]] at 0x7f5234269198>, b'Jet_eta': <JaggedArray [[1.6020508 -1.6999512 1.1896973 ... 2.5161133 0.23187256 2.6313477] [0.1565857 0.7056885 1.2592773 ... 2.0205078 3.0078125 -3.1552734] [-0.50061035 0.09446716 -1.2380371 ... -1.6047363 -2.1469727 4.354492] ... [-0.13708496 -1.2954102 -0.9724121 ... 0.9505615 1.8010254 1.8461914] [0.3062744 -0.20315552 0.5751953 ... 0.17785645 -4.6220703 0.6199951] [-0.46264648 -2.0483398 -1.9233398 ... 0.18710327 -2.9482422 4.2773438]] at 0x7f51f4316828>, b'Jet_phi': <JaggedArray [[-3.1323242 0.6746826 2.2163086 ... -1.1293945 2.019043 -0.70373535] [-2.0 1.9453125 0.7652588 ... -1.9306641 0.9395752 2.996582] [-1.6313477 1.6838379 -0.5772705 ... 1.2653809 -2.534668 1.0336914] ... [-3.135254 -0.6010742 0.84375 ... 2.9975586 2.6391602 -0.27130127] [-2.7495117 -0.703125 0.56933594 ... 2.9873047 2.6152344 -0.14083862] [2.230957 -1.3618164 -0.4418335 ... -1.6503906 -1.3928223 -2.7197266]] at 0x7f51f4302208>, ......`

and I am doing what you suggested, like:
```
cut_expression = "selected_branches[Jet_pt]>10"
selected_events = {name: array[cut_expression] for name, array in selected_branches.items()}
```
but I am getting index errors like: 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`
what am I doing wrong? Sorry again for the basic question.

**Comment by jpivarski** [comment]
First of all, use `namedecode="utf-8"` so that `selected_branches` is a dict from `str` → arrays, rather than from `bytes` → arrays. That really ought to be the default and probably will be in uproot 4.0 or something.

Secondly, the `cut_expression` should not be a string. It is a string in cmsNanoTools because that string is passed to ROOT as a `TTree::Draw` or C++ string, but uproot gives you Python objects that you can manipulate directly in Python. The procedure for applying a cut is

```python
cut_expression = selected_branches["Jet_pt"] > 10
cut_expression
```

picks the jet pT array out of that dictionary (you may want to shorten its name) and compares each value with 10. That gives you a mask, an array of `True` and `False` that you can then apply to any other array, for instance

```python
selected_branches["Jet_eta"][cut_expression]
```

to get an array of just the jet eta values for which jet pT > 10. That's why I recommended

```python
selected_jets = {name: array[cut_expression] for name, array in selected_branches.items()}
```

because it applies the `cut_expression` mask to each of the arrays you're interested in and gives you a new dict from str → array.

If not all of your arrays are jet arrays, but some are for electrons, muons, etc., then you'll need to apply the cuts to the appropriate arrays, so you do a little more Pythoning to make that happen. Note that I wrote `selected_jets` above, because that's what the above would do.

Since `selected_branches["Jet_pt"]` is a jagged array of jets in events, the `selected_branches["Jet_pt"] > 10` mask is a jagged mask (jagged array of booleans) that will cut _jets_, not _events_. For a cut on events, you need to do a comparison across events, such as

```python
cut_on_events = selected_branches["Jet_pt"].max() > 10
selected_events = {name: array[cut_on_events] for name, array in selected_branches.items()}
```

because `selected_branches["Jet_pt"].max()` finds the maximum jet pt per event (can be `-inf` if there are no jets in an event) and `cut_on_events` is a non-jagged array of `True` and `False`. When you apply _that_ to all arrays, it cuts _events_, and so you can use it on all of your particle types.

These are topics that are better covered in the tutorial I linked to above. Perhaps the main take-away is that doing analysis with arrays is not like doing analysis in a front-end to a C++ library: you don't form a string and pass it over a wall for another system to deal with. The arrays are fully on the Python side—you can manipulate them directly, so try it in an interactive terminal or Jupyter notebook to get a sense of what particle cutting versus event cutting is like.

Best,
-- Jim

**Comment by alefisico** [comment]
thank you so much Jim, I think now it is finally clear. I think I got really confused with this mask feature. Thanks a lot!
