### ISSUE TITLE
vector<uint_64> is read as jagged array of dtype uint32

### ISSUE THREAD

**Issue by DraTeots** [scikit-hep/uproot#341]
Hi!
I have a root file with "events" each of it having 

```c++
std::vector<uint64_t> hit_trk_id
```

When I open the file with root and print the branch info

```
root [13] b->Print()
*Br    0 :hit_trk_id : vector<unsigned long>                                 *
*Entries :      100 : Total  Size=     161079 bytes  File Size  =      16628 *
*Baskets :        6 : Basket Size=      32000 bytes  Compression=   9.66     *
*............................................................................*
```

When I open it with uproot:

```
events = uproot.open("data/g4e_test_herwig_100ev_2019-09.root")['events']
events.show()
```
The result:
```
...
hit_trk_id                 TStreamerSTL               asjagged(asdtype('>u4'), 10)
...
```
So it is 32 bits and the data is kind of corrupted if read without an explicit interpretation:
```python
print(events.array('hit_trk_id').flatten())   # flatten is for simplicity
```
gives
```
array([    0,  1021,     0, ..., 11801,     0, 11802], dtype=uint32)
```
(zeroes and dtype)

The workaround is something like:

```python
skip_bytes = 0
if isinstance(events['hit_trk_id'], asjagged):
    skip_bytes = asjagged.skipbytes
events['hit_trk_id'].array(asjagged(asdtype(np.uint64), skip_bytes))   # prints tree contents
```

But I believe it is a bug. 
The root file is attached. 

P.S. are skip_bytes always 10? 

[g4e_test_herwig_100ev_2019-09.zip](https://github.com/scikit-hep/uproot/files/3632337/g4e_test_herwig_100ev_2019-09.zip)

**Comment by jpivarski** [comment]
I think you're seeing an old, fixed bug (or an old version of your own file?):

```python
>>> import uproot
>>> b = uproot.open("issue-341.root")["events"]["hit_trk_id"]
>>> b.interpretation
asjagged(asdtype('>u8'), 10)
>>> b.array()
<JaggedArray [[1021 1021 1021 ... 2 5317 5316] [2318 2318 2318 ... 2 2 5809] [24 24 24 ... 2 2 5544] ... [27 27 27 ... 2 2 2] [28 28 28 ... 5062 5063 5061] [4287 4287 4287 ... 11801 11801 11802]] at 0x7f61ddbbcf98>
```

The interpretation in this file for the latest uproot is a jagged array of 64-bit unsigned integers. The first few values returned from this file are in agreement with what I see in ROOT (which sees it as a `vector<unsigned long>`). However, you printed those values in your report, too, so I wonder if you've got two versions of the file or something.

As for the `skip_bytes`, that's because `std::vector` has exactly 10 bytes of overhead at the beginning of each entry: 6 are a header, 4 are the size of the vector, which is redundant because the TBasket also has offsets pointing to the beginning of every entry. If the data are stored as different C++ types with equivalent meaning (e.g. `uint64_t[]` instead of `std::vector<uint64_t>`, or one of these embedded within a class, rather than being at top level), then there's a different number of bytes to skip. The reason for having this as a parameter is so that all of these cases can be handled by a single Python class. For a given branch, there's only one "right" value.

If you have another file that is incorrectly interpreted by uproot 3.10.1, you can reopen this issue and I'll take a look. Cheers!

**Comment by DraTeots** [comment]
Just came to say, that everything works in the new version. It happened, that on one machine I didn't have conda-forge and, I assume, used the old uproot version. 

Thank you for the answer and sorry for the disturbance!

**Comment by jpivarski** [comment]
Glad to hear it's working now!
