### ISSUE TITLE
Reading a file written with uproot: TTreeCache::{AddBranch,DropBranch}: unknown branch -> *

### ISSUE THREAD

**Issue by douglasdavis** [scikit-hep/uproot#352]
I'm taking a first stab at TTree writing and I'm running into an issue when trying to read the file back into ROOT (reading it back in uproot is working fine). ROOT is telling me
```
Error in <TTreeCache::AddBranch>: unknown branch -> *
Error in <TTreeCache::DropBranch>: unknown branch -> *
```
when I try to call `TTree::Show` on it. It seems like some kind of nameless ghost of a branch is appearing in the tree some how. I've also tested reading the uproot-originating tree via `RDataFrame` (to create ROOT histograms with `RDataFrame::Histo1D`). Things just crash.

My file is created like so:

```python
## `out_dict` is a dictionary of {name(type=str) -> data(type=numpy.ndarray)}.
## `tree` is just a string for the tree name in the file.

branches = {}
for colname, arr in out_dict.items():
    if arr.dtype == np.uint32: ## convert to int32 for now
        out_dict[colname] = out_dict[colname].astype(np.int32)
    branches[colname] = uproot.newbranch(out_dict[colname].dtype)
    log.info(f"Saving branch {colname} with dtype {out_dict[colname].dtype}")

with uproot.recreate(outfile) as f:
    f[tree] = uproot.newtree(branches, flushsize="10 MB")
    f[tree].extend(out_dict, flush=False)
```

I've tried tinkering with the flush (not declaring a `flushsize` on the tree and giving extend `flush=True`) and compression settings just to see if it might impact the error I'm seeing but it doesn't (just file size is different, as I guess is expected). [Link to file](http://webhome.phy.duke.edu/~ddavis/public/uproot352.root)

**Comment by douglasdavis** [comment]
Looks like we can get a branch named `*` [through logic on the ROOT side](https://github.com/root-project/root/blob/master/tree/tree/src/TTreeCache.cxx#L519-L523), but I can't quite follow how this is triggered

**Comment by reikdas** [comment]
Thanks for reporting the issue!

> `## `out_dict` is a dictionary of {name(type=str) -> data(type=numpy.ndarray)}.`

To aid in debugging, could you tell me how many dimensions does data have? (`data.ndim`)

**Comment by jpivarski** [comment]
Preferably a full reproducer—we're trying to catch cases we implicitly don't handle and replace them with `NotImplementedError` messages for now, so that we understand the boundaries of the current implementation and at least prevent the impression that a correct file has been made.

**Comment by jpivarski** [comment]
(Multidimensional arrays are one such case.)

In your example, it looks like a branch with an illegal name is getting created. We don't know the full set of illegal names, but if we did, we should check for them. `*` is very likely not allowed because it can be used in `SetBranchStatus` to mean "all branches." I wonder if any wildcard character anywhere is not allowed?

**Comment by marinang** [comment]
```
Error in <TTreeCache::AddBranch>: unknown branch -> *
Error in <TTreeCache::DropBranch>: unknown branch -> *
```

I also get this when I open files with the ROOT Browser to explore files created with uproot.

**Comment by reikdas** [comment]
I was able to reproduce the error. 
@jpivarski This isn't related to multidimensional arrays like we thought. It is some error that crept in via some commit, that we didn't catch because surprisingly calling AsMatrix() on the tree works.

**Comment by douglasdavis** [comment]
> To aid in debugging, could you tell me how many dimensions does data have? (`data.ndim`)

All of the values in the dictionary are one dimensional arrays

**Comment by douglasdavis** [comment]
Minimal reproducer below. As @marinang said, the error messages pop up when looking at a TBrowser (we can still see the data). Using `TTree::Show` _only_ gives the error message; and trying to use RDataFrame just crashes.

```python
import uproot
import numpy as np


data = {"a": np.random.randn(100).astype(np.int32),
        "b": np.random.randn(100).astype(np.float32),
        "c": np.random.randn(100).astype(np.float64)}

branch_templates = {"a": uproot.newbranch(np.int32),
                    "b": uproot.newbranch(np.float32),
                    "c": uproot.newbranch(np.float64)}

with uproot.recreate("output.root") as f:
    f["output_tree"] = uproot.newtree(branch_templates, flushsize="10 MB")
    f["output_tree"].extend(data, flush=False)
```

**Comment by jpivarski** [comment]
If the name of the branch literally is `"*"`, then it should be visible as such in uproot. Uproot treats the branch names as simple bytestrings with no interpretation. When selecting branches in one of the methods like `TTree.arrays`, it uses glob patterns to match them, but you should be able to just say `TTree.keys()` to see a list of them all. Maybe the `"*"` branch is just the first where it starts going bad, due to some off-by-one error.

It is weird that `TTree::AsMatrix` didn't care, though. I would have thought that that called underlying `TTree::GetEntry` code...

**Comment by reikdas** [comment]
@jpivarski The issue is at a more fundamental level. 

> If the name of the branch literally is "*"

No branch of that name exists. (Verified using uproot's `.allkeys()` and ROOT's `TTree.Print()`)

uproot is able to read the data in all cases. ROOT's `AsMatrix()` works, but `RDataFrame.AsNumpy()` and `TTree.Show() `does not give the expected results (error).
I know this used to work before as I think I remember using RDataFrame to read data from files written by uproot - which is why I said the bad commit must have crept in at some point, will have to find it.

Since uproot is able to read it, the error is due to a lapse in our understanding of how TTree basket data is serialized. I have a rising suspicion that this may have something to do with the fBaskets attribute(the recovery basket data).. in which case this is not a trivial bug to solve.

**Comment by jpivarski** [comment]
@reikdas Do we know under what conditions it happens? Does this happen for all TTrees written by uproot (i.e. by only testing `TTree::GetEntry` and `TTree::AsMatrix`, we missed something that every TTree should have, which is only revealed when calling `TTree::Show` or `RDataFrame::AsDict`)? Does it happen for some or all of the unit tests

**Comment by reikdas** [comment]
> Does this happen for all TTrees written by uproot?

Yes :(

> Does it happen for some or all of our unit tests?

All of them :(

**Comment by jpivarski** [comment]
Okay, so we have a mistake in our understanding of the TTree format because our readback tests in ROOT (`TTree::GetEntry`, which we used for what we thought was complete generality and `TTree::AsMatrix`, which we used for convenience) were insufficiently general. These two ROOT functions don't fully validate the binary format of the TTree object—they don't touch whatever we're doing that's wrong.

@douglasdavis and @marinang, what ROOT commands would constitute a sufficient test of conformance? I would think that `RDataFrame` is necessary (and I thought we used it in some earlier tests because it has a convenient `RDataFrame::AsNumpy` method).

   * `RDataFrame::AsNumpy`
   * `TBrowser` is something we can use in a spot-check, but not in tests, because of the GUI.
   * `TTree::Show`
   * `TTree::Print`

`TTree::Show` and `TTree::Print` can't be used in unit tests without capturing the stdout (and hoping ROOT doesn't change its human-readable format), but they can be included in the tests just to see that they don't crash.

Given that `TTree::GetEntry` and `TTree::AsMatrix` return expected results, the binary format that we're writing is probably not far from correct—only some functions touch the error; others don't.

**Comment by reikdas** [comment]
> - `TTree::Print`

This works correctly on files written by uproot, so checking if this causes a crash is not a valid test.

**Comment by douglasdavis** [comment]
> what ROOT commands would constitute a sufficient test of conformance?

The items you listed exhaust all but one thing I can think of. Perhaps something along these lines can be tested (given some well understood ROOT file with pt and eta for example):

```python
import ROOT
RDataFrame = ROOT.ROOT.RDataFrame
TH1DModel = ROOT.ROOT.RDF.TH1DModel
import uproot
import numpy as np

rdf = RDataFrame("tree", "file.root")
filter = rdf.Filter("pt > 25 && abs(eta) < 2.5")
pthist_model = TH1DModel("pthist", ";pt;", 25, 225, 20)
pthist = filter.Histo1D(pthist_model, "pt")

t = uproot.open("file.root").get("tree")
pt = t.array("pt")
eta = t.array("eta")
selection = (pt > 25) & (np.abs(eta) < 2.5)
counts, edges = np.histogram(pt[selection], bins=20, range=(25, 225))

pthist_data = np.ndarray(shape=(25,), dtype=np.foat64, buffer=pthist.GetArray())
assert np.allclose(pthist_data, counts)
```

**Comment by jpivarski** [comment]
@reikdas I'm triaging the issue and I came across this peculiarity: uproot does not produce `TTree::fLeaves` as it should. Reproducing example:

```python
import numpy
import uproot
with uproot.recreate("byuproot.root", compression=None) as f:
    f["tree"] = uproot.newtree({
                    "branch": uproot.newbranch(numpy.int32, title="BRANCH")
                }, title="TREE")
    f["tree"]["branch"].newbasket(numpy.arange(10))
```

```c++
#include "TFile.h"
#include "TTree.h"

void byroot() {
  TFile* f = new TFile("byroot.root", "RECREATE");
  f->SetCompressionLevel(0);

  TTree* t = new TTree("tree", "TREE");
  int data;
  t->Branch("branch", &data, "leaf/I");

  for (int i = 0;  i < 10;  i++) {
    data = i;
    t->Fill();
  }
  t->Write();
  f->Close();
}
```

Reading back:

```python
import uproot
byroot = uproot.open("byroot.root")
byuproot = uproot.open("byuproot.root")

byroot["tree"]["branch"]._fLeaves
# returns [<TLeafI b'leaf' at 0x7f0b43e44dd8>]
byuproot["tree"]["branch"]._fLeaves
# returns [<TLeafI b'branch' at 0x7f0b43e44ef0>]

# but
byroot["tree"]._fLeaves
# returns [<TLeafI b'leaf' at 0x7f0b43e44f98>]
byuproot["tree"]._fLeaves
# returns [None]
```

so they can't be identical binaries. This points to an issue in the `writeobjany`, our least favorite function, but at least we don't have to speculate that it's somehow outside of the TTree binary. Could you look into that while I dig deeper?

**Comment by jpivarski** [comment]
(Incidentally, uproot never uses `TTree::fLeaves`, so this would be a difference in usage that makes the files fully readable in uproot. It's a hint, at least.)

**Comment by jpivarski** [comment]
Another strangeness: I can read both files in ROOT!

```bash
% root -l byroot.root byuproot.root 
root [0] 
Attaching file byroot.root as _file0...
(TFile *) 0x55d38e4ba500
Attaching file byuproot.root as _file1...
(TFile *) 0x55d38e4aff80
```

and then

```c++
TTree *byroot, *byuproot;
_file0->GetObject("tree", byroot);
_file1->GetObject("tree", byuproot);
byroot->Print();
```
```
******************************************************************************
*Tree    :tree      : TREE                                                   *
*Entries :       10 : Total =             933 bytes  File  Size =        941 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
*Br    0 :branch    : leaf/I                                                 *
*Entries :       10 : Total  Size=        596 bytes  File Size  =        113 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
```
```c++
byroot->Scan();
```
```
************************
*    Row   * branch.br *
************************
*        0 *         0 *
*        1 *         1 *
*        2 *         2 *
*        3 *         3 *
*        4 *         4 *
*        5 *         5 *
*        6 *         6 *
*        7 *         7 *
*        8 *         8 *
*        9 *         9 *
************************
(long long) 10
```
```c++
byuproot->Print();
```
```
******************************************************************************
*Tree    :tree      : TREE                                                   *
*Entries :       10 : Total =            1008 bytes  File  Size =       1820 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
*Br    0 :branch    : Int_t BRANCH                                           *
*Entries :       10 : Total  Size=        667 bytes  File Size  =        180 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
```
```c++
byuproot->Scan();
```
```
************
*    Row   *
************
*        0 *
*        1 *
*        2 *
*        3 *
*        4 *
*        5 *
*        6 *
*        7 *
*        8 *
*        9 *
************
(long long) 10
```

So far, so good. But I just remembered that "`Scan`" is different from "`Show`" (they both start with "S"), and I _do_ see a difference when I "`Show`" them:

```c++
byroot->Show();
```
```
======> EVENT:9
 leaf            = 9
```
```c++
byuproot->Show();
```
```
======> EVENT:9
```

Specifically, the weirdness is in the list of leaves, which we already know is wrong from uproot. So far, this is the only thing I'm seeing as being wrong.

**Comment by reikdas** [comment]
Thanks for pointing the thing about the fLeaves out! I'll look into it.

**Comment by jpivarski** [comment]
The issue with reading with `RDataFrame` is directly related to the malformed `TTree::fLeaves` list:

```python
import ROOT
ROOT.RDataFrame("tree", "byroot.root").AsNumpy()
# returns {'branch.leaf': numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)}

# but
ROOT.RDataFrame("tree", "byuproot.root").AsNumpy()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pivarski/miniconda3/lib/python3.7/site-packages/ROOT.py", line 418, in _RDataFrameAsNumpy
    column_type = df_rnode.GetColumnType(column)
Exception: string ROOT::RDF::RInterface<ROOT::Detail::RDF::RNodeBase,void>::GetColumnType(basic_string_view<char,char_traits<char> > column) =>
    Column "branch" is not in a dataset and is not a custom column been defined. (C++ exception of type runtime_error)
```
That error message
   * is emitted from RDFUtils.cxx's [ColumnName2ColumnTypeName](https://github.com/root-project/root/blob/497c1fbc0ce26aef9b43d9231b6279a3d2bea688/tree/dataframe/src/RDFUtils.cxx#L197-L226),
   * because `colType` fails to be filled by RDFUtils.cxx's [GetBranchOrLeafTypeName](https://github.com/root-project/root/blob/497c1fbc0ce26aef9b43d9231b6279a3d2bea688/tree/dataframe/src/RDFUtils.cxx#L148-L151),
   * which immediately calls [TTree::GetLeaf](https://github.com/root-project/root/blob/c7c1340fbe16f8df0149267d3150391ae5e24415/tree/tree/src/TTree.cxx#L6005-L6018) (one string argument),
   * which calls [TTree::GetLeafImpl](https://github.com/root-project/root/blob/c7c1340fbe16f8df0149267d3150391ae5e24415/tree/tree/src/TTree.cxx#L5895) (with `nullptr` as a `branchname`),
   * which wants to iterate over [GetListOfLeaves](https://github.com/root-project/root/blob/c7c1340fbe16f8df0149267d3150391ae5e24415/tree/tree/src/TTree.cxx#L5907) (because `branchname` is `nullptr`),
   * which is simply [fLeaves](https://github.com/root-project/root/blob/c7c1340fbe16f8df0149267d3150391ae5e24415/tree/tree/inc/TTree.h#L441),
   * which uproot doesn't correctly write.

So unless there's something else wrong, fixing the `TTree::fLeaves` should allow uproot-written files to be read by `RDataFrame`.

**Comment by jpivarski** [comment]
I don't fully know how `TTreeCache` gets into [the state reported](https://github.com/root-project/root/blob/fd29ebe718940d22d561c51498bae8487243c986/tree/tree/src/TTreeCache.cxx#L513-L517) by @douglasdavis and @marinang (though I have reproduced it with `TBrowser`), but that function

   * uses [GetListOfLeaves](https://github.com/root-project/root/blob/e8b110a37c1329b254989b38d9632f51737dc643/tree/tree/src/TTreeCache.cxx#L444) at several points, so wrong values here can affect whether `branch` is initialized and `nb` is non-zero.
   * I think that a `bname` of `"*"` is a normal entry state for this function, but it presumably expects to replace `"*"` with a list of all branch names [starting from the TLeaf object returned by GetListOfLeaves](https://github.com/root-project/root/blob/e8b110a37c1329b254989b38d9632f51737dc643/tree/tree/src/TTreeCache.cxx#L454), which we already know is problematic.

So all warning bells are pointing at `TTree::fLeaves`. There's a good chance that fixing that one attribute will fix all the problems users have been seeing.

_(At least let's hope!)_

**Comment by jpivarski** [comment]
@reikdas Okay, here's the issue:

   * When `TBranch::fLeaves` is being written, it goes through `writeobjany` and writes whole `TLeaf` classes and objects (because it's first).
   * Then when `TTree::fLeaves` is being written, it goes through `writeobjany` and writes tags (references to the objects) that are too small by 8.

When reading (in `_readobjany`), I see a `cursor.refs` of

```python
{278: <class 'uproot.rootio.TBranch'>, 469: <class 'uproot.rootio.TLeafI'>,
 465: <TLeafI b'branch' at 0x7fc57e7fc3c8>, 274: <TBranch b'branch' at 0x7fc57e835d68>}
```

when we want to read `TTree::fLeaves`. (This is after we've already successfully read all `TBranch::fLeaves`.) The leaf object should be referenced with tag 465, but the tag ([first four bytes read](https://github.com/scikit-hep/uproot/blob/02228a7835a6f908a968d8391349bac800f869ac/uproot/rootio.py#L450-L456) by `_readobjany`) is 457, and it misses the `TLeafI` object by 8 (465 - 457). That's why it shows up as `None` in uproot and `nullptr` in ROOT: it has to be exact.

Interestingly, the correct position in the file I made with ROOT happens to be 457, but that could have been an accident of offsets. In both ROOT and uproot, changing the title of the TTree shifts all of these positions by a constant because they're all defined by relative seek positions. So it seems that uproot-writing is correctly not hard-coded for these positions, but it is off by 8. (I made files in ROOT and uproot with identical names apart from the leaf name, which is `"leaf/I"` in the file made by ROOT and `"branch"` in the file made by uproot, which happens to be the same number of characters.)

Some places to look for the reason behind the offset by 8:

   * The tags associated with classes have a relative seek position that differs from tags associated with objects by 4 (because tags associated with [objects are relative to the seek position _before_ reading the 4-byte tag](https://github.com/scikit-hep/uproot/blob/02228a7835a6f908a968d8391349bac800f869ac/uproot/rootio.py#L497) and tags associated with [classes are relative to the seek position _after_ reading the 4-byte tag](https://github.com/scikit-hep/uproot/blob/02228a7835a6f908a968d8391349bac800f869ac/uproot/rootio.py#L485)).
   * All of the tags in question have a `kMapOffset` of 2.
   * ...?

**Comment by reikdas** [comment]
> Interestingly, the correct position in the file I made with ROOT happens to be 457

ROOT and uproot always write the same value of the tag, which is why the byte sequence in the TTree written by both ROOT and uproot are always the same. I had added in a -8 offset to make them match up (I thought it was relevant when debugging some unrelated issue).

I have fixed the issue in https://github.com/scikit-hep/uproot/commit/654713718651645dc0381a16c6c8da06cfc1d657 :) 

Thanks so much for your help!

**Comment by jpivarski** [comment]
Is this in a PR? I'd like to see if this fixes everybody's problems.  :)

**Comment by reikdas** [comment]
Yes https://github.com/scikit-hep/uproot/pull/358 ! (Sorry, I was cleaning some things up before making the PR - I am done now)

**Comment by jpivarski** [comment]
I've approved the PR and we should make a new version of uproot from it (your `RDataFrame` unit test shows that what you've done is already an improvement), but @douglasdavis and @marinang, does the new branch (or, by the time you read this, new version of uproot) fix your problems?

**Comment by douglasdavis** [comment]
Testing the new branch, `TTree::Show` and `TTree::Scan` and `RDataFrame` seem to only find the first branch. (using the result from [this comment](https://github.com/scikit-hep/uproot/issues/352#issuecomment-536195428). In a TBrowser everything is showing up.

**Comment by reikdas** [comment]
I think I know what the problem is. I'll start looking into it. Thanks for reporting.

**Comment by reikdas** [comment]
@douglasdavis @marinang Can you check if branch issue352 https://github.com/scikit-hep/uproot/tree/issue352 fixes your issue?

**Comment by marinang** [comment]
@reikdas I have just tried and I don't  see error message.

> ```
> Error in <TTreeCache::AddBranch>: unknown branch -> *
> Error in <TTreeCache::DropBranch>: unknown branch -> *
> ```
> 
> 
> I also get this when I open files with the ROOT Browser to explore files created with uproot.

**Comment by douglasdavis** [comment]
Things appear to be working smoothly for me as well.

**Comment by reikdas** [comment]
Great! :)
