### ISSUE TITLE
Getting branch type and shape without reading data

### ISSUE THREAD

**Issue by imandr** [scikit-hep/uproot#37]
Is there a way to get the branch type and shape without actually reading the data ?
In particular, is there a way to do something like this:

b = tree["path"]
btype = b.type()             # ndarray or JaggedArray ?
bshape = b.shape()        # (nevents,) for ndarray and (nevents, None) for Jagged

This would significantly speed up the process of schema inference.

Thanks.

**Comment by jpivarski** [comment]
`uproot.interpret(b)` gives you the interpretation without reading any data. In the case above, it would be an `asjagged` because the default interpretation is to read this branch into a jagged array, and that has an `asdtype` attribute with `fromdtype` (how it interprets the bytes in the file; big-endian) and a `todtype` (the array it presents after reading; native-endian). You want `todtype`.

The `asdtype` also has `fromdims` and `todims`, which is all elements of the shape parameter except the first one, the gross size. For most data, these "dims" are all `()` (no special shaping— the data are one-dimensional).

But you want that gross size, probably— that's probably what you meant by the shape. What you actually want is either the `b.numentries` for the number of entries (length of the outer list in the jagged array) or `b.numitems(...)`, which is a computed quantity, based on interpretation, corresponding to the sum of inner list lengths in the jagged array. Without reading the array, I only know how many bytes it occupies on disk, and how many items that corresponds to depends on the interpretation. If it's a simple jagged array, for instance, I can just divide the number of bytes by the byte width of the interpreted data type. If it's from an exploded class, I have to subtract one byte per entry because this case was padded for some reason. If it's an STL vector, I have to subtract 10 bytes per entry. Strings are even more complicated. So that's why it depends on interpretation, but it will pick up the default interpretation (`uproot.interpret(b)`) if you don't specify.

This isn't exactly a bug report, so I made a Google Group called "uproot users".
