### ISSUE TITLE
uproot.iterate error (AttributeError: object has no attribute)

### ISSUE THREAD

**Issue by iokarkan** [scikit-hep/uproot#384]
Hello, I've come across the following error while trying to get uproot iterate to loop over 2 separate files. My command is:
`for data in uproot.iterate("*.root","Delphes",["Particle.PT","Particle.Eta","Particle.Phi","Particle.E","Particle.Pz","Particle.fUniqueID",
                        "GenJet.PT","GenJet.Mass","GenJet.Particles","GenJet.Constituents"],namedecode="utf-8",entrysteps=steps):
    pass`

and the error (**Windows**)
`Traceback (most recent call last):
  File "D:/share_with_cernvm/PyCharm uproot/largegenjet_bkgzj/[manyfiles_iterate][loop_out_of_function]reco_object_selection_delphes.py", line 139, in <module>
    "GenJet.PT","GenJet.Mass","GenJet.Particles","GenJet.Constituents"],namedecode="utf-8",entrysteps=steps):
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 114, in iterate
    for tree, newbranches, globalentrystart, thispath, thisfile in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options):
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 174, in _iterate
    elif not newbranches[key].compatible(oldbranches[key]):
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\interp\objects.py", line 316, in compatible
    return isinstance(other, asgenobj) and self.generator.cls.__name__ == other.generator.cls.__name__
AttributeError: 'SimpleArray' object has no attribute '__name__'`

and (**Ubuntu 18.04**):
`Traceback (most recent call last):
  File "/media/sf_share_with_cernvm/PyCharm_uproot/largegenjet_bkgzj/[manyfiles_iterate][loop_out_of_function]reco_object_selection_delphes.py", line 141, in <module>
    "GenJet.PT","GenJet.Mass","GenJet.Particles","GenJet.Constituents"],namedecode="utf-8",entrysteps=steps):
  File "/home/kark/PycharmProjects/uproot/venv/lib/python3.6/site-packages/uproot/tree.py", line 114, in iterate
    for tree, newbranches, globalentrystart, thispath, thisfile in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options):
  File "/home/kark/PycharmProjects/uproot/venv/lib/python3.6/site-packages/uproot/tree.py", line 174, in _iterate
    elif not newbranches[key].compatible(oldbranches[key]):
  File "/home/kark/PycharmProjects/uproot/venv/lib/python3.6/site-packages/uproot/interp/objects.py", line 316, in compatible
    return isinstance(other, asgenobj) and self.generator.cls.__name__ == other.generator.cls.__name__
AttributeError: 'SimpleArray' object has no attribute '__name__'
`

Now, I can see that googling gets me to [Issue 274](https://github.com/scikit-hep/uproot/issues/274), but I cannot find any solution in the link of the comment. Is this not the correct syntax? 
I am trying the 1st snippet both in Windows and a Ubuntu 18.04 VM, in python2.7, getting the same error. 

Also, trying the example from the tutorial on how to use uproot.iterate fails on windows 10 with the similar error:

`Traceback (most recent call last):
  File "D:/share_with_cernvm/PyCharm uproot/largegenjet_bkgzj/[manyfiles_iterate][loop_out_of_function]reco_object_selection_delphes.py", line 145, in <module>
    reportpath=True, reportfile=True, reportentries=True):
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 114, in iterate
    for tree, newbranches, globalentrystart, thispath, thisfile in _iterate(path, treepath, branches, awkward, localsource, xrootdsource, httpsource, **options):
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 151, in _iterate
    paths = [y for x in path for y in _filename_explode(x)]
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 151, in <listcomp>
    paths = [y for x in path for y in _filename_explode(x)]
  File "C:\Users\kark\AppData\Local\Programs\Python\Python36\lib\site-packages\uproot\tree.py", line 70, in _filename_explode
    if _bytesid(parsed.scheme) == b"file" or len(parsed.scheme) == 0 or (os.name == "nt" and open._windows_absolute.match(x) is not None):
AttributeError: 'builtin_function_or_method' object has no attribute '_windows_absolute'`

**Comment by jpivarski** [comment]
The two errors are unrelated. For the first, uproot checks to see that the data types don't change too much from one file to the next (checks that the new type is `compatible` with the old), and it looks like I had assumed that the data type is always a class (which has a `__name__`), but sometimes it can be `SimpleArray` or `STLVector` objects. In PR #385, I gave these objects `__name__` properties, so they shouldn't fail when crossing the boundary. Sorry about that.

Could you try checking out and testing PR #385 to see if your problem is fixed?

(This can be counted as a failure of Python's dynamic typing—a static type-checker would have caught that. However, once found, it's easy to fix. I'm on the fence about dynamic typing.)

The second error, related to opening a file on Windows, is something that has already been fixed, so you somehow have the wrong version. What's worse, your code represents an intermediate stage in fixing #382. The PR that fixed it, #383, has two commits—it looks like you got the first but not the second. According to GitHub's records, I merged and deployed after the second commit, so I'm puzzled about the fact that you're seeing it. Are you using the old PR?

**Comment by iokarkan** [comment]
I am using PyCharm and a virtual environment, the python3.6 interpreter I am using has uproot version 3.10.6 installed.
It shows that 3.10.8 is available in the `https://pypi.python.org/simple` repository.  Should I wait for 3.10.9 to be available?

**Comment by iokarkan** [comment]
As for checking it firsthand, I am afraid I'm not quite familiar as to how I should handle a specific pull request.

**Comment by jpivarski** [comment]
The latest release is 3.10.8. I've made a proposed fix for your problem, but I won't know if it's really helping you until you test it. When you give me the okay, I'll deploy the fixed version as 3.10.9.

To check out a PR (#385 in this case), go to the PR to see the branch name: there's a copy icon that copies it to the clipboard: "issue-384" (I name my PR branches after the issues they address). Then you can pip-install the provisional version like this:

```bash
pip install git+https://github.com/scikit-hep/uproot.git@issue-384
```

When you're done testing and I've deployed 3.10.9, you can get on the official release by

```bash
pip install --upgrade uproot
```

Since you observed two bugs, one real and the other maybe a version mismatch, could you test both before giving me the okay? I want to be sure that everything is fixed before I deploy again.

Thanks!

**Comment by iokarkan** [comment]
Perfect, I really appreciate the effort you're putting in for the walkthrough. I will try it and report back asap.

**Comment by iokarkan** [comment]
Indeed, it works for me. Iteration correctly switches files now.

**Comment by jpivarski** [comment]
Is the Windows bug still there? That's something I can't test directly.

**Comment by iokarkan** [comment]
I edited my comment, the windows bug is no longer there!

**Comment by jpivarski** [comment]
Thanks! When [this CI/CD](https://travis-ci.org/scikit-hep/uproot/builds/602365607) finishes, uproot 3.10.9 will be available and you'll be able to get it with

```bash
pip install --upgrade uproot
```
