### ISSUE TITLE
iterate does not read all requested branches

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/uproot#388]
I'm reading multiple root files containing trees. Some of the root files contain branches, which the others don't. I only need selected branches from the root files. Some of the branches I want are only present in some root files. Thus I use uproot.iterate, where the branches argument is a function TBranchMethods ⇒ True or False.
What I would expect is, that the dict yielded by iterate contains the branches as they are available.
But instead the branches inside the dict are determined by the branch availabilities of the first file that was read: When the first file does not have some branches, they are not read for later files that have them; when a later file does not have a branch, an exception is raised by uproot/tree.py.
Everything seems to be caused by lines 178 to 183 in tree.py.
I can not understand this behaviour from the documentation. It also does not make sense to call the function given by the branches argument in every iteration step if the branches are determined by the first call. For my case, the only way I could solve the issue is by splitting the files I have into categories of their available branches and then having a iterate loop for each of the categories. This would be complicate things by a lot.

**Comment by jpivarski** [comment]
(I'm about to be out of contact for 24 hours, so I'm afraid a clarification will be all I can provide for now.)

The intention was to provide the subset of branches that exist in all files, as well as verify that their types are consistent (`Interpretation.compatible`) across the dataset. Some systems would require them to be exactly the same, and uproot may be used to feed into one of those systems. However, it can't look ahead into all files to check for consistency for performance reasons, so that's why it has this narrowing scope. (It can't take away the events it's already delivered!) In the past, it actually raised an error. I just didn't know what to do about these situations—I would think you'd always want all ROOT files to have the same set of branches with the same types.

If this isn't the case, then even the narrowing-scope policy is too limiting, as you say. Maybe what it ought to do is hang onto the original branch request (the `branches` variable before it's passed into `tree._normalize_branches`) and reevaluate it without narrowing, maybe without even checking for consistent types. (Existence in some files and non-existence in others is in a sense "[changing types](https://en.wikipedia.org/wiki/Bottom_type).")

I'm moving toward this kind of policy in awkward-array, too: the `ChunkedArray` currently performs a test to be sure that all chunks have equivalent type (raising an error if it's not), but I'm thinking that this is more trouble than it's worth—in the future, `ChunkedArrays` will always implicitly have [union type](https://en.wikipedia.org/wiki/Union_type). A collection of ROOT files collectively defining a dataset is a chunked array, so I guess the same logic should be applied in uproot.

Since I won't be able to touch this for a while (I'll be busy for the next week and a half), maybe you want to try implementing the more lax policy on your own, as a pull request? You've identified the relevant lines of code. You should be able to remove the whole test ([L176-L183](https://github.com/scikit-hep/uproot/blob/fd17acd956239798cee12b2663528d3f044e9503/uproot/tree.py#L176-L183)) as well as  all references to `oldpath` and `oldbranches` in this function. (`oldbranches` only exists to enforce the policy and `oldpath` only exists to provide a useful error message.) Then this function ([generator](https://wiki.python.org/moin/Generators), actually) wouldn't be doing much except providing a meaningful `globalentrystart`, which is useful for iterations over Pandas DataFrames and when `reportentries=True`. So the function/generator can stay.

You can get your use-case up and running with the knowledge that you won't be dealing with a forked uproot indefinitely—I agree that what you suggest is a better policy and will adopt it (simpler, less restrictive, and if a framework that uses uproot thinks it's too permissive, they can throw their own error).
