### ISSUE TITLE
Support for nested vectors

### ISSUE THREAD

**Issue by dguest** [scikit-hep/uproot#39]
This looks awesome, do you plan to support arbitrarily nested vectors? The documentation mentions support for vectors of native types but it's not clear if this extends to nested vectors.

**Comment by jpivarski** [comment]
Not yet, but that's on the roadmap.

As of this writing, uproot supports numbers/booleans, fixed-length "leaf list" of numbers/booleans, variable-length strings, and variable-length lists of numbers/booleans, including such things as `std::vector<double>`.

The next on the list are:
   * fixed-length class structures, such as `TLorentzVector`, as a Numpy record array (analogous to the way we handle "leaf list");
   * variable length class structures, such as `std::vector<TLorentzVector>`, as a `JaggedArray` whose `contents` is a Numpy record array;
   * deeper levels of nesting, such as `std::vector<std::vector<double>>`.

The issues that are really requests for these feature upgrades (like this one) are the ones I'm leaving open right now. I should probably learn how to use the GitHub "milestones" or labels for these issues.

For the third bullet in that list, I need to devise a container to put them in. I could use Python lists of namedtuples or something, but I'd like to keep everything that scales with the number of events in arrays. The [OAMap project](https://github.com/diana-hep/oamap) is intended to do just that: representing arbitrarily nested data in a format that is both columnar (one array per attribute, across all events) and directly usable in analysis (e.g. generates Python classes on the fly and is usable in compiled Numba). In the near term, I'm focusing on OAMap because it's more central to my research focus, and uproot in its current state is useful to a variety of physics analyses. (For me, uproot is intended as a backend to OAMap, rather than OAMap just being a container for a special case of data from uproot.)

**Comment by jpivarski** [comment]
With version 2.6, it's now possible to read two levels deep— `vector<vector<double>>`— as well as `vector<string>`. It's not general yet, but it covered a particular use-case.

**Comment by jpivarski** [comment]
With version 2.7, it's now possible to read variable length class structures, such as `std::vector<TLorentzVector>` and two levels of nesting for simple types, like `std::vector<std::vector<double>>`. I don't know if I can close this yet, because it's still not entirely general. Just all the cases mentioned here.

Actually, I'll close it because covering all possible types is something of an asymptotic goal.

**Comment by beojan** [comment]
It looks like it might not be possible to read two levels deep.
I get a `asgenobj(STLVector(STLVector(asdtype('>f4'))))`, but:

1. It's an `ObjectArray` of (nested) lists
2. Only the first event has a value, the rest all have an empty list
![image](https://user-images.githubusercontent.com/3727925/48358357-e3713780-e69a-11e8-84a6-050649d1257f.png)

**Comment by jpivarski** [comment]
That output doesn't mean that all events are empty except the first, though of course that's a possible value for some variable. The `...`  means "lots of values not shown" not "everything in between these two `[]` are also `[]`". It's following Numpy's convention of showing only the starting and ending entries in an array to avoid overwhelming the user with output. In general, we're dealing with large datasets.

Try

```python
[len(x) for x in btag]
```

to get the length of every object in the array.

**Comment by beojan** [comment]
I checked some subsequent events, they really are empty

On Nov 12, 2018 16:55, "Jim Pivarski" <notifications@github.com> wrote:

That output doesn't mean that all events are empty except the first, though
of course that's a possible value for some variable. The ... means "lots of
values not shown" not "everything in between these two [] are also []".
It's following Numpy's convention of showing only the starting and ending
entries in an array to avoid overwhelming the user with output. In general,
we're dealing with large datasets.

Try

[len(x) for x in btag]

to get the length of every object in the array.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/scikit-hep/uproot/issues/39#issuecomment-437932327>,
or mute
the thread

**Comment by jpivarski** [comment]
Okay, but should they not be empty? I don't know anything about the file to know that this is even a bug. It's also probably better as a **new issue**, since this issue is about adding a new `vector<vector<double>>` feature, and you're reporting an error in its implementation (I think).

**Comment by beojan** [comment]
Never mind, turn's out they're not *all* empty.

Nevertheless, is there a reason I get an `ObjectArray` of lists instead of a `JaggedArray`?

**Comment by jpivarski** [comment]
Right— that is a good point. The data elements are logically arbitrary length lists of arbitrary length lists of floats, so you'd want that to be a jagged-jagged array of floats.

However, ROOT does not encode doubly nested data the same way that it encodes singly nested data. Instead of splitting it and laying it out as columns, it serializes the objects sequentially, as though you had `splitLevel=0`. There's work being done in ROOT to replace TTree with a data container that is arbitrarily splittable/columnar (called "RForest").

When we encounter data like this in uproot, it can only be decoded as an opaque class, like the way histograms are decoded, one at a time. The technique of casting the data as a Numpy array (or, similarly, as a `JaggedArray`) is not possible because the data are not columnar. The array type for opaque data is `ObjectArray`, meaning "I don't know what this object is, but here you go" array. The deserialization is done in Python code that gets generated from the ROOT streamers in the header of the file. I literally don't know what I'm giving you— that code is being generated at runtime from the streamer instructions in your file.

The `ObjectArray` type holds the raw bytes from the file and turns them into objects on demand. In the case of nested `std::vectors`, they're turned into Python lists. This is to delay the cost of that transformation: it cannot be done in Numpy, so it's probably a factor of 100‒1000 slower than a jagged array, which can. There would be no performance benefit from turning this into a `JaggedArray(JaggedArray(float))` because you have to go through slow Python anyway, although there could be a benefit if you want to load it once and do many operations on it.

The right place to do this is in `JaggedArray.fromiter`, a constructor that builds jagged arrays from Python objects. I don't think that constructor goes two levels deep, but it ought to. I ought to expand that function to identify the depth of nesting (before you get to numbers) and make the appropriately nested jagged array. Or maybe the right thing to do is to finish writing `awkward.fromiter`, which turns arbitrary data into the appropriate jagged type— then it wouldn't be limited to jagged<sup>N</sup> of numbers. That code worked in an old version, but when I updated awkward-array to work with uproot, that part fell behind.
