### ISSUE TITLE
Accessing custom classes with uproot

### ISSUE THREAD

**Issue by zinebaly** [scikit-hep/uproot#390]
First of all, THANK YOU for you quick reply on my [stackoverflow question](https://stackoverflow.com/q/58640970/1623645) :)

Can you please tell me how uproot can handle the class features in : Evt, AAObject, TObject and t? 

My goal: open data in my root file into pandas DataFrame.

When I try to loop over data in ['Evt'] tree, I get the following error for the following branches AAObject, TObject and  t

    ValueError: cannot interpret branch b'AAObject' as a Python typein file: /myfile.root

    ValueError: cannot interpret branch b't' as a Python type in file: /myfile.root

    ValueError: cannot interpret branch b'TObject' as a Python type in file: /myfile.root

This is what I type to explore my file

    data = uproot.open("myfile.root")["E"]
    data.show() 
    data_branch_Evt['Evt']['AAObject'].basket(0)
    data_branch_Evt['t'].basket(0)`

Here is the result of data.show()

```
Evt                        TStreamerInfo              None
AAObject                   TStreamerInfo              None
TObject                    TStreamerInfo              None
fUniqueID                  TStreamerBasicType         asdtype('>u4')
fBits                      TStreamerBasicType         asdtype('>u4')

usr                        TStreamerSTL  asjagged(asdtype('>f8'), 10)
usr_names                  TStreamerSTL asgenobj(STLVector(STLString()))

id                         TStreamerBasicType         asdtype('>i4')
det_id                     TStreamerBasicType         asdtype('>i4')
mc_id                      TStreamerBasicType         asdtype('>i4')
run_id                     TStreamerBasicType         asdtype('>i4')
mc_run_id                  TStreamerBasicType         asdtype('>i4')
frame_index                TStreamerBasicType         asdtype('>i4')
trigger_mask               TStreamerBasicType         asdtype('>u8')
trigger_counter            TStreamerBasicType         asdtype('>u8')
overlays                   TStreamerBasicType         asdtype('>u4')
t                          TStreamerObjectAny         None
t.fSec                     TStreamerBasicType         asdtype('>i4')
t.fNanoSec                 TStreamerBasicType         asdtype('>i4')

hits                       TStreamerSTL               asdtype('>i4')
```

Thank you for your time and consideration 
  
[dummy.root.zip](https://github.com/scikit-hep/uproot/files/3798897/dummy.root.zip)
@tamasgal

**Comment by jpivarski** [comment]
`AAObject` is what I call a "fake branch"—it exists to help define the class structure, but it contains no data. Looking at its streamer,

```python
>>> file._context.streamerinfosmap[b"AAObject"].show()
StreamerInfo for class: AAObject, version=5, checksum=0x307c73ad
  TObject         BASE            offset=  0 type=66 Basic ROOT object
  usr_data        vector<AAny>    offset=  0 type=500 dox: storage place for any user data values (AAny)
  usr_names       vector<string>  offset=  0 type=500 dox: user data keys
```

You see the `usr_data` and `usr_names` as separate branches—they've already been split out. All the `usr_names` you wanted, for example, can be obtained through

```python
tree.array("usr_names")
```

Stepping back to your original problem, you want to load these into Pandas DataFrames—_multiple_ DataFrames because they have different cardinalities: the number of hits is not equal to the number of tracks, and Pandas does not/cannot deal with different numbers of object in a DataFrame (that's not what a DataFrame is about). So you're going to have to select branches anyway. This is how you would get the hits as a DataFrame:

```python
>>> tree.pandas.df("hits.*")
```
```
                hits.id  hits.dom_id  hits.channel_id  hits.tdc  ...  hits.pure_a  hits.type  hits.origin  hits.pattern_flags
entry subentry                                                   ...                                                         
0     0               0    806451572                8         0  ...          0.0          0            0                   0
      1               0    806451572                9         0  ...          0.0          0            0                   0
      2               0    806451572               14         0  ...          0.0          0            0                   0
      3               0    806451572               18         0  ...          0.0          0            0                   0
      4               0    806455814                8         0  ...          0.0          0            0                   0
...                 ...          ...              ...       ...  ...          ...        ...          ...                 ...
9     100             0    809524432               10         0  ...          0.0          0            0                   0
      101             0    809544058                9         0  ...          0.0          0            0                   0
      102             0    809544058               10         0  ...          0.0          0            0                   0
      103             0    809544058               11         0  ...          0.0          0            0                   0
      104             0    809544061                0         0  ...          0.0          0            0                   0

[1434 rows x 20 columns]
```

When investigating the `trks`, I found a bug—unrelated to what you were asking about, but something to fix anyway. (It was the newly added `std::vector` handling inside of a class; if that class is itself inside of a vector, the result should be a doubly jagged array, not singly jagged.) So I'm going to fix that in a PR, making it possible to read the `"trks.*"` the same way as `"hits.*"`.

**Comment by jpivarski** [comment]
PR #391.

**Comment by tamasgal** [comment]
That was quick, as always ;)

A question regarding the `tree.pandas.df("hits.*")` where you already pointed out that Pandas dataframe is not well-suited: is there a built-in/easy way to do the grouping efficiently, for example for iteration? As far as I can see the `entry` column is used to indicate which rows belong together.

When we convert such files to HDF5, we basically do the same as this `tree.pandas.df` method and also save an index table which maps the number of items and the starting index, so we can easily pick a single event without reading the whole table.

So I am wondering how you would access all the hits of the 6th event (including all parameters).

```python
In [1]: import uproot

In [2]: f = uproot.open("dummy.root")

In [3]: f["E/hits.channel_id"].array()[5]
Out[3]:
array([17, 22,  4,  3,  1,  0,  4,  6,  7,  8,  9,  3, 24, 14,  5,  6, 19,
        6, 25, 29,  3, 28,  7,  9,  2, 28, 14,  6,  3,  7, 14,  2, 11, 30,
       30, 20, 12,  9, 29, 19, 16, 15, 22, 19,  5, 23,  1, 15, 10, 26,  3,
       23,  4,  8,  8, 10, 15, 15,  1,  9], dtype=uint32)

In [4]: f["E/hits"].arrays(["channel_id", "dom_id"])[5]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-bcf125a067ed> in <module>
----> 1 f["E/hits"].arrays(["channel_id", "dom_id"])[5]

AttributeError: 'TBranchElement' object has no attribute 'arrays'
```

This is more or less similar to what @zinebaly aims for (sorry, not meant to hijack this issue, but we are colleagues ;)

**Comment by jpivarski** [comment]
If you want to get, for instance, the 6th hit of every event, your problem may not be well-suited to Pandas. However, awkward-array was made for this sort of thing. If you extract the data with `arrays` instead of `pandas.df`, you'll get unflattened jagged arrays from the awkward-array library, and you can select the 6th hit of every event like this:

```python
jagged_hits[:, 5]
```

which is now a non-jagged array. There's a lot more, so see that library's documentation.

Also, some of the data in your file is doubly nested, which ROOT does not store in the same way as a doubly jagged array. To turn the `ObjectArrays` you get out of ROOT into true doubly jagged arrays (for slicing like the above), pass then through `awkward.fromiter`. (That function is not automatically called because the awkward 0.x version of it involves a Python for loop, something to be avoided without explicitly knowing what you're getting into, performance-wise, but awkward 1.x does that loop in C++ and so uproot 4.x, which will be based on awkward 1.x, will automatically call `awkward.fromiter`. I'll be taking about that this week at CHEP.)

**Comment by tamasgal** [comment]
Ah, I was probably unclear, I meant getting the hits for the 6th event (it was not really related to pandas), which I did not yet manage to do easily, other than grabbing all sub-arrays manually (like `f["E/hits.channel_id"].array()[5]` etc.)

How do you actually obtain that `jagged_hits`? I am playing around with it and `f["E/hits"]` has no `arrays()` method since it's a `TBranchElement` and `f["E"].array("hits")` gives some weird numbers:

```
In [182]: f = uproot.open("dummy.root")

In [183]: f["E"].array("hits")
Out[183]: array([176, 125, 318, 157,  83,  60,  71,  84, 255, 105], dtype=int32)
```

Anyways, your explanations are still very enlightening! I need to dive much deeper into the docs I guess.

**Comment by jpivarski** [comment]
For example,

```python
jagged_hits_x = tree.array("hits.pos.x")
```

And work with jagged arrays for each column individually, or maybe

```python
jagged_hits = awkward.JaggedArray.zip(tree.arrays("hits.*"))
```

But the disadvantage of this is that it loads all columns whether you need them or not. There's yet another alternative:

```python
everything = tree.lazyarrays()
jagged_hits = everything["hits"]
```

The lazy arrays load what you ask for when you ask for it, but then you get less control. Some of the complaints that I've gotten about laser eyes well down to not having as much control.

Picking the 6th event, rather than the 6th hit of every event, is this:

```python
jagged_hits[5]
```

It's not quite as easy to do that in Pandas because the numbers in a DataFrame are less object-like. (There are a few different ways, and they're not super hard, but not nearly as easy as just `[5]`.)

**Comment by tamasgal** [comment]
Hm I got a bit stuck actually. Also with the `lazyarrays()` I only get flat array of integers instead of a real jagged array with the actual content:

```
In [54]: tree.lazyarrays()   # tree is f["E"]
Out[54]: <Table [<Row 0> <Row 1> <Row 2> ... <Row 7> <Row 8> <Row 9>] at 0x7f06413cd890>

In [55]: tree.lazyarrays()["hits"]
Out[55]: <ChunkedArray [176 125 318 ... 84 255 105] at 0x7f0640dd7bd0>

In [56]: tree.lazyarrays()["hits"][5]
Out[56]: 60
```

maybe I misunderstood something...

But this one works (yes, all 0 is ok, since it's not calibrated):

```
In [58]: tree = f["E"]

In [59]: tree.array("hits.pos.x")
Out[59]: <JaggedArray [[0.0 0.0 0.0 ... 0.0 0.0 0.0] [0.0 0.0 0.0 ... 0.0 0.0 0.0] [0.0 0.0 0.0 ... 0.0 0.0 0.0] ... [0.0 0.0 0.0 ... 0.0 0.0 0.0] [0.0 0.0 0.0 ... 0.0 0.0 0.0] [0.0 0.0 0.0 ... 0.0 0.0 0.0]] at 0x7f0640b3f7d0>
```

Btw. the (not recommended) zip solution fails due to a Python 3 incompatibility in `awkward` (I also tried with bytes instead of strings), I have not traced that down yet, I am still a bit sick and my brain is too slow:

```
In [60]: awkward.JaggedArray.zip(tree.arrays("hits.*"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-60-2f86d433acff> in <module>
----> 1 awkward.JaggedArray.zip(tree.arrays("hits.*"))

/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/site-packages/awkward/util.py in <lambda>(*args, **kwargs)
     46     def __get__(self, ins, typ):
     47         if ins is None:
---> 48             return lambda *args, **kwargs: self.fcn(True, typ, *args, **kwargs)
     49         else:
     50             return lambda *args, **kwargs: self.fcn(False, ins, *args, **kwargs)

/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/site-packages/awkward/array/jagged.py in zip(isclassmethod, cls_or_self, columns1, *columns2, **columns3)
   1821         if isclassmethod:
   1822             if isinstance(columns1, dict) or len(columns3) > 0:
-> 1823                 table = cls.Table.fget(None)(columns1, *columns2, **columns3)
   1824             else:
   1825                 table = cls.Table.fget(None).named("tuple", columns1, *columns2)

/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/site-packages/awkward/array/table.py in __init__(self, columns1, *columns2, **columns3)
    222                 seen.add(n)
    223
--> 224                 self[n] = x
    225
    226             if len(columns2) != 0:

/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/site-packages/awkward/array/table.py in __setitem__(self, where, what)
    640             self._contents[where] = self._util_toarray(what, self.DEFAULTTYPE)
    641
--> 642         elif self._util_isstringslice(where):
    643             what = what.unzip()
    644             if len(where) != len(what):

/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/site-packages/awkward/array/base.py in _util_isstringslice(cls, where)
    613             return True
    614         elif isinstance(where, bytes):
--> 615             raise TypeError("column selection must be str, not bytes, in Python 3")
    616         elif isinstance(where, tuple):
    617             return False

TypeError: column selection must be str, not bytes, in Python 3
```

**Comment by jpivarski** [comment]
This is because I'm trying to give suggestions on my phone without testing them. The `"hits"` in your file is both a so-called "fake branch" for structure and also happens to store the number of hits per event. That's why it's a flat array of numbers. It'll be hard for me to give suggestions non-interactively, but hopefully I'll given you enough pointers?

**Comment by tamasgal** [comment]
I understand, thanks! I'll explore and report back tomorrow.

Btw. have a nice time at CHEP in Australia! A bummer that I could not go there...

**Comment by jpivarski** [comment]
I think the original issue is done and the subsequent bug-fixes are okay, so I'm going to close this and merge the PR. If you find additional bugs, open new GitHub issues, and if you have other usage questions, ask on StackOverflow.

Thanks! (And bummer about not being able to meet up at CHEP.)
