### ISSUE TITLE
Cannot interpret std::vector<THnD*>

### ISSUE THREAD

**Issue by chernals** [scikit-hep/uproot#399]
Root output files generated by BDSIM (http://www.pp.rhul.ac.uk/bdsim/manual/) have branches containing vectors of 1d, 2d and 3d histgrams.

It appears that this cannot be interpreted as a Python type.

Can this be done ?

**Comment by jpivarski** [comment]
So each entry in the TTree has a `std::vector<TH1F>`? The sounds like something that can't be handled yet. It might be possible with some investigation. However, I have to say that it's a very odd thing to do!  `:)`

Just to be sure, uproot is saying that the `branch.interpretation` is `None`, right? That's the way it's supposed to handle unrecognized types. If it's throwing a mysterious error, that would be more of a problem.

**Comment by chernals** [comment]
Yes, it's a `TObject`, with `splitlevel=1` having three members:

```
  std::vector<TH1D*> histograms1D;
  std::vector<TH2D*> histograms2D;
  std::vector<TH3D*> histograms3D;
```

This is odd I agree :)

Yes, the interpretation is `None`, see below:

```
e._tree  # <TTree b'Event' at 0x7f84384878d0>
e._tree['Histos.']  # <TBranchElement b'Histos.' at 0x7f8438615c88>
e._tree['Histos.'].items()
# [(b'Histos.TObject', <TBranchElement b'Histos.TObject' at 0x7f8438615cf8>),
#  (b'Histos.histograms1D',
#   <TBranchElement b'Histos.histograms1D' at 0x7f8438615e10>),
#  (b'Histos.histograms2D',
#   <TBranchElement b'Histos.histograms2D' at 0x7f8438621048>),
#  (b'Histos.histograms3D',
#   <TBranchElement b'Histos.histograms3D' at 0x7f8438621240>)]
e._tree['Histos.histograms3D']  # <TBranchElement b'Histos.histograms3D' at 0x7f8438621240>
e._tree['Histos.histograms3D'].interpretation is None  # True
e._tree['Histos.histograms3D'].items()  # []
```

**Comment by chernals** [comment]
I posted an example (lightweight) file on Dropbox:

https://www.dropbox.com/s/zaapzaw0n05ajzj/output-2.root?dl=0

**Comment by jpivarski** [comment]
Actually, as members of a class it makes more sense. I was thinking of a branch containing a histogram, like the unit test file named Event.root. uproot can read that (odd as it is), so the issue here is related to them being in `vectors`.

I'll take a look on Monday, so see if it's a simple thing. Meanwhile, how essential is this for your work? (I.e. is it possible to use a work-around?)

**Comment by chernals** [comment]
Indeed, I don't have per-event histograms directly sitting on a branch, but via this vector in this split object.

Long story short, BDSIM comes with a bunch of Python tools to analyse the output in the I'm in the process of rewriting a large part of it not using the event-per-event approach of PyROOT but with uproot and numpy. This works great so far, and this here would be the last piece of the puzzle. This would also allow me to get rid of an intermediate C++ tool and do everything in Python.

However, I cannot really propose a change in the file format, as other groups heavily rely on the PyRoot analysis tools.

I would be happy to contribute to that feature/fix if you point me in some direction.

**Comment by jpivarski** [comment]
I'd like to encourage you to look into this so that more people know about uproot's internals, but this particular one might be complicated.

If, because of the `splitlevel=1`, the vector of histograms is now in a subbranch by themselves, then it's about finding a new `Interpretation` for branches of this type. It's probably

```python
uproot.asgenobj(uproot.STLVector(TH1F), branch._context, skipbytes=6)
```

where

```python
TH1F = file._context.classes[b"TH1F"]
```

generated by the ROOT file's streamers. If that doesn't work, it will require a bit more investigation (sometimes there's a one-byte "speedbump"). If you need to investigate, there's an `Interpretation` called `uproot.asdebug` that dumps raw bytes, conveniently separated by entry.

The `tests/samples/Event.root` file has an example of a branch that consists only of histograms—this would be just like that but in a `vector`. The histogram itself is very complicated, though the class generated by a streamer has a `readinto` method that takes care of that. (Print out `TH1F._pycode` to see it—all of that is auto-generated.)

If the vector of histograms is not separated into its own branch, you should be getting a `NotImplementedError` from `uproot.rootio` during the parent class's `readinto`, instead of the branch's `interpretation` being `None`. The symptom is a little different, and the solution is totally different (subject of another comment, if it's relevant).

**Comment by jpivarski** [comment]
Sorry, I missed the fact that you answered some of the questions I later asked; I was trying to diagnose via phone. I'm looking at the file now.

**Comment by jpivarski** [comment]
@chernals If you're attempting to solve this on your own, stop now—this goes deep into the internals. I've implemented it in PR #400.

In short, this type is a vector of _pointers_ to histograms, and pointers need to reference known positions in the buffer. Unfortunately, I had been passing only the bytes relevant to a given event to the `ObjectArray`, but now we need to know the global position of that slice of bytes because the references use those numbers. Therefore, I have to push these `byteoffsets` from the point where they would ordinarily be thrown away all the way through to the final `ObjectArray`.

We can read the 1D histograms because your file contains a streamer for `TH1D`. It doesn't have streamers for `TH2D` or `TH3D`, which are strictly necessary for reading objects of these types. Maybe when you made a small version of the file, it dropped these streamers? On this point, I can't do anything without those streamers.

**Comment by jpivarski** [comment]
By the way, try it out (with PR #400):

```python
    def test_issue399(self):
        t = uproot.open("tests/samples/issue399.root")["Event"]
        a = t["Histos.histograms1D"].array()
        for i in range(t.numentries):
            assert [x.title for x in a[i]] == [b"Primary Hits", b"Primary Loss", b"Energy Loss", b"Primary Hits per Element", b"Primary Loss per Element", b"Energy Loss per Element"]
```

The `x` objects in the list comprehension are histograms from event `i`.

**Comment by chernals** [comment]
Jim, this is awesome, many thanks!

It works as expected.

For an unknown reason the streamer for TH3D was not present in the file, I tested with another and it works just fine.

**Comment by chernals** [comment]
I imagine that the whole vector has to be read and unpacked for each event in the tree, right? There is no way, with the current format that I have, to access only the one of the element of the vector?

Or maybe there would be a way to pre-select only some elements (by their index) to be unpacked?

**Comment by jpivarski** [comment]
The range of bytes that have to be read and uncompressed is given by the `entrystart` and `entrystop` parameters of the `arrays` method, but these bytes are not immediately converted into Python objects. The conversion to Python actually happens when you access an item with square brackets (or as you iterate over them in a for loop). So you _are_ decoding them with random access. In fact, if you wanted the opposite—decode them only once—you'd have to fill a list with them or call `.tolist()`.

**Comment by chernals** [comment]
OK, that's for the "event index" of the array, but I was thinking about the "index in the vector" (in the `std::vector<TH1D*>`.

For example:

```
t = uproot.open("test.root")["Event"]
ar = t['Histos.histograms3D'].array()
np.stack( [v[2].values for v in a] )
```

Are all data in `v` read and instanciated as Python objects during the iteration ? Is the possible only load `v[2]`, ie. to have a `ar[:, 2]` view.

Not sure if what I'm saying is clear or make sense.

**Comment by jpivarski** [comment]
Each event of histogram must be deserialized in its entirety. You can do `ar[2]` to deserialize all 6 histograms in the third event without deserializing any other events, but you can't get just one of the histograms in an event. The data are record-oriented, not columnar, which forces sequential processing. (In principle, we could hack `uproot.STLVector` to stop reading after the first or second if it's one of the early ones you want.)

**Comment by jpivarski** [comment]
Oh, and you also can't read just a few of the bins of a histogram. It's not columnar.

**Comment by chernals** [comment]
Understood, thanks.
