### ISSUE TITLE
Installing upROOT on lxplus

### ISSUE THREAD

**Issue by ZhelunLi1995** [scikit-hep/uproot#402]
Hi!

  I have a rather basic question: what would be the easiest way of installing upROOT and pandas on lxplus? I tried the pip -install for both of them and it simply does not work out the well. 

Cheers,
Zhelun

![pandas_install](https://user-images.githubusercontent.com/32752647/68706880-ad40ef00-055e-11ea-8173-9e748398bc15.png)
![uproot_install](https://user-images.githubusercontent.com/32752647/68706881-ad40ef00-055e-11ea-8766-b07d16e3e9c9.png)

**Comment by jpivarski** [comment]
The default Python on lxplus is Python 2.7, which [has less than two months to live](https://pythonclock.org/). NumPy and Pandas both dropped support for Python 2.7 on January 1, 2019, almost a full year ago. The latest versions of these packages that _do_ support Python 2.7 are NumPy 1.16.x and Pandas 0.23.x.

You can install them in your home directory like this, though it's not recommended:

```bash
pip install --user --upgrade 'numpy<1.17' 'pandas<0.24' uproot
```

and check (possibly needing to set `PYTHONPATH`):

```python
>>> import numpy
>>> numpy.__version__
'1.16.5'
>>> import pandas
/afs/cern.ch/user/p/pivarski/.local/lib/python2.7/site-packages/pandas/core/nanops.py:39: UserWarning: The installed version of bottleneck 0.7.0 is not supported in pandas and will be not be used
The minimum supported version is 1.0.0

  ver=ver, min_ver=_MIN_BOTTLENECK_VERSION), UserWarning)
>>> pandas.__version__
u'0.23.4'
>>> import uproot
>>> uproot.__version__
'3.10.11'
```

The _recommended_ way to do it is to either get a more up-to-date Python from your collaboration's software framework or to [install Miniconda](https://docs.conda.io/en/latest/miniconda.html). I personally would go the Miniconda route—I've found it to be the easiest way to get any system up and running because it doesn't rely on (virtually) anything from the base OS distribution.

**Comment by jpivarski** [comment]
Zooming into your console output, I see that the Python version on this system is 2.6, which was ended on October 29, 2013, _more than six years ago_. You won't find any reasonable version of NumPy or Pandas that will work on Python 2.6. In fact, uproot requires at least NumPy 1.13.1 because this is the first version that allows `JaggedArrays` to be evaluated with ufuncs, and NumPy 1.13.1 does not support Python 2.6.

You _must_ use a newer version of Python; don't even try the trick I described above to make Python 2.7 work. Since you need a new Python, get a version 3 Python; 3.7 and 3.8 are current. I recommend Miniconda.

**Comment by nsmith-** [comment]
On lxplus, you have the option of using LCG, simply activate the environment:
```bash
# check your platform: CC7 shown below, for SL6 it would be "x86_64-slc6-gcc8-opt"
source /cvmfs/sft.cern.ch/lcg/views/LCG_96python3/x86_64-centos7-gcc8-opt/setup.sh
```

**Comment by henryiii** [comment]
Just to be clear, Uproot supporting Python 2.6 doesn't actually fix the fact that the default version of Python on the old lsplus6 (lsplus defaults to lsplus7 and Python 2.7 now) is wrong - you won't be able to do anything else after importing uproot, such as: installing numpy, pandas, using any modern code, etc. You'd have to manually pin old versions of all packages - why not manually pin uproot too, then? So uproot is simply "first point of failure" here. I think we should declare 2.6 is completely unsupported and move on, possibly with a "final version to support 2.6" note, and a `sys.version_info > (2, 6)` check for a better error message.

**Comment by henryiii** [comment]
(Obviously I'm referring to Uproot4, but this seems to be the issue keeping Python 2.7 syntax out of Uproot4)
