### ISSUE TITLE
Cannot interpret std::string

### ISSUE THREAD

**Issue by rtesse** [scikit-hep/uproot#404]
I'm trying to read a branch, no issue with all the `double` elements but I cannot read `std::string` elements.

See the sample file : https://www.dropbox.com/s/nvqb3tqa0zbn5mk/survey.root?dl=0

```
import uproot
uproot.open("survey.root")['Beam']['Beam.GMAD::BeamBase.beamParticleName'].array()
```

raising `ValueError: cannot interpret branch b'Beam.GMAD::BeamBase.beamParticleName' as a Python type in file: survey.root`.

**Comment by jpivarski** [comment]
Thanks! Actually, it had nothing to do with not being able to read strings (I see that it generated the right code for reading strings from an unsplit version of the object); it's that the object has been split but I didn't manage to pass the information down about which branch corresponds to which field, so that it knows that `'Beam.GMAD::BeamBase.beamParticleName'` is a string, for instance. (The information is not actually attached to the branch; it has to be inferred by walking down the nested branches and the class structure at the same time. Somehow, that got lost and I'm going to figure out where.)

**Comment by jpivarski** [comment]
PR #405; the problem was that when I was walking from branches to sub-branches in the TTree and simultaneously walking down classes to class members in the streamers, there was an extra branch associated with the fact that members like `beamParticleName` came from a base class, `GMAD::BeamBase`. Instead of searching the direct children of a branch, I now recursively search all of the branch's descendants and thus can find the right class member for each branch and associate it with a type.

**Comment by chernals** [comment]
Perfect, thanks.
