### ISSUE TITLE
Wrong assignment of type JaggedArray

### ISSUE THREAD

**Issue by lgiommi** [scikit-hep/uproot#410]
Hi, I am using uproot in my project and I find a wrong behaviour of uproot.
I am using this root file (/afs/cern.ch/work/l/lugiommi/public/sgn.root) and there is something strange in assigning the type of the branch triggerBit. It is strange because each element of this branch is an array of dimension 23 so it should not be assigned JaggedArray as uproot does, right?

```
import uproot
file=uproot.open("sgn.root”)
array=file["boostedAk8/events"].array("triggerBit")
array[array.counts!=23]
<JaggedArray [] at 0x00012bd66990>

file["boostedAk8/events"].show()
triggerBit                 (no streamer)              asjagged(asdtype('bool'), 10)
```

Thanks,
Luca

**Comment by jpivarski** [comment]
It's not wrong: this is what was actually stored in the ROOT file (on the C++ side, it really is a `std::vector`, despite the fact that every entry has the same number of trigger bits).

```python
>>> import uproot, numpy
>>> f = uproot.open("issue410.root")
>>> t = f["boostedAk8/events"]

>>> t["triggerBit"]._fClassName
b'vector<bool>'
```

Since the data are _in fact_ regular, you can turn the `JaggedArray` into a `numpy.ndarray` with the `regular` method:

```python
>>> t.array("triggerBit").regular()
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])
```

That method fails at runtime if the `JaggedArray` is not in fact regular.
