### ISSUE TITLE
Investigating basket sizes before creating lazyarrays to adjust the cache size

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot#419]
We use `lazyarray`s for many of our nested data structures and they work very nicely. However, we sometimes hit a file where the (default) cache size which we use as the `basketcache` is too small, so we get the error `ValueError: value too large` from `cachetools`.

Is there any recommended way to skim through the ROOT structures and figure out the maximum basket size so we can adjust the `basketcache` size beforehand? Quickly iterating through the the trees/branches and checking for `dtype`s and `len`ghts would provide the numbers but I'd like to avoid any unnecessary I/O to keep the latency low.

If I find some time I'd also would like to follow this up with a PR if I find time to add a `console_script` to the `setup.py` similar to [ptdump](https://www.pytables.org/usersguide/utilities.html) in PyTables which shows the tree structures and some relevant sizes.

Ping @zinebaly

**Comment by jpivarski** [comment]
You can!

https://uproot.readthedocs.io/en/latest/ttree-handling.html#uproot.tree.TBranchMethods.uncompressedbytes

This method will tell you the number of bytes that a basket has after decompression (relevant for setting the `basketcache` size). You can get a `TBranch` object via square brackets on the `TTree` and the number of baskets for that branch using `numbaskets`.

This method doesn't read the baskets, but it does have to read each basket's header to get the uncompressed sizes, and those are located all over the file. If you're content with uncompressed sizes, the uncompressed version of this method doesn't require any basket headers.

The reason that basket headers matter is that reading even a single byte from an uncached region of the file will cause a whole page to be read. This is not such a big deal with local files, where the operating system handles that and the pages are 4 kB each, but for remote files, we use larger pages (1 MB, I think?) because establishing connections can be very expensive relative to downloading data.

The `keycache` stores these basket headers if you access them multiple times. You can use a plain dict for this cache and the keys won't ever get evicted. (They're not very big.)

**Comment by tamasgal** [comment]
No idea how I missed that `uncompressedbytes` thing... thanks Jim, that's perfect 😉 

I'll play around with it and hopefully I can come up with a tiny helpful command line utility.

**Comment by tamasgal** [comment]
Unfortunately the fact that we have so many "corrupt" ROOT files makes it more or less impossible to create something reliable. For many branches I get an error when trying to access `uncompressedbytes`:

`ValueError: entries in recovered baskets (offsets [0]) don't add up to total number of entries (10)`

But that's not an uproot issue of course.

It's interesting to see that ROOT somehow silently manages to read these files and doesn't give any errors. I think it should at least give a warning.

**Comment by sbinet** [comment]
FYI, there's already a `ptdump` equivalent:
- [go-hep.org/x/hep/groot/cmd/root-dump](go-hep.org/x/hep/groot/cmd/root-dump)

(and also `npy2root`, `root2npy`, `arrow2root`, root2arrow`...)

**Comment by tamasgal** [comment]
Thanks @sbinet, I was thinking of one written using the `uproot` package, but that's already a starting point.

**Comment by jpivarski** [comment]
Actually, is a misleading error message: you get it when uproot tries to find baskets for branches that have no data. I need to fix it by putting in a check to only call `recover` on branches with an `interpretation`.

`recover` is a work-around for files that were not explicitly closed at the end of writing. The symptom is that some of the baskets are in unusual places and so the number of entries in normal baskets doesn't add up to the number of entries in the branch's metadata. However, non-data branches have zero baskets (before and after "recovery") yet report the same number of entries as the TTree, so this check for the success of `recover` is naive.

It is not an error in the ROOT files.

We've run into this a few times and I keep forgetting to fix it because it's never a blocker for anybody's work. For instance, in your case, you can put a check in your test for `branch.interpretation == None` to skip the branches that would raise this exception.

Can you post an issue to remind me to fix it when I get to a computer? Thanks!
