### ISSUE TITLE
Cannot read branch data

### ISSUE THREAD

**Issue by Editing42** [scikit-hep/uproot#429]
My root file have branch data_ana_kk but it appears that this branch cannot be interpreted as a Python type.
```
>>> f.keys()
[b'data_tr;1']
>>> f["data_tr"].show()
data_ana_kk                (no streamer)              None
mctoptype                  (no streamer)              asdtype('>i4')
mctopnum                   (no streamer)              asdtype('>i4')
mctopdata                  (no streamer)              asdtype("('>i4', (192,))")
mctopmd5                   (no streamer)              asdtype("('>i4', (4,))")
>>> f["data_tr"]["data_ana_kk"].array()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/uproot/tree.py", line 1348, in array
    interpretation = self._normalize_interpretation(interpretation, awkward)
  File "/usr/lib/python3.8/site-packages/uproot/tree.py", line 1091, in _normalize_interpretation
    raise ValueError("cannot interpret branch {0} as a Python type\n   in file: {1}".format(repr(self.name), self._context.sourcepath))
ValueError: cannot interpret branch b'data_ana_kk' as a Python type
   in file: data_ana_001.root
```
The root file is here(https://github.com/Editing42/rootfile/blob/master/data_ana_001.root)

**Comment by jpivarski** [comment]
This branch is a "leaf-list" with 27 leaves and, apparently, four extra bytes of padding. The algorithm that assigns interpretations doesn't assume that your data will need to be padded (I don't know what that algorithm would be), and that's why it fails. Here's how to get it to work, though it's a bit long-winded.

First, I'm going to load your data like this:

```python
import uproot
file = uproot.open("issue429.root")
tree = file["data_tr"]
branch = tree["data_ana_kk"]
```

The `branch` has many leaves, which we can see in the private member `_fLeaves` (defined via ROOT's streamers).

```python
>>> branch._fLeaves
[<TLeafF b'Mphi' at 0x793f461e4a90>, <TLeafF b'MKp1Km1' at 0x793f461e4ac8>, <TLeafF b'MKp2Km2' at 0x793f50c842b0>, <TLeafF b'MKp1Km2' at 0x793f46135630>, <TLeafF b'MKp2Km1' at 0x793f461351d0>, <TLeafF b'MphiKp2' at 0x793f461352b0>, <TLeafF b'MphiKm2' at 0x793f46135320>, <TLeafF b'M2phiKp2' at 0x793f46135358>, <TLeafF b'M2phiKm2' at 0x793f46135400>, <TLeafF b'MphiK' at 0x793f461353c8>, <TLeafF b'Chi2_4c' at 0x793f46135550>, <TLeafF b'QKp1' at 0x793f46135588>, <TLeafF b'QKm1' at 0x793f461355f8>, <TLeafF b'QKp2' at 0x793f46135668>, <TLeafF b'QKm2' at 0x793f461356d8>, <TLeafF b'QKp1Km1' at 0x793f46135710>, <TLeafF b'QKp2Km2' at 0x793f46135748>, <TLeafF b'MomKp1' at 0x793f46135780>, <TLeafF b'MomKm1' at 0x793f461357b8>, <TLeafF b'MomKp2' at 0x793f461357f0>, <TLeafF b'MomKm2' at 0x793f46135828>, <TLeafF b'MKp1Km1Kp2' at 0x793f46135860>, <TLeafF b'MKp1Km1Km2' at 0x793f46135898>, <TLeafF b'MKp1Kp2Km2' at 0x793f461358d0>, <TLeafF b'MKm1Kp2Km2' at 0x793f46135908>, <TLeafF b'weight' at 0x793f46135940>, <TLeafI b'itopo' at 0x793f461359b0>]
```

All of these leaves are `TLeafF` (32-bit floating point number) and `TLeafI` (32-bit integer), which are easy to interpret. The interpretation should have been this list of 2-tuples, which NumPy recognizes as a [structured array type](https://docs.scipy.org/doc/numpy/user/basics.rec.html):

```python
>>> dtype = [(x._fName.decode("utf-8"), "float32" if type(x).__name__ == "TLeafF" else "int32") for x in branch._fLeaves]
>>> dtype
[('Mphi', 'float32'), ('MKp1Km1', 'float32'), ('MKp2Km2', 'float32'), ('MKp1Km2', 'float32'), ('MKp2Km1', 'float32'), ('MphiKp2', 'float32'), ('MphiKm2', 'float32'), ('M2phiKp2', 'float32'), ('M2phiKm2', 'float32'), ('MphiK', 'float32'), ('Chi2_4c', 'float32'), ('QKp1', 'float32'), ('QKm1', 'float32'), ('QKp2', 'float32'), ('QKm2', 'float32'), ('QKp1Km1', 'float32'), ('QKp2Km2', 'float32'), ('MomKp1', 'float32'), ('MomKm1', 'float32'), ('MomKp2', 'float32'), ('MomKm2', 'float32'), ('MKp1Km1Kp2', 'float32'), ('MKp1Km1Km2', 'float32'), ('MKp1Kp2Km2', 'float32'), ('MKm1Kp2Km2', 'float32'), ('weight', 'float32'), ('itopo', 'int32')]
```

Now we _should_ be able to just provide this `dtype` as a new interpretation (through `uproot.asdtype`), but it doesn't work because the size is wrong.

```python
>>> array = branch.array(uproot.asdtype(dtype))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/uproot/uproot/tree.py", line 1381, in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
  File "/home/jpivarski/irishep/uproot/uproot/tree.py", line 1336, in _basket_itemoffset
    numitems = interpretation.numitems(key.border, self.basket_numentries(i))
  File "/home/jpivarski/irishep/uproot/uproot/interp/numerical.py", line 152, in numitems
    assert remainder == 0
AssertionError
```

The size is wrong? How can that be? The leaves told us exactly what the types ought to be. Well, I did some digging, and your data has an extra 4 bytes of padding (all `\xff`).

```python
>>> array = branch.array(uproot.asdtype(dtype + [("padding", "S4")]))
```

This `array` has all the normal fields

```python
>>> array["Mphi"]
array([1.0161009, 1.0152352, 1.0235338, ..., 1.0189617, 1.0177454,
       1.019102 ], dtype=float32)
>>> array["MKp1Km1"]
array([1.0161009, 1.0152352, 1.0235338, ..., 1.0189617, 1.0177454,
       1.019102 ], dtype=float32)
>>> array["weight"]
array([2.9058652, 2.936209 , 3.1178842, ..., 2.8489256, 3.0074883,
       3.0073295], dtype=float32)
>>> array["itopo"]
array([1065353216, 1065353216, 1065353216, ..., 1065353216, 1065353216,
       1065353216], dtype=int32)
```

with one extra: the padding.

```python
>>> array["padding"]
array([b'\xff\xff\xff\xff', b'\xff\xff\xff\xff', b'\xff\xff\xff\xff', ...,
       b'\xff\xff\xff\xff', b'\xff\xff\xff\xff', b'\xff\xff\xff\xff'],
      dtype='|S4')
>>> (array["padding"] == b"\xff\xff\xff\xff").all()
True
```

If I understood how to predict how much padding you should see, I could add it to the standard algorithm that assigns interpretations, so your data would just work.

**Comment by Editing42** [comment]
Thanks for your reply.

The cause of this padding array should be [c structure padding](https://fresh2refresh.com/c-programming/c-structure-padding/). I don't know how to predict how much padding would generate, but I can try to avoid c structure padding.

Hope you can find a way to predict it.

**Comment by Editing42** [comment]
I find [this discussion](https://root-forum.cern.ch/t/ttree-with-c-struct/13469) about c struct in root forum, which could avoid this padding problem.

**Comment by jpivarski** [comment]
That's a recommendation to avoid creating ROOT files with padding issues, and the final recommendation is to define struct fields in order of decreasing size. All of your fields have exactly the same size.

It's also possible that NumPy can be instructed to use a particular padding rule. The thing that worries me is the "compiler dependence." We can't know which compiler produced a particular ROOT file, and since uproot is in Python, we can't even inherit it from a compiler (you might not even have a compiler on your computer).

**Comment by Editing42** [comment]
Numpy.dtype has this parameter:

>align : bool, optional
>Add padding to the fields to match what a C compiler would output for a similar C-struct. Can be True only if obj is a dictionary or a comma-separated string. If a struct dtype is being created, this also sets a sticky alignment flag isalignedstruct.

Can this be disabled to avoid padding?

**Comment by jpivarski** [comment]
Your problem is not one of avoiding padding: there's padding in the ROOT file, so you need padding in the NumPy representation (which isn't there by default).

This is the parameter I was thinking of. Turning it on could enable what we want: it could add the extra 4 bytes according to the appropriate rules, whatever those are, although I don't know how it would pick the right rules of they are compiler-dependent.

In the description of the parameter, it says that the dtype has to be passed as a string, but we're passing it as a list of 2-tuples. I think you can just put quotes around that list, but I'm not sure.

In my example, I suggested

```python
uproot.asdtype( ...dtype... )
```

but you can have more control over it if you pass it as

```python
uproot.asdtype(numpy.dtype( ...dtype... ))
```

If this parameter is an argument to the `numpy.dtype` constructor, then constricting it explicitly gives you a place to put the constructor.

**Comment by jpivarski** [comment]
I'm assuming that I can close this now. Let me know if I'm wrong!
