### ISSUE TITLE
Problem with iterate function

### ISSUE THREAD

**Issue by lgiommi** [scikit-hep/uproot#44]
Hi, I’m using uproot to read some root files and I have some problem when I use uproot.iterate function. I wrote this script to explain you the problem.
```
from math import *
import numpy
import uproot
import sys
import argparse

parser=argparse.ArgumentParser(prog='PROG', description='inspect root files')
parser.add_argument("--fin", action="store",
            dest="fin", default="", help="Input ROOT file")
parser.add_argument("--branch", action="store",
            dest="branch", default="Events", help="Input ROOT file branch (default Events)")
parser.add_argument("--branches", action="store",
            dest="branches", default=[], help="Comma separated list of branches to read (default all)")
parser.add_argument("--fout", action="store",
            dest="fout", default="", help="Output file name to write")
args = parser.parse_args()
list_branches = args.branches.split(',') if args.branches else []

outputfile = open(args.fout, "w")
iterator = uproot.iterate(args.fin, args.branch, 1000,
     branches=list_branches, outputtype=dict)
for block in iterator:
    outputfile.write("%s \n" %block)
outputfile.close() 
```

If I run this 
`python try_uproot.py --fin /afs/cern.ch/work/b/bonacor/public/double.root --fout output --branches event`
I can see that the last two blocks of the iterator are empty and the filling stops in the 16th iteration (so it seems that there are less than 16000 events). This is not correct because the root file contain 18000 events for branch “event”. If I change the root file and I run this
`python try_uproot.py --fin=/afs/cern.ch/work/b/bonacor/public/small10kevts.root --fout=output --branch events --branches=evtNo`
the output file shows that the elements in the branch evtNo are 7981 but in the root file we can see that they are 10000. There is something wrong in uproot? This happens of course even if I select different branches.
On the contrary if I run
`python try_uproot.py --fin /afs/cern.ch/user/v/valya/public/nano-RelValTTBar.root --fout output --branches event`
that is similar to the root file of the first example but with less events, that are 9000 (I obtained double.root copying nano-RelValTTBar.root two times, so it has 18000 events), the output file shows that all the events are read with iterate function.
So, there is maybe a problem of full allocated memory when I run iterate function? Because when I try to read big root file (also bigger than those of the previous examples), it stops inexplicably in reading.

Thank you
Luca

@vkuznet

**Comment by jpivarski** [comment]
I've been working with the first file, `double.root`, and recognize a problem I've seen before. The short story is that your ROOT-file writer is terminating before fully writing out the file. When a TBasket is finished being written, it is made into an independent object in the file, addressed by a TKey, much like histograms and trees. However, if a ROOT process terminates before this can happen, the partly-filled basket data can be found embedded within the TTree (different location and format from the usual case). Although I'd be tempted to say it was "incompletely written" or "improperly written," this state is not considered a bug by the ROOT developers— it is considered the responsibility of readers to be able to interpret this data.

I have code to interpret files of this type: you do `branch.recover()` for a single branch or `tree.recover()` for all branches. In your example,

```python
>>> import uproot
>>> t = uproot.open("~/storage/data/issue44/double.root")["Events"]
>>> for (array,) in t.iterate("event", 1000, outputtype=tuple):
...     print len(array)
... 
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
960
0
0
```

The last two iterations are empty because the iteration steps are set by the tree's number of entries, which is 18000:
```python
>>> t.numentries                # TTree says 18000
18000
>>> t["event"].numentries       # TBranch independently agrees
18000
```
but the entries in the baskets themselves fall short of that.
```python
>>> t["event"].numbaskets
4
>>> t["event"].basket_numentries(0)
3990
>>> t["event"].basket_numentries(1)
3990
>>> t["event"].basket_numentries(2)
3990
>>> t["event"].basket_numentries(3)
3990
>>> 3990 + 3990 + 3990 + 3990
15960
# You had 15 iterations with 1000 events, 1 with 960, and the rest had 0, hence 15960.
```

When you call the `recover()` function, we find another basket, "stillborn" inside the TTree, and this has the missing entries:
```python
>>> t["event"].recover()
>>> t["event"].numbaskets
5
>>> t["event"].basket_numentries(4)
2040
>>> 3990 + 3990 + 3990 + 3990 + 2040
18000
```

Now the iterator finds all of them:
```python
>>> for (array,) in t.iterate("event", 1000, outputtype=tuple):
...     print len(array)
... 
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000   # yay!
```

Why am I being conservative and making you type `recover()`? Because I don't fully understand this state yet. I wouldn't want to automatically `recover()` everything and introduce new problems.

Indeed, `double.root` has something I need to learn: recovering the whole TTree raises an exception about improperly formatted file contents:
```python
>>> t.recover()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uproot/tree.py", line 474, in recover
    branch.recover()
  File "uproot/tree.py", line 1267, in recover
    recovered = [x for x in uproot.rootio.TObjArray.read(self._source, self.fBaskets._cursor, self._context, asclass=TBranchMethods._RecoveredTBasket) if x is not None]
  File "uproot/rootio.py", line 1067, in read
    out = cls._readinto(out, source, cursor, context, asclass=asclass)
  File "uproot/rootio.py", line 1078, in _readinto
    _endcheck(start, cursor, cnt)
  File "uproot/rootio.py", line 356, in _endcheck
    raise ValueError("object has {0} bytes; expected {1}".format(observed, cnt))
ValueError: object has 14793 bytes; expected 20161
```

You should be able to solve your immediate problem by fixing the file-writing process, usually by explicitly `TTree::Write()` and `TFile::Close()` before terminating the process. Meanwhile, I'll try to figure out what's going on in this file. If it's formatted well enough for ROOT to read it, uproot needs to be able to read it, too.

**Comment by lgiommi** [comment]
Thank you very much. I broadly understand what's going on and I can confirm that if I add the `TTree::Write()` function all the entries are read.  Both the files of the example that I mentioned before were cloned from original root files using my script and I didn't know that without Write function there would be this problem.

**Comment by jpivarski** [comment]
Good timing: I just finished fixing `tree.recover()` for your case! It will be released as 2.5.18.

**Comment by lgiommi** [comment]
Ok perfect. Many thanks for the prompt reply

**Comment by jpivarski** [comment]
Your original files were very useful. They were the first examples I'd seen of TTrees requiring recovery with offset data (i.e. JaggedArrays as opposed to plain arrays), and I had misunderstood how this data would be structured.

Making the files with a final `TTree::Write` is a good policy, but if you ever happen to make a file without this function call, uproot 2.5.18 should be able to read them. (Will be released soon— I'm having trouble with Travis.) Since you're reading files with `uproot.iterate`, which doesn't let you see the `TTree` objects to call `recover()` on them, I've added a `recover=False`/`True` keyword to the `uproot.iterate` function. You could add `recover=True` to your original `uproot.iterate` call and you'd see all 18000 events in all branches.

Pretty soon, I'll probably make "recovery" automatic for TBranches that have a larger `numentries` than the sum of their TBaskets. I just needed to see examples like this one to get comfortable with my understanding of their layout.

**Comment by jpivarski** [comment]
I'm comfortable enough with the `recover()` function that it is now called automatically on affected branches: https://github.com/scikit-hep/uproot/releases/tag/2.6.1. This function had never been publicized, but now that it's redundant, it has been renamed to `_recover()` (and you'll probably never call it directly).
