### ISSUE TITLE
Reading tree with TVector3 branch into Pandas DataFrame

### ISSUE THREAD

**Issue by ast0815** [scikit-hep/uproot#443]
Hello,

I am trying to read a TTree with a TVector3 branch, and ultimately would like to have the data as a Pandas DataFrame. Unfortunately I get this error when trying to do so:

```
ValueError: cannot interpret branch b'hitPosExtrap' as a Python type
```

Here is an excerpt of my code:

```
tree_name = 'muonDataTree'
with uproot.open(filelist[0]) as f:
    print(f[tree_name].array('hitPosExtrap'))
```

I uploaded a file where this happens here: 

http://www-pnp.physics.ox.ac.uk/~koch/TVector3_error.root

**Comment by jpivarski** [comment]
Oh, it's because the `TVector3` has been split into three sub-branches, one for each component.

```python
f[tree_name]["hitPosExtrap"]["fX"].array()
f[tree_name]["hitPosExtrap"]["fY"].array()
f[tree_name]["hitPosExtrap"]["fZ"].array()
```

should work, though the file you've posted seems to have zero hits (also in `"hitPosRaw"`). If, in your larger file, you find that the hits are okay, then close this issue and self-answer on StackOverflow.

Note that calling `f[tree_name]` each time will re-read the TTree metadata; you may want to put it in a variable:

```python
t = f[file_name]
...
```

**Comment by ast0815** [comment]
Ah, I see. It seems like I can  access the arrays like that. Thanks. Is there also a way to tell `uproot.pandas.iterate` to look in a sub-branch? I have tried something like `uproot.pandas.iterate(['hitPosExtrap.fX'])` before, but that did not work and I could not find a way to do this in the README.

**Comment by jpivarski** [comment]
My goal at the beginning of uproot was to provide users with a view of what "is" in the file, rather than what the data "mean." It's therefore a bit low-level: ROOT TTrees consist of branches, some of which exist to demark structure (like `"hitPosExtrap"`) and some of which contain data. ROOT's traditional view is that some sets of branches, collectively, represent C++ objects. Two files might represent the same `TVector3` objects, but one is "split," putting components into separate subbranches, and the other is "unsplit," putting all the data serially in a single branch. ROOT would present those two files as the same, but uproot presents them differently, as you've seen.

A practical reason why uproot isn't more high-level is that I don't know all the rules for translating sets of branches into C++ objects. A software-philosophy reason is to do as little magic as possible, because when something goes wrong or a user wants something unusual, those users would have to work against the magic. That is, you definitely don't want me to do the branches → objects translation wrong, and you might not want me to do it at all.

-------------------

You _could_ do it all in one command, like an explicit `uproot.pandas.iterate(["hitPosExtrap.fX", "hitPosExtrap.fY", "hitPosExtrap.fZ"])`, but the subbranches would have to be named differently. The TTree's search for branches by string name is a recursive search, but you have several branches with the same names: `"fX"` inside of `"hitPosExtrap"` and also `"fX"` inside of `"hitPosRaw"`. (Get a bird's eye view with `tree.show()`.)

There's a way to get ROOT to name the subbranches distinctly, `"hitPosExtrap.fX"` and `"hitPosRaw.fX"`—I think the rule is to name the branch with a `"."` at the end. [Here is a roottalk from 2004](https://root.cern.ch/root/roottalk/roottalk04/2592.html) describing that rule.

-------------------

Alternatively, we could add a rule to uproot to let the user express subbranches explicitly, possibly with `"/"` because I think that character is not allowed in branch names. The ROOTDirectory class already parses the string it's given for subdirectories with `"/"` (and also cycle numbers with `";"`):

https://github.com/scikit-hep/uproot/blob/master/uproot/rootio.py#L333-L363

Similar functionality would have to be added to TTree:

https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L374-L383

and TBranch:

https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L981-L986

It's not a huge project, and I'd be open to helping volunteers.  `:)`

**Comment by ast0815** [comment]
Yeah, I think it would be quite useful to have the possibility of explicitly referring to subbranches in `iterate` (and other places where it is applicable). I might take a look and see how hard it is to implement.

In the mean time, what would you suggest to do to get these subbranches into a Pandas DataFrame, iterating over multiple files? Get the arrays from the subbranch as shown above and then building the DataFrame by hand?

**Comment by jpivarski** [comment]
Due to this inability to unambiguously ask for the branches you want in one line, you'd have to iterate and build the Pandas DataFrames manually, yes. I didn't consider the `"/"`-based disambiguation before because most files have already been generated with the dot thing (that's why you find examples of `"hisPosExtrap.fX"` syntax elsewhere) and I didn't realize that this small inconvenience of having to write

```python
f[tree_name]["hitPosExtrap"]["fX"]
```

instead of

```python
f[tree_name]["hitPosExtrap/fX"]
```

becomes a big inconvenience when you want to put a lot of branches together in a Pandas frame, and you want to iterate over Pandas frames automatically. The first syntax doesn't let you write a lot of branch names in a list to pass to a do-everything function like `uproot.pandas.iterate`, but the second syntax does.

Incidentally, if TTrees and TBranches have the `"/"` syntax, it would accidentally become possible to do this:

```python
f["tree_name/hitPosExtrap/fX"]
```

"Accidentally" in the sense that it wasn't intended and I didn't envision people doing that (because doing it repeatedly would repeatedly read the TTree metadata), but it would work and would be pretty slick in some situations.

Should I leave this issue open for implementing the `"/"` syntax? There might be other takers out there who want to learn more about uproot internals by trying it.

**Comment by ast0815** [comment]
It's up to you. I guess it might as well go into a separate issue to keep things clean.

**Comment by jpivarski** [comment]
That, or the title should change. Maybe yes, make it a new issue. (You can copy my three links to the model and the two functions that would change.)
