### ISSUE TITLE
Extend branch lookup to match subbranches using `/` as separator

### ISSUE THREAD

**Issue by ast0815** [scikit-hep/uproot#444]
As discussed in #443, it would be convenient to specify subbranches in the `iterate` functions. This would have to be implemented in a couple of places:

https://github.com/scikit-hep/uproot/blob/master/uproot/rootio.py#L333-L363

https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L374-L383

https://github.com/scikit-hep/uproot/blob/master/uproot/tree.py#L981-L986

**Comment by jpivarski** [comment]
The third part of [this comment](https://github.com/scikit-hep/uproot/issues/443#issuecomment-578831373).

**Comment by ast0815** [comment]
So, I finally got around to look into this. It seems like the `ROOTDirectory.get` method already supports arbitrary '/' depths. So no more work needed there, it seems.

I got a few questions about the intended behaviour for the `TTree` objects though:

1)  Should `tree.iterkeys(recursive=True)` return the subkeys with the '/' separators or just the raw subkeys?
2)  Should the `name` properties of the branches returned by `tree.itervalues(recursive=True)` be modified to include the '/' or remain raw?
3)  Same questions for `tree.iteritems(recursive=True)`.
4) What should happen when `get` is called with `recursive=True` and a name containing a '/'?
    Or with '/' and `resursive=False` for that matter.
5) Should the default value of get really be `recursive=True`?

If it were up to me, I would probably say: modify the values of `iterkeys` and the key part of `iteritems` to contain the full path, but leave the `name` property of the returned values alone. This way each subbranch always gets a unique key as seen from the particular top-level tree, but the branches themselves remain untouched.

I also would remove the `recursive` argument from get and have it only look at exact matches with the `iterkeys` (It can decide whether to use `iterkeys(recursive=True/False` by checking whether there is a `/` in the requested name). This way there are no surprises and you can simply use `get` or `__getitem__` with the return values of `keys` or `allkeys` without thinking about it too much.

I'm not 100% sure, but this might also solve #447 in one swoop.

Thoughts?

**Comment by jpivarski** [comment]
Your ideas sound good to me:

   * `iterkeys(recursive="/")` and `iteritems(recursive="/")` should yield keys that have the parent names prepended with slashes; that is, "fully qualified" keys,
   * these fully qualified keys should be usable in `get` (and therefore `__getitem__`), and
   * the `value.name` should _not_ be affected. Iterating over the keys and/or values should not cause data to change.

However, the default behavior of `get` should not change—there are many users out there whose branches might be deeply nested and they either don't know or haven't thought about it in a while, and reducing the set of things this function returns would break their scripts in ways that could be hard to predict.

Uproot 4 will have some breaking changes, so that's a time (April) when we can contemplate that, but still I think that `get` should be recursive by default. It was surprising in your case, but the opposite would be surprising in other people's cases (as is evidenced by the fact that it took this long for your case to bubble up). Most ROOT files are constructed with nested branches having names like `"outer.middle.inner"` and requiring owners of these files to do `"outer/outer.middle/outer.middle.inner"` would be an unwelcome surprise. Another alternative would be to make it smart enough to see if there are dots and use that to make a choice, but simplicity is better than interfaces that second-guess your intention.

How about the following, though? If the string passed to `get` has any slashes, the text between the slashes is not searched recursively: they should each explicitly name a branch. If the string has no slashes, then the current default of searching for that token recursively is used. This is a little bit "smart" but I think that's okay because anyone deliberately putting a slash in their search string wants to name the subbranch levels explicitly. It would also introduce a new idiom to choose between recursive and non-recursive in `__getitem__`: one can say `"branchname"` for recursive and `"/branchname"` or `"branchname/"` for non-recursive.

One last thing: since `/` is going to be accepted by `get`, the `iterkeys` and `iteritems` shouldn't be allowed to produce any delimiter other than `/`. There's no point in having the freedom to produce keys that you won't be able to use in `get`, and we don't want to make `get` configurable. Let's just say that `/` is the delimiter. I think you do need to distinguish between `iterkeys(recursive=True)` and `iterkeys(recursive="/")` because one yields branch names and the other yields fully qualified branch paths. You could even pass that `"/"` through all the internal code as an arbitrary delimiter, but restrict it to only `"/"` at the entry point, so that it might later be flexible, but for now, we're only allowing the one value.

**Comment by ast0815** [comment]
Ok, so the default behaviour of `get` and `allkeys` etc. will remain `recursive = True` for now and I'll add a `recursive='/'` option to the `iterkeys` and similar methods. In case of a name containing '/', `get` will ignore the `recursive` argument and look for the exact subbranch.

Am I correct in assuming that all method documentation is to be updated in `_help.py`? Out of curiosity, what is the intention behind separating the docstrings from the source like this?

**Comment by jpivarski** [comment]
Everything you said is right.

The reason the docstrings are separated into their own file is because most of them have significant overlap—the same variable names with the same meanings—so I wanted to use variable substitution to ensure consistency. Docstrings inferred from position (the first line in a function or class) must be constant literals—they can't be programmed. I had two choices: assign them after each class definition, a non-standard place sprinkled throughout all the files, or assign them all in one place, non-standard but universal. It seemed to me that the latter is the clearest of those two options.
