### ISSUE TITLE
Failed to read TClonesArray

### ISSUE THREAD

**Issue by antoniomdk** [scikit-hep/uproot#451]
Hello everyone,  I've been given a ROOT file and I need to extract some data to feed a model. I'm new to ROOT (CS background) and I can't get my head around this. This error appears when trying to convert a branch into an array:

> In[50]: branch['fStations']['fStations.fPMTs'].array(entrystop=1)
Out[50]: <ObjectArray [[<Undefined (failed to read 'TClonesArray' version 65535) at 0x0001ade87510>, ...]

> In[52]: b['fStations']['fStations.fPMTs'].interpretation
Out[52]: asgenobj(SimpleArray(TClonesArray))

I'm not sure if it's my bad or just that the library doesn't support TClonesArray type.

I'd appreciate any help.

Thank you so much!

**Comment by jpivarski** [comment]
I think we support TClonesArray if it is split (written with `splitLevel=99` or otherwise larger than `2`), but not if it's unsplit, as in this case (`asgenobj`).

As for the usefulness of the error message—it's _attempting_ to read it because it found the streamer defining the byte-layout of your version of the TClonesArray class and it's attempting to use that information in an automated way. However, some of the basic ROOT types are not entirely regular, at least not in a way that we've fully solved the problem of automatic deserialization. (There might be a piece of information that makes the deserialization procedure derive directly from the streamer, but I don't know it.) For simpler, less central-to-the-ROOT framework classes, our interpretation of the streamer data works well.

Usually, the reason you want to make a TClonesArray, as opposed to a TObjArray, is so that the data can be split for efficiency, anyway. Alternatively, plain arrays and `std::vectors` are also quite regular and easy to deserialize (then it might depend on what's _in_ the container).

**Comment by antoniomdk** [comment]
Thank you for your early response @jpivarski !  Do you know if there is a way to convert from TClonesArray into a TObjArray? From ROOT/pyroot or from this module, I don't mind?

Thank you so much again!

**Comment by jpivarski** [comment]
Preferably, you'd want to write the data as simple arrays or `std::vector`, since `TObjArray` is another core ROOT container, which could be hard to deserialize. (To my knowledge, no one has tried it in uproot. But simple arrays and `std::vector` are used all the time.)

If you have control over how the data are written in the first place, that's the easiest way to change it. It might even work to just turn on `splitLevel=99`. But if you have to read from one file and write to another, it would be a standard ROOT event loop.

If you're doing that anyway and see an easy way to break the structures up into something closer to primitive types (numbers and arrays of numbers), then that not only improves the chances of successfully deserializing the data, but it can also make the deserialization much faster. The Awkward `ObjectArray` you're seeing in your output is an indication that uproot hasn't been able to "cast the data as NumPy arrays" and must instead generate Python code to walk over the data structures individually. The difference in rate can be a factor of 100 or so. CMS's NanoAOD has broken the data down to simple arrays of numbers, and this has been a "killer app" for uproot because the deserialization is not only easy, it's also fast. If you have control over your data structures, making them resemble NanoAOD or a "flat ntuple" can have major benefits.

**Comment by antoniomdk** [comment]
I understand. I think the ROOT file is exported from [Corsika](https://www.ikp.kit.edu/corsika/), so I'm not sure if I can change the way it's created. What I can do is read that file and write another trying to change the types.

I appreciate your help so much,

Thank you again!

**Comment by jpivarski** [comment]
I'm assuming that I can close this now. Let me know if I'm wrong.
