### ISSUE TITLE
can't convert "leaf-list" with different dimensional arrays

### ISSUE THREAD

**Issue by LeavesWang** [scikit-hep/uproot#464]
Hi all,

I am currently trying to use the uproot to convert my root/tree data files to NumPy or Pandas data format. My data structure looks like this:
<img width="433" alt="Capture" src="https://user-images.githubusercontent.com/41975394/76087300-e1b03f00-5f83-11ea-9a55-05d8f139b620.PNG">

And I tried using the “array” to convert the anaToF to an array, but it didn’t work and gave me this error message:
<img width="687" alt="Capture2" src="https://user-images.githubusercontent.com/41975394/76087345-fb518680-5f83-11ea-9897-cb7ad15e5022.PNG">
<img width="624" alt="Capture3" src="https://user-images.githubusercontent.com/41975394/76087350-fe4c7700-5f83-11ea-8a58-a42f0cce81b8.PNG">

How can I deal with it?

**Comment by jpivarski** [comment]
This is failing because the leaves in this branch all have different numbers of dimensions. There isn't a good error message telling you that because I didn't even know it was possible and hence, didn't write one.

More fundamentally, this is a mismatch between ROOT's data model and NumPy's: ROOT's [leaf-list](https://root.cern.ch/doc/master/classTTree.html#addcolumnoffundamentaltypes) describes contiguous data, data that can't be read separately because it's interleaved, as does NumPy's [record arrays](https://docs.scipy.org/doc/numpy/user/basics.rec.html), so we convert leaf-lists into record arrays. However, ROOT apparently allows each element of the leaf-list to have its own dimensions, but NumPy shapes contiguous data into multiple dimensions after fixing its dtype (where the fields of a record array are defined).

As for how you can deal with it, if you made this file by serializing a C `struct`, try turning on ROOT's [splitlevel](https://root.cern.ch/doc/master/classTTree.html#addingacolumnofobjs) feature. This should put each leaf in a separate branch. Not only would they not all be glued together in one NumPy array (where you have problems with not being able to give each field a different number of dimensions), but you'd be able to read them separately. Splitting data is good for offline analysis in many ways.

**Comment by jpivarski** [comment]
I'm assuming that I can close this. Let me know if I'm wrong.
