### ISSUE TITLE
Missing interpretation involving `std::map<int, struct>`

### ISSUE THREAD

**Issue by chernals** [scikit-hep/uproot#468]
It seems that I am running into trouble with `uproot` missing the interpretation of the format.

Here is a very lightweight `root` file: https://www.dropbox.com/s/xuux3yel3gd8trw/uproot_issue.root?dl=0

The issue is for the tree `Geant4Data` which contains the class `BDSOutputROOTGeant4Data` (source: https://bitbucket.org/jairhul/bdsim/src/master/include/BDSOutputROOTGeant4Data.hh ).

It contains `std::map<int, ParticleInfo> particles;` where `ParticleInfo` is defined as

```
struct ParticleInfo
{
      std::string name;   ///< Name of particle.
      int         charge; ///< Charge in units of e.
      double      mass;   ///< Mass in GeV.
};
```

**Comment by tamasgal** [comment]
The automatic interpretation fails since it is an unusual structure and uproot does not cover all the edge cases. I am sure the information can be extracted using the uproot tools and Jim will probably figure out a way how to parse the binary information to recreate the streamer for this, but since I was curious, I had a quick look into your data and this is what I reverse engineered so far.

To obtain the raw data, I used `uproot.asdebug` as argument to `.array()` and selected the first and only element:

```python
>>> import uproot
>>> f = uproot.open("uproot_issue.root")
>>> raw = f['Geant4Data']['Geant4Data.']['Geant4Data.particles'].array(uproot.asdebug)[0]
>>> raw
array([ 64,   0,   4, ..., 198,  96, 162], dtype=uint8)
```

Then I created a binary dump to look at it in the hex editor:

```python
>>> with open("raw.dat", "wb") as f: f.write(raw.tostring())
```

The following part shows a rough decoding of the data. I cannot say if the `map-key` (`int`) is correctly parsed, the values show a suspicious pattern, but you can clearly see that the particle names, charge and masses make sense.

```
@\x00\x04\xaa@\t\x00\x00\xdc\xcc(*   (header)

\x00\x00\x00\x1e   # number of std::map elements (here 30)

# misc format descriptions which are needed to parse the following data
\xc4d\xe7\xb8\xc4d\xe7\xc2\xc4e\x0e\xd2\xc4e\x0e\xdc\xff\xff\xf7\\\xff\xff\xf7\xc0\xff\xff\xfe\xbf\xff\xff\xff-\xff\xff\xff\xf0\xff\xff\xff\xf1\xff\xff\xff\xf2\xff\xff\xff\xf3\xff\xff\xff\xf4\xff\xff\xff\xf5\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x16\x00\x00\x00\xd3\x00\x00\x01A\x00\x00\x08@\x00\x00\x08\xa4;\x9a\xf1$;\x9a\xf1.;\x9b\x18>;\x9b\x18H   

# first std::map element
@\x00\x00#\x00\x00,[\xbf\xaf@\x00   # misc element "prefix"
\x00\r\x00\t     # 851977 : map "key" [int]
\n               #     10 : number of following chars (if 255, read 4bytes as int instead)
anti_alpha                # name of particle : [std::string]
\xff\xff\xff\xfe          # -2 : charge [int]
@\r\xd1\xac\x14\xc6`\xa2  # 3.727379  :  mass in GeV [float64]

# second std::map element
@\x00\x00!\x00\x00,[\xbf\xaf@\x00   # misc element "prefix"
\x00\x0b\x00\t   # 720905 : map "key" [int]
\x08             #      8 : number of following chars (if 255, read 4bytes as int instead)
anti_He3                  # name of particle : [std::string]
\xff\xff\xff\xfe          # -2 : charge [int]
@\x06w\x95\xb3[\x0b\xbf   # 2.808391  : mass in GeV [float64]

@\x00\x00$\x00\x00,[\xbf\xaf@\x00
\x00\x0e\x00\t   # 917513 : map "key" [int]
\x0b             #     11 : number of following chars (if 255, read 4bytes as int instead)
anti_triton               # name of particle : [std::string]
\xff\xff\xff\xff          # 0 : charge [int]
@\x06x\xab\x92\xc0a\x84   # 2.808921  : mass in GeV [float64]

...
...
...
the remaining 27 elements...
```

As said, this is not really helpful but it gives an idea how to construct an interpreter for this particular data structure. Everything which is needed to decode the data is inside the part between the "number of items" and the very first element. The `STLMap` parsing is implemented here: https://github.com/scikit-hep/uproot/blob/3f60b2e3ab03953bca91860c587e58131390cac4/uproot/interp/objects.py#L73 and ROOT uses magic numbers to indicate types and masks etc. This is available here: https://github.com/scikit-hep/uproot/blob/master/uproot/const.py

I am not sure about your use-case, if it's a one-time readout, you can consider parsing the data "manually", however if you need to work with these data you'll need a proper interpretation implementation.

**Comment by jpivarski** [comment]
Added to the new project: https://github.com/scikit-hep/uproot4/projects/1#card-40289893

**Comment by chernals** [comment]
Thanks a lot to both of you!

**Comment by jpivarski** [comment]
I'm using this example and a few other `std::map` examples (#283, #431, and #494), I'm trying to solve the `std::map` serialization in general. It's a little weird in that it writes all of the keys together before writing any values, so @tamasgal's interpretation is a little wrong. Below is a quick note to fix that for both of our benefit.

For context, the `std::map<string,string>` case was

```python
def map_string_string(chunk, cursor, context):
    cursor.skip(12)
    size = cursor.field(chunk, _map_string_string_format1, context)
    cursor.skip(6)
    keys = [cursor.string(chunk, context) for i in range(size)]
    cursor.skip(6)
    values = [cursor.string(chunk, context) for i in range(size)]
    return dict(zip(keys, values))
```

so all the key strings and then all the value strings, with some headers. This example of `std::map<int, struct>` is similar. In a nutshell, it's

   1. a 12-byte header for the `std::map`
   2. a 4-byte integer representing the number of items in the map
   3. all the integers in one serialized group
   4. all the structs in a serialized group, where each struct is
      1. a 6-byte header for the struct, which contains size information
      2. a 6-byte header for the `std::string` particle `name`
      3. a 1-to-5-byte string size (ROOT always* uses a 1 byte length prefix for string size, and if the string size is 255 or greater, that byte is 255 and the next 4 bytes gives the string size in full)
      4. the particle `name`
      5. 4-byte `int` for particle charge
      6. 8-byte `double` for particle mass in GeV

Starting from

```python
>>> a = f["Geant4Data/Geant4Data./Geant4Data.particles"].array(uproot.asdebug)[0]
```

We see the number of items (30) after 12 bytes.

```python
>>> a[12 : 12 + 4].view(">i4")
array([30], dtype=int32)
```

Next comes the 30 keys.

```python
>>> a[12 + 4 : 12 + 4 + 30*4].view(">i4")
array([-1000020040, -1000020030, -1000010030, -1000010020,       -2212,
             -2112,        -321,        -211,         -16,         -15,
               -14,         -13,         -12,         -11,           0,
                11,          12,          13,          14,          15,
                16,          22,         211,         321,        2112,
              2212,  1000010020,  1000010030,  1000020030,  1000020040],
      dtype=int32)
```

The "aha!" moment for me was recognizing that these are PDG ids. I looked up 1000020030 and 1000020040 and indeed, they're He3 and alpha, which correspond to the names in the next section.

Working backward from the end (because ROOT puts all of its metadata before any data), we see that it ends with a string, integer, and double (which I verified is the alpha mass).

```python
>>> a[-18 : -18 + 6].tostring(), struct.unpack(">id", a[-18 + 6 :])
(b'\x05alpha', (2, 3.727379))
```

The next one up, working backward, has its string starting at `-50`:

```python
>>> a[-50 : -50 + 4].tostring(), struct.unpack(">id", a[-50 + 4 : -50 + 4 + 12])
(b'\x03He3', (2, 2.808391))
```

(with 2.808 GeV being the He3 mass; thanks, Wolfram Alpha).

Between the end of the second-to-last mass and the beginning of the last particle name is 16 bytes:

```python
>>> a[-50 + 4 + 12 : -18]
array([ 64,   0,   0,  30,   0,   0,  44,  91, 191, 175,  64,   0,   0,
         8,   0,   9], dtype=uint8)
```

I think that the last part, `64, 0, 0, 8, 0, 9`, is the 4-byte size and 2-byte version of the `std::string`. The 4-byte size is masked by a `64` high bit so the size is `8`, and these are always smaller than the real size by 4, so really "12". This "12" is `\x05alpha` (6) plus the 6-byte header = 12. This guess relies heavily on other examples of how ROOT serialization usually works.

The second-to-last part, `64, 0, 0, 30, 0, 0, 44, 91, 191, 175`, is the 4-byte size (again with a `64` high mask) and 2-byte version, followed by another 4 bytes to make a 10-byte header (not uncommon). Following the same rules, the `30` is the size of the whole struct; `\x05alpha` (6) plus the `std::string`'s 6-byte header + 4-byte charge integer + 8-byte mass + 10-byte struct header = 34, and as usual, "34" has to be reduced by 4 so `30`. It's consistent.

Then, looking at the header before the He3 entry,

```python
>>> a[-50 - 16 : -50]
array([ 64,   0,   0,  28,   0,   0,  44,  91, 191, 175,  64,   0,   0,
         6,   0,   9], dtype=uint8)
```

it's the same thing except the string "He3" is two characters shorter than "alpha" so we have a `28` instead of `30` and a `6` instead of `8`. The `std::string` has the same version number (9).

Oddly, the version number for the Particle struct is 0. The TStreamerInfo says that the version number should be 1, so I'll need to find a way for the code to be flexible about that.

```
StreamerInfo for class: BDSOutputROOTGeant4Data::ParticleInfo, version=1, checksum=0x2c5bbfaf
  name            string          offset=  0 type=500 Name of particle.
  charge          int             offset=  0 type= 3 Charge in units of e.
  mass            double          offset=  0 type= 8 Mass in GeV.
```

**Comment by tamasgal** [comment]
Ah nice, I missed that somehow!

> The "aha!" moment for me was recognizing that these are PDG ids.

Indeed 😉 

Also, nice trick with working backwards. I always stared from the bottom up until I hit something, but backwards makes more sense for this format 😆

**Comment by jpivarski** [comment]
This is finished in Uproot4: https://github.com/scikit-hep/uproot4/blob/fd823404093a3bae0b664665e724400add5ebb2e/tests/test_0034-generic-objects-in-ttrees.py#L998-L1143
