### ISSUE TITLE
Working with TGraph2DErrors

### ISSUE THREAD

**Issue by GuiiFerrari** [scikit-hep/uproot#474]
Hi everyone,

I need to read the axis of a TGraph2DErrors but I'm not finding any method / documention that helps me. There's only a .read() but I don't know how to work with arguments: 'source', 'cursor', 'context', and 'parent'. I need these axisin arrays because It's easy than C++ to implement some Machine Learning methods. what should I do?

Thank you all.

**Comment by jpivarski** [comment]
What you're looking for would be in one of the attributes whose name starts with "`_f`" (translated directly from ROOT). It might be inside of `_fXaxis`.

This is not more apparent because TGraph2DErrors doesn't have a Pythonic wrapper like the others [in this directory](https://github.com/scikit-hep/uproot-methods/tree/master/uproot_methods/classes). (These are user-contributed, so when you find what you're looking for, you're welcome to add a Pythonic convenience function as a pull request.)

**Comment by GuiiFerrari** [comment]
I would like to do some Pythonic wrapper for this but I don't even know how to start it hahaha.
Thank you!

**Comment by jpivarski** [comment]
I'm guessing I can close this? Let me know if I'm wrong.
