### ISSUE TITLE
TParameter support

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#478]
Would it be possible to add the ability to (easily) read and write `TParameter`s? We use these to store normalizations and other metadata in our ATLAS analysis.

**Comment by jpivarski** [comment]
What happens when you try to read them now?

**Comment by jpivarski** [comment]
This doesn't address writing—that would be a new project. But about reading, you might already have what you want.

I just looked up the [TParameter documentation](https://root.cern.ch/doc/v608/classTParameter.html). It's templated, so it really matters what the `AParamType` is. If it's something simple, it might work out of the box.

**Comment by beojan** [comment]
I get ` <Undefined_TParameter_3c_double_3e_ at 0x7f637d082b00>`. The only member is a `read` function.

**Comment by jpivarski** [comment]
This `TParameter<double>` failed to be automatically deserialized. If you send me a file, I can figure out why.

**Comment by beojan** [comment]
I think the file was corrupt just in some (transient) way.

**Comment by jpivarski** [comment]
Okay, so you're saying it works? (You can close this issue if so.)

**Comment by beojan** [comment]
Yes, it works. It would be nice to have a public way of accessing `fVal` though (rather than having to dig into the private members of the TParameter).

**Comment by jpivarski** [comment]
That sort of thing can be added with a module in [uproot-methods/classes](https://github.com/scikit-hep/uproot-methods/tree/master/uproot_methods/classes), which is user-contributed.  `:)`

**Comment by beojan** [comment]
I've added a file (`TParameter.py`) to that directory, mostly cribbing from the `TGraph` implementation. This clearly isn't enough for uproot to recognize it as providing an interpretation for `TParameter`s. How do I "register" my new class with uproot-methods?

**Comment by jpivarski** [comment]
Can you make it a pull request so that I can see it?

There are a few requirements: the name of the module must be the C++ name of the class and the class within it needs to be named "Methods". This is Uproot's discovery mechanism:

https://github.com/scikit-hep/uproot-methods/blob/2e2089748d4ece2a573cd6fa8cb84782ebb8cb15/uproot_methods/classes/__init__.py#L5-L12

(There isn't any explicit registration.)

It could be an issue that the C++ class name is `TParameter_3c_double_3e_` in Python, since Python class names have to be `[A-Za-z_][A-Za-z0-9_]*` identifiers.

I just verified that Uproot is using this sanitized `pyclassname` when looking for methods:

https://github.com/scikit-hep/uproot/blob/820049c4cdbf580b42df90a8c48993f51d366ba5/uproot/rootio.py#L916-L926

The `pyclassname` is defined here:

https://github.com/scikit-hep/uproot/blob/820049c4cdbf580b42df90a8c48993f51d366ba5/uproot/rootio.py#L687-L692

**Comment by beojan** [comment]
There must be some way around the requirement that the name of the module match the C++ class name, since I need to match `TParameter` with any template parameters.

How does uproot deal with this for `TH1{I,D,F,...}`?

**Comment by jpivarski** [comment]
Uproot deals with those histogram types by defining methods on the superclass, TH1. Histograms were implemented at a time before C++ templates worked reliably in all compilers, so they have a superclass. Parameters are the first set of classes that we've dealt with where we wanted the same behavior on all specializations, so no, there isn't a mechanism for dealing with that yet.

**Comment by beojan** [comment]
The PR has now been merged in uproot_methods.
