### ISSUE TITLE
Determine number of chunks with uproot.iterate

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot#483]
When using `iterate`, is there some way to determine ahead of time how many chunks there are (i.e. how many iterations will occur)?

**Comment by jpivarski** [comment]
Yes, the `entrysteps` parameter calls `clusters`, `mempartitions`, or is one per file, depending on the type of specification. `clusters` and `mempartitions` produce lightweight iterators that can be evaluated and counted (e.g. `len(list(tree.clusters(branches)))`) quickly—without reading data.

If your iteration is over many files, you do have to open each file to do this count, and opening each file, even reading only the file and tree metadata, can be somewhat expensive. The default `entrysteps` when iterating over files is `np.inf`, meaning one iteration step per file, so if that's your mode, it's easy to count!

The only complication here is that there are so many ways to specify the `entrysteps` and each implies a different method of counting.

**Comment by tamasgal** [comment]
I thought that it might be useful to offer some kind of stripped down versions of the `uproot.open` function to skip things when only a few specific information is needed. I ran into some issues recently when skimming through thousands of files and only looking for the existence of some branches for example. In this case the streamer and other "Python heavy" stuff is not needed and  might save quite a lot of time.

For this of course there should be a set of common use-cases which justify such an extra readout...

**Comment by jpivarski** [comment]
Uproot has a specialized function for determining the number of entries without reading the TStreamerInfos and the majority of the TTree metadata (`uproot.numentries`), but this works because `fEntries` is near the beginning of the TTree record, before most of the version-specific differences arise. Just getting the names of all the TBranches already requires version-specific parsing, which either requires reading all of the TStreamerInfos or would be a hard-coded function that has to stay abreast of changes in ROOT.

If you (@beojan) can use `entrysteps=np.inf` in `uproot.iterate`, then the number of steps is just the number of files, and that should be easy to determine. If you're iterating within one file, `clusters` and `mempartitions` are quick to evaluate; they do not read basket data.

**Comment by beojan** [comment]
It turns out `len(list(tree.mempartitions(size)))` doesn't return the correct number. My progress bar finishes at about 9%.

**Comment by jpivarski** [comment]
I'm guessing I can close this? Let me know if I'm wrong.
