### ISSUE TITLE
directly open a TTree

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot#49]
I have a ROOT file like this

    KEY: RooFitResult	fitResult;1	Fit Results
    KEY: TProcessID	ProcessID0;1	46ded5cc-074c-11e8-9717-f83db9bcbeef
    KEY: TTree	nllscan;1	nllscan

when opening with `uproot.open` I get an error, probably due to the `RooFitResult` object:

    ValueError: cannot sort TStreamerInfos into dependency order:

    RooUniformBinning    requires RooAbsBinning

this is not the point. Is it possible to have a function to directly open a TTree inside a file and to ignore everything else? Something like

    uproot.open_tree(filename, treename)

**Comment by jpivarski** [comment]
The only way uproot (or ROOT, for that matter) knows how to read a TTree from a file is via its streamers— the definition of a TTree changes from version to version, so we strictly need its streamer (which depends on a dozen other streamers) to read the TTree.

uproot 1.x didn't use streamers, and it had a if-then based TTree ingest that navigated among the past five years of TTree versions, but this isn't scalable as ROOT can add new TTree fields at any time (they just did, in the last version). I have been considering including these as a fallback, for cases like the one you described above.

The `uproot.open` command has a `read_streamers=True` option that you can set to `False`, which was intended for this case. Try that first (I might have put those uproot 1.x TTree version-dependent definitions in after all...).

But in any case, please send me your file so that I can fix the issue. Since you can't do anything without streamers, I'm trying to keep the streamer-reading code path as exception-free as possible: for instance, NotImplementedErrors for unhandled types are deferred to when you actually try to _load_ the items. But if we can't sort the streamers in their dependency order, I don't know what to do— we can't define classes, even with NotImplementedErrors in their constructors, if the class inheritance doesn't seem to be a tree. I'd like to see how `RooUniformBinning` relates to `RooAbsBinning` to see why the dependency sorter thinks they're circular.

You can post the file here or send it to me privately.

**Comment by wiso** [comment]
[output__all_free.txt](https://github.com/scikit-hep/uproot/files/1686268/output__all_free.txt)
Thank you. I had to change the extension to `txt` from `root`

**Comment by jpivarski** [comment]
As it turns out, RooUniformBinning requires RooAbsBinning, but RooAbsBinning doesn't exist. It's not even in the list of streamers. I put in a change to skip cases like that, so neither RooUniformBinning nor RooAbsBinning classes get generated, but the subgraph of classes with existing inheritance trees (including TTree) do get generated.

This is uproot 2.5.22, in GitHub and PyPI.
