### ISSUE TITLE
Different ways of opening and reading files into lazyarrays

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot#491]
Hi,

I observed a segfault when reading ROOT files (built with `uproot`) with `lazyarrays()`.  This segfault does not occur in my local development environment (macOS), but I can reproduce it in a docker container. Furthermore, it only appears in one of two ways of reading the file.

To reproduce the error, I am using
```bash
$ docker run -it --rm python:3.7-slim bash
```
Inside the container:
```bash
$ pip install uproot
$ python
>>> import uproot
>>> uproot.__version__
'3.11.6'
>>> import awkward
>>> awkward.__version__
'0.12.21'
```
I then create a file with this script:
```python
import uproot

with uproot.recreate("data.root") as f:
    f["tree"] = uproot.newtree({"jet_pt": "float64"})
    f["tree"].extend({"jet_pt": [1,2,3,4,5]})
```
Next, I read the file like this:
```python
import uproot

with uproot.open("data.root") as f:
    data = f["tree"].lazyarrays()

print(data["jet_pt"])
```
resulting in `Segmentation fault`.
I then try reading the file in the following way instead:
```python
import uproot

data = uproot.open("data.root")["tree"].lazyarrays()

print(data["jet_pt"])
```
which does not produce a crash.
Another way to avoid the segfault is to already access the data while the file is still open, like this:
```python
import uproot

with uproot.open("data.root") as f:
    data = f["tree"].lazyarrays()
    print(data["jet_pt"])

print(data["jet_pt"])
```
I am surprised about the differences in behavior, and that I only see them in this docker image (and gitlab CI, which originally caused me to discover this), while in my macOS environment all examples work without segfaulting. For completeness, I'm using `awkward` 0.12.17 and `uproot` 3.10.12 locally. Is this behavior expected?

Edit:  I updated to `uproot` 3.11.6 and `awkward` 0.12.21 locally, which now also segfaults in the same way and shows identical behavior to the docker container.

**Comment by jpivarski** [comment]
I was about to say that it's hard to even imagine a segfault from Uproot + Awkward0 (the old version, which was pure Python), but I see what it is: you're accessing the data after the memory map has been closed.

Originally, Uproot was designed around memory-mapped files, which let the OS load or unload whatever it wants to provide the bytes a program asks for. This meant that they could be left open without using up any memory. Almost immediately (issue #4), someone asked for a context manager to do the `with uproot.open(...) as f` thing; I argued that it isn't needed because it's a memory map, and ended up making the context manager do nothing.

Then, much later, someone else showed me the error of my ways: open memory maps don't use memory, but there is a limited number of file handles available, and using up all of those is a bad thing. But the trouble was that everything was designed around the idea that you can get at the bytes at any time. If I actually close the memory maps, accessing them afterward causes segfaults. (Often; some segfaults are based on undefined behavior and are therefore platform-dependent or can even vary from run to run. That's why I hate 'em. They provide very little diagnostic power.)

I eventually consented and made the context manager close the memory map because it was leaking file handles. But that means that it's possible to cause segfaults, as you've done here.

You can work around this problem by using the `FileSource`, instead of the `MemmapSource`, which opens and closes plain file handles instead of maintaining one memory map. Then, if you're outside the context manager, it will open new files. (Or complain about being closed; I don't remember.)

This was high on my list of priorities for Uproot4. Going forward, we have real context management:

https://github.com/scikit-hep/uproot4/blob/4cd75f06218cf381e5906876e6b0b50b9dd9ca82/uproot4/source/memmap.py#L77-L87

But to make this possible, I have to _not_ assume that the file is always available everywhere the requested operation needs it. If ROOT files were opened, read entirely, then closed, there would be no issue, but we take objects out of ROOT files, which can live longer than the file stays open, and then these objects can request more data, like evaluating a lazy array or even just asking a TTree object for a regular array.

That's why this fix had to wait until I was ready to revamp everything, but that's happening now, piggy-backing on the Awkward0 → Awkward1 transition.

**Comment by alexander-held** [comment]
Thank you very much for this detailed answer! So if I understand correctly, the 
```python
data = uproot.open("data.root")["tree"].lazyarrays()
```
approach works because the memory map is not closed, and as long as I don't run out of file handles this is in principle fine? If so, I think this would be sufficient for my current use and I can reevaluate the approach when switching to Uproot4/Awkward1.

**Comment by jpivarski** [comment]
Yes, that would work. I think it's hard to run out of file handles.

**Comment by alexander-held** [comment]
Thanks a lot again! Feel free to close.

**Comment by tamasgal** [comment]
For the sake of completeness, here is the issue which you mentioned, which I created due to a memory pile-up when working with multiple files in a single process:

https://github.com/scikit-hep/uproot/issues/438

**Comment by jpivarski** [comment]
Thanks for finding that issue; I was looking for it last night!

This context manager issue bookmarks the history of Uproot nicely; #4 (asking for having a context manager at all) was the very first issue, and #438 is fairly recent (this year). It's one of the design flaws that I'm fixing now.

Incidentally, @tamasgal, I'm doing the same thing you are with walking through the Uproot code, straightening it out in a rewrite. To handle the above issue (and #393), the Source is not operated on directly, we have to first ask for Chunks and operate on those (at which point, the file might be found to be closed and/or the remote connection can be downloading in the background), so some reorganization is necessary. But since it's open anyway, I'm detangling things like my hacky handling of multiple versions of the same class and code generation. The new code should be easier to read for conversion to Julia.

**Comment by tamasgal** [comment]
Ah that sounds quite interesting indeed! The versioning in Julia is very difficult to get right and I now came up with a solution which I might like, but I am still unsure. Since this is not really the right place to discuss details, I guess I'll open a new thread in https://groups.google.com/forum/#!forum/polyglot-root-io I am curious about the refactorings in uproot!
