### ISSUE TITLE
Missing interpretation for std::map<std::string, TVector3>

### ISSUE THREAD

**Issue by chernals** [scikit-hep/uproot#494]
Not sure if this is really something missing or an issue on my side, I expect `TVector3` to be sufficiently standard that it should work.

Here is a sample file:

https://www.dropbox.com/s/f1x6xvro5fq03g1/uproot_issue_tvector3?dl=0

It is in the `Model` tree, branch `Model.scoringMeshTranslation`.

Thanks for the help on this!

**Comment by jpivarski** [comment]
It's not on your side—TVector3 is standard, but generic `std::map` (for any contents) has not been implemented. Your sample file will help with implementing it, though! (Until now, I've only seen examples of maps of strings, and strings are a special case, not generalizable. I'll have to get past a few deadlines before I can work on it though, and it will probably only go into Uproot4 because that's where the main-line development is now.)

**Comment by chernals** [comment]
Is uproot4 already usable? Should I make the switch to anticipate this?

**Comment by jpivarski** [comment]
The goal is to have it ready by the beginning of July. That date is a little uncertain, but it will be close.

Since Uproot 3 → 4 is a big upgrade like Awkward 0 → 1, I'm doing the same thing of giving it a different package name, making it possible to use both in the same Python process, which could be necessary if some things in the new library don't work right away or old scripts need to be converted.

[This tutorial](https://github.com/jpivarski/2020-06-08-uproot-awkward-columnar-hats/blob/master/evaluated/01-using-uproot-effectively.ipynb) on Uproot mixes in some Uproot 4 examples. It's in a state where we can read jagged arrays from TTrees, though it's still unfinished in many ways (reading objects from TTrees, for instance).

**Comment by jpivarski** [comment]
It's a card in the new project: https://github.com/scikit-hep/uproot4/projects/1#card-40289893

**Comment by jpivarski** [comment]
This is finished in Uproot4: https://github.com/scikit-hep/uproot4/blob/fd823404093a3bae0b664665e724400add5ebb2e/tests/test_0034-generic-objects-in-ttrees.py#L1244-L1295
