### ISSUE TITLE
Support opening files on the web

### ISSUE THREAD

**Issue by graipher** [scikit-hep/uproot#50]
Normal ROOT supports opening files from the web, not directly through the constructor, but with the `Open` method. It would be nice if `uproot` did so as well.

```
>>> uproot.open('http://www.scikit-hep.org/uproot/examples/Zmumu.root')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/uproot/rootio.py", line 69, in open
    raise ValueError("URI scheme not recognized: {0}".format(path))
ValueError: URI scheme not recognized: http://www.scikit-hep.org/uproot/examples/Zmumu.root
```

**Comment by jpivarski** [comment]
Agreed. The difficult part is that you need to seek a lot to get around a ROOT file, and HTTP isn't seekable the way XRootD is. It's possible to send byte range requests to HTTP GET only part of a file:

[https://stackoverflow.com/q/1971240/1623645](https://stackoverflow.com/q/1971240/1623645)

but that still means that every interaction is a new HTTP request. We're caught between wanting to download the whole file, because that would let us seek around at leisure, and wanting to make lots of HTTP requests to avoid big downloads. The optimum is somewhere in between.

uproot's [local file handler](https://github.com/scikit-hep/uproot/blob/master/uproot/source/file.py) and [XRootD handler](https://github.com/scikit-hep/uproot/blob/master/uproot/source/xrootd.py) are subclasses of [ChunkedSource](https://github.com/scikit-hep/uproot/blob/master/uproot/source/chunked.py), which emulate a memory map (uproot's default file handler) by reading chunks of the file on demand. They present a slicable array interface.

A good solution to HTTP would be another subclass of ChunkedSource that makes HTTP requests for each chunk, and the optimal size of those chunks should be rather large, a balance between downloading too much unnecessary data and making too many small requests. It would be very straightforward.

I've put it on my mental to-do list, but if someone really needs this feature soon, I can guide you through it.

**Comment by jpivarski** [comment]
I had uproot open and was fixing other things (#54), so I decided to give this one a go. To make sure I didn't spend too long on it, I timed it: 10 minutes! Like I said, the infrastructure was [already there](https://github.com/scikit-hep/uproot/blob/c7146a9c439134a8dfd1c399b68d578fea0048a7/uproot/source/http.py).

I have not tuned the chunking parameter. By default, this will download over HTTP in 8 kB chunks with a 1 MB cache. These might be the wrong choices, and should be explored in some realistic case. (Who is reading ROOT files over HTTP? What kind of performance do they need when doing that?)

This will be 2.6.16 after I fix one more thing.
