### ISSUE TITLE
Unexpected return of TH2D.numpy()

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#502]
Calling `.numpy()` on a TH2D loaded with uproot produces this data structure (types highlighted)
```
tuple(
  array(<values>), 
  list(
     tuple(
       array(<edges-x>),
       array(<edges-y>)
     )
   )
)
```
while the following is expected (same as output as np.histogram2d)
```
tuple(
  array(<values>), 
  array(<edges-x>),
  array(<edges-y>)
)
```
At the very least the double wrapping of the edges in both a tuple and a list cannot be intended.

**Comment by jpivarski** [comment]
The double-wrapping wasn't intended—the originally intended code must have gotten away from us at some point.

However, NumPy has two forms for multidimensional histograms, and we'd need to pick one of them:

```python
>>> import numpy as np
>>> content, edges = np.histogram([1, 2, 3, 4, 5])
>>> content2d, edges_x, edges_y = np.histogram2d([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
>>> content2d, (edges_x, edges_y) = np.histogramdd([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
```

Only the last one generalizes:

```python
>>> content3d, (edges_x, edges_y, edges_z) = np.histogramdd([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
```

I think it used to be the 2-d form, but then it was switched to the d-d form because that's more general. Or maybe the d-d needs to be specifically selected because it not only fails to limit to the 2-d case, it also fails to limit to the 1-d case:

```python
>>> content1d, (edges_x,) = np.histogramdd([[1, 2, 3, 4, 5]])
```

and maybe someone wants consistency with the d-d interface in all dimensions.

**Comment by HDembinski** [comment]
Ok, makes sense. I think the most intuitive is to map TH2D to the histogram2d format and THnD to the histogramdd format.

**Comment by jpivarski** [comment]
I'd like to broaden the scope of this thread to discuss Uproot → histogram interfaces in general, since we're already talking about Uproot → NumPy histogram interfaces.

First of all, Uproot4 now adheres to your desired interface, @HDembinski.

```python
>>> import uproot4, skhep_testdata
>>> with uproot4.open(skhep_testdata.data_path("uproot-hepdata-example.root")) as f:
...     values, edges = f["hpx"].np                # TH1F
...     values, xedges, yedges = f["hpxpy"].np     # TH2F
...     (values, errors), edges = f["hprof"].np    # TProfile; no NumPy equivalent but this seems natural
```

If I had an example of a TH3, it ought to be accessed via

```python
...     values, (xedges, yedges, zedges) = f["???"].np
```

following [np.histogramdd](https://numpy.org/doc/stable/reference/generated/numpy.histogramdd.html) (implemented but untested) and if I had an example of a TProfile2D/TProfile3D, it ought to be accessed via

```python
...     (values, errors), xedges, yedges = f["???"].np
...     (values, errors), (xedges, yedges, zedges) = f["???"].np
```

(unimplemented).

The general plan for Uproot4 histogram objects is to have a very minimal interface that almost entirely just converts to other formats. The natural first two to start with are NumPy and boost-histogram. I'm using the two-letter abbreviations for them, `np` and `bh`, as properties, so that expressions like

```python
file["my_histogram"].bh.do_whatever()
```

become typical shorthand. (About performance: Uproot4 has an object cache by default—repeated calls to the `file["my_histogram"]` part check the cache before rereading from the file, so we don't need to discourage this syntax.)

I don't think the hist library has a two-character shorthand (why would it need one? I think I can type "hist" faster than anything with two characters!), so I think the equivalent for that would be `hist`:

```python
file["my_histogram"].hist.plot()
```

Using properties for the library converters assumes that we won't ever need to parameterize the conversion with arguments. `f["h"].np` returns tuples of arrays, `f["h"].bh` returns a `boost_histogram.Histogram`, and `f["h"].hist` returns a hist histogram. But if they weren't properties, then users would have to _always_ type the `()` for the sake of possible future cases. I think it's better for this usual case to be succinct. (If we ever need to parameterize a conversion, that can be a new method name, indicating that we're doing something more complicated.)

TH1, TH2, and TH3 can be converted into Boost histograms, and the strategy I've followed is to

   * turn `TAxis` with `fLabels` into `StrCategory` axis,
   * turn `TAxis` with `fXbins` into `Variable` axis,
   * turn all others into `Regular` axis,

and

   * turn histograms with `fSumw2` into `Weight` storage,
   * turn all other histograms into `Int64` or `Double` storage, depending on which `TArray` they inherit from.

For metadata, I've attached all `TAxis` parameters to the Boost axis metadata and all `TH1` parameters to the Histogram metadata except

   * `fXbins` and `fLabels`, since they've already been converted into axis data,
   * `fXaxis`, `fYaxis`, `fZaxis` from the main Histogram because they're covered by the axes themselves,
   * `fSumw2` because this is part of the main data of the bins,
   * `fContour` because this probably scales with the size of the histogram, making it not metadata,
   * `fBuffer` because I think this is only used for ROOT's internal purposes while filling a histogram. I might be wrong.

The idea is that metadata should be all those scalar quantities that don't change as you slice, rebin, or otherwise modify the histogram, but would allow a round-trip conversion from ROOT to boost-histogram/hist to ROOT. If a histogram has special fonts and colors in ROOT, it would be nice to preserve them.

For instance, here's a histogram:

```python
>>> import uproot4, skhep_testdata
>>> with uproot4.open(skhep_testdata.data_path("uproot-hepdata-example.root")) as f:
...     h = f["hpx"].bh
...
>>> h
Histogram(Regular(100, -4, 4, metadata={'@fUniqueID': 0, '@fBits': 50331648, 'fName': 'xaxis', 'fTitle': '', 'fNdivisions': 510, 'fAxisColor': 1, 'fLabelColor': 1, 'fLabelFont': 42, 'fLabelOffset': 0.004999999888241291, 'fLabelSize': 0.03500000014901161, 'fTickLength': 0.029999999329447746, 'fTitleOffset': 1.0, 'fTitleSize': 0.03500000014901161, 'fTitleColor': 1, 'fTitleFont': 42, 'fNbins': 100, 'fXmin': -4.0, 'fXmax': 4.0, 'fFirst': 0, 'fLast': 0, 'fBits2': 0, 'fTimeDisplay': False, 'fTimeFormat': <TString '' at 0x7f32281d0450>}), storage=Double()) # Sum: 74994.0 (75000.0 with flow)
```

You can see the axis metadata inline, but the Histogram metadata is

```python
>>> h.metadata
{'@fUniqueID': 0, '@fBits': 50331656, 'fName': 'hpx', 'fTitle': 'This is the px distribution', 'fLineColor': 602, 'fLineStyle': 1, 'fLineWidth': 1, 'fFillColor': 0, 'fFillStyle': 1001, 'fMarkerColor': 1, 'fMarkerStyle': 1, 'fMarkerSize': 1.0, 'fNcells': 102, 'fBarOffset': 0, 'fBarWidth': 1000, 'fEntries': 75000.0, 'fTsumw': 74994.0, 'fTsumw2': 74994.0, 'fTsumwx': -97.16475860591163, 'fTsumwx2': 75251.86518025988, 'fMaximum': -1111.0, 'fMinimum': -1111.0, 'fNormFactor': 0.0, 'fOption': <TString '' at 0x7f32281d05d0>, 'fFunctions': <TList of 1 items at 0x7f3228124850>, 'fBufferSize': 0, 'fBinStatErrOpt': 0, 'fN': 102}
```

Just to see that we have everything here, let's look at all the member data associated with the attached function (which is actually a `TPaveStats`):

```python
>>> h.metadata["fFunctions"][0].all_members
{'@fUniqueID': 0, '@fBits': 50331657, 'fLineColor': 1, 'fLineStyle': 1, 'fLineWidth': 1, 'fFillColor': 0, 'fFillStyle': 1001, 'fX1': 2.8000001713633544, 'fY1': 2117.3906469108188, 'fX2': 4.800000208616257, 'fY2': 2619.290637562203, 'fX1NDC': 0.7800000160932541, 'fY1NDC': 0.7750000059604645, 'fX2NDC': 0.9800000190734863, 'fY2NDC': 0.9350000023841858, 'fBorderSize': 1, 'fInit': 1, 'fShadowColor': 1, 'fCornerRadius': 0.0, 'fOption': <TString 'brNDC' at 0x7f32281d06d0>, 'fName': <TString 'stats' at 0x7f32281d07d0>, 'fTextAngle': 0.0, 'fTextSize': 0.0, 'fTextAlign': 12, 'fTextColor': 1, 'fTextFont': 42, 'fLabel': <TString '' at 0x7f32281d0750>, 'fLongest': 17, 'fMargin': 0.05000000074505806, 'fLines': <TList of 4 items at 0x7f322810c690>, 'fOptFit': 0, 'fOptStat': 1111, 'fFitFormat': <TString '5.4g' at 0x7f32281d09d0>, 'fStatFormat': <TString '6.4g' at 0x7f32281d0a50>, 'fParent': <TPaveStats (version 4) at 0x7f3228124590>}
>>> h.metadata["fFunctions"][0].member("fLines")[0].member("fTitle")
'hpx'
>>> h.metadata["fFunctions"][0].member("fLines")[1].member("fTitle")
'Entries = 74001  '
>>> h.metadata["fFunctions"][0].member("fLines")[2].member("fTitle")
'Mean  = -0.002273'
>>> h.metadata["fFunctions"][0].member("fLines")[3].member("fTitle")
'RMS   =  1.002'
```

In addition to the `np`, `bh`, `hist` properties, it's useful to also have methods (with parentheses) for

   * `edges(axis)` → NumPy array of a requested axis (e.g. `0`, `1`, `2`, `"x"`, `"y"`, `"z"`), including `-inf` and `inf` as the extremes because underflow and overflow are included,
   * `values()` → NumPy array of bin contents, including underflow and overflow bins (where ROOT puts them: below and above the bins)
   * `values_errors()` → 2-tuple of NumPy arrays for values and errors, since computing errors often requires values to be computed, and this API avoids unnecessary calculations.
   * `TProfile` additionally has an `error_mode` parameter for `values_errors` (error on mean, spread, integer spread, Gaussian spread) and `effective_entries()` → NumPy array of effective entries, which is another non-trivial quantity unique to profile plots.

But they won't ever have methods like `fill` or `plot`. The uproot-methods idea of trying to get the community to define what behavior they want these objects to have didn't work, particularly when combined with the strange method resolution hierarchy (e.g. TH3 is a subclass of TH1). Instead, I think the API on these objects should be kept minimal and primarily just extract data or convert to other libraries, so that the real work can be done in those other libraries.

All of these have been implemented in Uproot4 0.0.14 except `TProfile` → boost-histogram. There's a placeholder there, but it doesn't put meaningful data in the `Histogram`. I've completed the `TProfile` → NumPy implementation, which illustrates how to turn ROOT internal variables into values and errors with the four error definitions (the hard part); I'm hoping that @HDembinski, @henryiii, or @LovelyBuggies can help with the rest, including the hist part.

I'm also open to critiques of this API, though I want to include it in Monday's tutorial, so I'm hoping it's not too controversial. (The main message of that tutorial is that the Pythonic way of doing things is for libraries to talk to each other. Hence, Uproot does not deal in histograms, but we make it as easy as possible to get your data as NumPy/boost-histogram/hist objects.)

**Comment by HDembinski** [comment]
Side-comment: That TH3 is a subclass of TH1 makes sense only in terms of state inside the class, but it makes no sense in terms of the interface. Inheritance should model an "Is A" relationship, but TH3 is not (by any means) a TH1. The people who wrote ROOT didn't study software design.

**Comment by HDembinski** [comment]
This looks very impressive. I like the idea of keeping the metadata.

In software design, interfaces that rely on caching are discouraged if there are alternative designs without caching. I would not trade the convenience of losing an extra brace against a more obvious interface, but I think the choice is less about convenience and more about the ability to easily get and set. You cannot assign to the result of a getter in Python.

**Comment by henryiii** [comment]
Preserving histogram metadata is addressed in https://github.com/scikit-hep/boost-histogram/pull/403.

**Comment by henryiii** [comment]
I don't like auto switching based on dimensions. Even NumPy doesn't do that, they provide distinct functions for each interface.  It makes it hard to write an interface that accepts 3D and 2D histograms. I would either extrapolate the 1D/2D interface (it's natural to convert in Python 3, and only one extra line in Python 2), or I'd provide a `npdd` that provides the histogramdd interface along with the (extrapolated) `np` interface.

**Comment by HDembinski** [comment]
Henry makes a good point.

**Comment by jpivarski** [comment]
What if the names were `np1` (only exists on `TH1` not counting weird inheritance), `np2` (only exists on `TH2`), and `np` (exists on all histograms, supplying the `np.histogramdd` style of interface)?

We should keep in mind that it takes only a moment to adjust to the "wrong" tuple structure, but a user might not ever discover a new name (though these might be found through tab-completion, since they start with the same characters).

**Comment by henryiii** [comment]
The expanded version is what boost-histogram provides in `.to_numpy()`. I think providing that uniform interface via `.np` then a `.npdd` if someone *really* needs the exact output of histogramdd would be fine? If NumPy were to add a histogram3d, the `.np` shortcut would look like it for 3D.

**Comment by henryiii** [comment]
I’ll check later and see how hard it might be to describe the output of .np with static types. I know it’s easy if the types are repeated, but not sure about a mismatch between bins and edges.

np1 and such is not a bad idea either. It is there mostly for compatibility, and that is the most compatible. Though for plotting and most things that matter for numpy style classic output, I think 1D and 2D are far more common, and .np for both is simpler for those. I hope for 3d people will use .bh or .hist. Actually I hope that for 1D. :)

**Comment by jpivarski** [comment]
By the power of Python, I have broken the class inheritance between TH1, TH2, and TH3:

```python
>>> import uproot4, skhep_testdata
>>> f = uproot4.open(skhep_testdata.data_path("uproot-hepdata-example.root"))
>>> h1 = f["hpx"]
>>> h2 = f["hpxpy"]
>>> hprof = f["hprof"]
>>> h1, h2, hprof
(<TH1F (version 1) at 0x7f2c603a2190>,
 <TH2F (version 3) at 0x7f2c600e0bd0>,
 <TProfile (version 6) at 0x7f2c601847d0>)
>>> h1.np<tab>
h1.np   h1.np1  
>>> h2.np<tab>
h2.np   h2.np2  
>>> hprof.np<tab>
hprof.np
>>> values, (xbins,) = h1.np
>>> values, (xbins, ybins) = h2.np
>>> (values, errors), (xbins,) = hprof.np
>>> values, xbins = h1.np1
>>> values, xbins, ybinx = h2.np2
>>> isinstance(h1, uproot4.behaviors.TH1.TH1)
True
>>> isinstance(h2, uproot4.behaviors.TH1.TH1)
False
>>> isinstance(h2, uproot4.behaviors.TH2.TH2)
True
>>> isinstance(hprof, uproot4.behaviors.TH1.TH1)
False
>>> isinstance(hprof, uproot4.behaviors.TProfile.TProfile)
True
```

It works because the "Model" classes that Uproot 4 uses to represent ROOT classes do not Python-inherit each other: it's a nearly flat hierarchy. If classes C++-inherit each other (such as TH1F from TH1), then that determines which behavior mix-ins get assigned to the classes dynamically generated from ROOT streamers. Thus, we can insert new rules, such as a rule that TH2, TH3, and TProfile do not inherit from TH1:

https://github.com/scikit-hep/uproot4/blob/0af5eef97c7e7ee5de11484ac5d1929379a802ad/uproot4/behaviors/TH2.py#L11-L12

https://github.com/scikit-hep/uproot4/blob/0af5eef97c7e7ee5de11484ac5d1929379a802ad/uproot4/behaviors/TH3.py#L11-L12

https://github.com/scikit-hep/uproot4/blob/0af5eef97c7e7ee5de11484ac5d1929379a802ad/uproot4/behaviors/TProfile.py#L17-L18

Given this inheritance diagram,

![image](https://user-images.githubusercontent.com/1852447/87228479-264f4b00-c367-11ea-89d9-8779eb4ef444.png)

the places to prune are `TH2.no_inherit == (TH1,)`, `TH3.no_inherit == (TH1,)`, `TProfile.no_inherit == (TH1,)`, `TH2Poly.no_inherit == (TH2,)`, `TProfile2D.no_inherit == (TH2,)`, `TProfile3D.no_inherit == (TH3,)`.

(Behavioral mix-ins won't be defined for the classes that differ in numerical type, since they get the right NumPy dtype from the `TArray` that they descend from.)

**Comment by jpivarski** [comment]
I'm not going to say much about converting Uproot histograms to NumPy with `np`, `np1`, `np2`, etc., which will give us more time to think about it.

I do want to say _something_ about getting histograms in a useful form, so I'm showing the `bh` property, assuming that the name and calling convention are uncontroversial. Scroll down to the "Histograms!" section of [this notebook](https://github.com/jpivarski/2020-07-13-pyhep2020-tutorial/blob/2d9b5f23a12def53ad59b230f97d79733e4cc875/tutorial.ipynb) to see what I have so far.

There is, unfortunately, a warning, which I've raised here: scikit-hep/mplhep#159. Furthermore, the 2D plot uses an entirely different function and you have to convert the `bh.Histogram` into NumPy _and_ use a var-args `*` to fit the API.

Am I missing something or is this the state of plotting histograms? If there's anything I could show instead, I'll try to work it in, but time is getting short.

**Comment by jpivarski** [comment]
Also, I'm fairly unopinionated about the interface between Uproot and NumPy histograms, boost-histogram, and hist. If you want the conversion to NumPy to go through `to_numpy()` methods (with parentheses), then I'm fine with that, though (1) it makes the conversion seem like a more significant undertaking and (2) the `bh.Histogram.to_numpy()` method returns tuples in the form of `np.histogram`, rather than `np.histogramdd`, so it lacks generality even though `bh.Histogram` is an N-dimensional object. Should the form of the tuples, the original topic of this issue, be an _argument_ to the `to_numpy()` method?

Like,

   * `TH1.to_numpy(histogramdd=False)` (default) is like `np.histogram`; `histogramdd=True` is like `np.histogramdd`
   * `TH2.to_numpy(histogramdd=False)` (default) is like `np.histogram2d`; `histogramdd=True` is like `np.histogramdd`
   * `TH3.to_numpy(histogramdd=True)` is the default and only allowed value of the argument, or maybe it doesn't have this argument
   * `TProfile*.to_numpy()` really shouldn't have a `histogramdd` argument. Perhaps the `histogramdd` argument is only for TH1 and TH2.

Then maybe `bh.Histogram.to_numpy()` would have the same `histogramdd` argument, though it would have to exist for all numbers of axes and storage types (profile/WeightedMean/Mean and non-profile/Weighted/Double/Int64)?

But then, what would the conversion from Uproot TH* and TProfile* to boost-histogram be? `to_boost()` (with parentheses)? If so, let's change it before the tutorial. I'd like to get both of your preferences on this, @HDembinski and @henryiii.

**Comment by henryiii** [comment]
> Am I missing something or is this the state of plotting histograms?

Hist plots histograms. I've added a bit of a readme here: https://github.com/scikit-hep/hist

I'd love to get mplhep to work with 2D histograms, but that's not in place yet. I'd also like mplhep to look for and use `metadata["title"]` or `.title` (the later being Hist only).

**Comment by jpivarski** [comment]
Do you think we can very quickly get `hist` properties or `to_hist()` methods on the TH* and maybe TProfile objects?

I'm going to need some input on hist constructors (I think your notebook only included boost-histogram), but everything needed from the ROOT side is demonstrated:

https://github.com/scikit-hep/uproot4/blob/77c5404ee7545beaf03689c8afe9090cab160083/uproot4/behaviors/TH1.py#L59-L129

Also, an opinion on two-letter properties vs `to_fullname()` methods with parentheses?

   * `to_numpy()` vs `np`, `np1`, `np2`
   * `to_boost()` vs `bh`
   * `to_hist()` vs `hist`

**Comment by henryiii** [comment]
I'll let @HDembinski weigh in on the `.to_stuff()` vs. `.stuff` syntax - Would it every be possible to assign to one of these? I would think not, as you already have an Uproot object before you call the method/property - I don't see a way this would naturally become an Uproot writing syntax. If that's the case, `to_X` is slightly longer to type, but is nicely organized by name, is clearer (someone might not know what a bh is), and does provide some options like the histogramdd one.

It's also consistent with boost-histogram's `.to_numpy()`. For us, there's also a handy way to disable/enable the flow bins with `.to_numpy(flow=True)` (default is `False`, as they are uncommon in NumPy).

If you do go that way, I wouldn't disable the `dd` argument for 3D+; `.to_numpy(dd=False)` can easily generalize. Someone who just needs the edges shouldn't have to change to `dd=True` syntax just because NumPy doesn't provide a histogram3d function.

**Comment by henryiii** [comment]
Hist is basically usable, the only downside so far is we don't have a release, it's just on GitHub. Should we do a release? It could be 2.0a1 (as there are already 1.0.0 - 1.0.6 releases on PyPI)

**Comment by jpivarski** [comment]
Yes, please make a release. It seems to me that it ought to be an alpha release; I can ask for alpha in the tutorial's requirements.txt.

**Comment by henryiii** [comment]
Perfect, will release in a moment, then.

**Comment by henryiii** [comment]
I'm going to try to push a boost-histogram 0.9.0 with the metadata support and a few fixes soon too, so you can slice and then convert back to ROOT and keep the metadata. There will be an alpha 1 release for Hist after that happens.

**Comment by jpivarski** [comment]
Because of the `flow=True` and consistency with boost-histogram, I'm going to go with the `to_xyz()` methods. There will never be any case where you'd want to _assign_ to a property of an Uproot TH* object. I'll also let `dd=True/False` generalize for TH3, as though NumPy had a `np.histogram3d` (generalizing the API).

**Comment by jpivarski** [comment]
Now that I have parentheses, I can put in all the options (for example, from TH2):

```python
    def to_numpy(self, flow=True, dd=False, errors=False):
        if errors:
            values, errs = self.values_errors()
        else:
            values, errs = self.values(), None

        xedges = self.edges(0)
        yedges = self.edges(1)
        if not flow:
            values = values[1:-1, 1:-1]
            if errors:
                errs = errs[1:-1, 1:-1]
            xedges = xedges[1:-1]
            yedges = yedges[1:-1]

        if errors:
            values_errors = values, errs
        else:
            values_errors = values

        if dd:
            return values_errors, (xedges, yedges)
        else:
            return values_errors, xedges, yedges
```

I am now looking at [this notebook](https://github.com/scikit-hep/hist/blob/master/notebooks/Hist.ipynb) on how to write `to_hist()`.

**Comment by henryiii** [comment]
I like that better! As Hans pointed out, setting is a key feature of the property syntax, and we don't need that.

I'm touch up Hist. Writing Hist should be the same as boost, with the one exception that you can make name and title available directly via keyword or property, and then it will include the title (and if no title, the name) in the plot. Otherwise, a Hist should behave exactly like a Histogram.

**Comment by jpivarski** [comment]
Including setting the contents through `view`? That's the part that's lacking from the notebook.

**Comment by jpivarski** [comment]
And setting the storage.

**Comment by henryiii** [comment]
It's identical, in fact, Storage comes from boost-histogram directly, so you could even leave bh.storage.X if you want.

Hist is almost entirely (or entirely?) additive.

**Comment by henryiii** [comment]
`to_histogram(lib=bh)` or `. to_histogram(lib=hist)` should even be possible to write, and then the other could call that. The only think you would have to do is hasattr "title" and hasattr "name".

**Comment by jpivarski** [comment]
I was misunderstanding that. Given that it works this way, can I simplify the `to_hist()` method by simply having it call `to_boost()` and then calling a conversion that turns the `bh.Histogram` into a `hist.Hist`?

**Comment by henryiii** [comment]
You could, but it would be nice to get the title and name as Hist properties, not just in the metadata dict. I think a `to_histogram` (public) or `_to_histogram` (hidden) or something of that sort that either of the other methods could call would be a little better.

**Comment by jpivarski** [comment]
I'd like to set the name and title, something I thought a wrapper might add.

Since `hist.Hist` is a subclass of `bh.Histogram`, perhaps I could create a `bh.Histogram`, reassign the `__class__`, and then add the `name` and `title` properties manually?

**Comment by henryiii** [comment]
It depends on the metadata structure. If `h.title == h.metadata["title"]` in Hist, then it's really easy to support both. The downside is that makes the title and name a public part of the metadata structure, and you could break the title/name if you assign to the metadata slot. So what should be done is to wrap the metadata. The boost-histogram metadata and the hist metadata will not be the same structure. (not sure what's there now, but I can fix/change soon).

You can call `Hist(h)` to convert - that's the plan anyway, I might need to add one more thing to do that.

**Comment by jpivarski** [comment]
Using a constructor like that certainly feels better than changing the `__class__` of an instantiated object. I made sure that `"name"` and `"title"` were assigned at all levels, rather than `"fName"` and `"fTitle"`, and now the conversion function is just

```python
    def to_hist(self):
        return uproot4.extras.hist().Hist(self.to_boost())
```

(where `uproot4.extras.hist()` does `import hist` with a "how to `pip install hist`" message upon failure).

**Comment by jpivarski** [comment]
Well, this is looking good (using hist from master, checked out a minute or two ago):

[https://nbviewer.jupyter.org/github/jpivarski/2020-07-13-pyhep2020-tutorial/blob/master/tutorial.ipynb#Histograms!](https://nbviewer.jupyter.org/github/jpivarski/2020-07-13-pyhep2020-tutorial/blob/master/tutorial.ipynb#Histograms!)

I want to show all of these things with no manual styling because I think it's important to see what you get for zero effort (the fact that effort can result in beautiful plots is a given). The pull plot error bars look a little strange, the `plot2d_full` has extraneous tick-marks, and all of the fonts are large, but it's very good to see that anyone can get plots as good as these are with no effort. The use of the uncertainties package complicates the `plot_pull` example; I don't know if it's optional.

Once a version of hist is deployed, I can start making the Binder.

Also, I hoped to hear from @HDembinski about interface choices, but it is a Saturday, rather late in Europe, and I think he's in favor of the clearer `to_numpy()`, `to_boost()`, `to_hist()`, particularly since assignment is never going to be a feature (the argument for properties).

**Comment by henryiii** [comment]
While metadata handling will likely improve later, for now, `metadata={"title":..., "name":...}` will be picked up and used as title/name in Hist. Currently it is just reading from a publicly exposed metadata field. In the future, maybe hist will do something a little differently. `h.metadata = None` will remove the name and title too, which seems odd.

**Comment by henryiii** [comment]
Boost-histogram 0.9.0 is out, mplhep now supports 2D hists, and hist 2.0.0a2 is now out.

**Comment by HDembinski** [comment]
Sorry for the late comments, but I didn't have anything to add, you converged to the same solution that I would have preferred.

**Comment by jpivarski** [comment]
All of these duplicates will all go into scikit-hep/uproot4#167, where this interface will get figured out, once and for all.
