### ISSUE TITLE
Cannot open TTree with branches consisting of unsigned integers

### ISSUE THREAD

**Issue by harringtonh** [scikit-hep/uproot#509]
![image](https://user-images.githubusercontent.com/54288976/87361274-b1c00c00-c520-11ea-80ab-011e1326ced2.png)
When I open a ROOT file I am able to open all of the TTrees except for one, for which I get the above error. However TBrowser is able to open the tree without any problems. I read the earlier issue thread regarding streamers which looked very similar. If this is the same issue, is there a way to ensure while writing a tree that the correct streamers get attached? Thank you in advance for any help.

**Comment by jpivarski** [comment]
This doesn't seem to have anything to do with unsigned integers (which are supported). You're getting this error while trying to read the TTree metadata, not any of the array data in the branches. Somehow, it failed to recognize a TBranch type, which is very unusual. Recently I encountered an apparently obscure TBranch subclass called "TBranchObject," though they're almost always either TBranch and TBranchElement.

This might be easier to debug in Uproot 4 (because the error messages are more thorough), or it may be solved outright if what you're looking at is a TBranchObject (handled only in Uproot 4). If your file is small enough and can be public, post it here and I'll take a look.

**Comment by harringtonh** [comment]
Thanks for the advice! uproot4 did in fact do the job!
