### ISSUE TITLE
Request support for tree branch with vector<TLorentzVector> objects

### ISSUE THREAD

**Issue by chrisjcc** [scikit-hep/uproot#57]
In giving UpRoot a try we noticed it does not currently support tree branches containing vector<TLorentzVector> objects.  Many analysis make use of 4-vector information for many types particles in the event. Having access to a branch with stored TLorentzVector objects would be very useful. It would be awesome if such capability could be added as it would benefit the physics community at large.

**Comment by eduardo-rodrigues** [comment]
Jim, would the purely pythonic class LorentzVector we have in https://github.com/scikit-hep/scikit-hep/blob/master/skhep/math/vectors.py be of use for you here? We have a pull request under work to change the internals of the class, for performance. Still, the API is basically there.

**Comment by jpivarski** [comment]
The immediate issue is that I need to use the ROOT streamers to read the data from bytes into a Python class. Then, after that, it could be useful to add Python methods for boosting, rotations, etc. Because of how ROOT has defined TLorentzVector, the data structure will have to be

```python
class TVector3(TObject, TVector3Methods):
    def __init__(self, x, y, z):
        self.fX = x
        self.fY = y
        self.fZ = z

class TLorentzVector(TObject, TLorentzVectorMethods):
    def __init__(self, p, e):
        self.fP = p
        self.fE = e
```

where I'm free to define `TVector3Methods` and `TLorentzVectorMethods` however I like. I can define these methods-only mixin classes (no data!) as subclasses of whatever I like, and it should at least have some basic convenience methods.

I can define the built-in methods to not clash with Scikit-HEP's `LorentzVector` and make Scikit-HEP an optional dependency that enhances it with the dozens of methods you've defined. They should come at no cost in performance, since it's just a superclass pointer. Then when users install Scikit-HEP, their Lorentz vectors get super-powers.

I'll have to experiment to see what Python does when Scikit-HEP's `LorentzVector` tries to derive quantities from a private member (two leading underscores, which like C++'s `private` are _not_ passed down to subclasses) and the data are in members named `fP`, `fE`. It would be easy to add a `@property` to translate `fP` to `__vector3d` and `fE` to `__t`, but I don't know how Python propagates that through subclasses.

**Comment by eduardo-rodrigues** [comment]
Understood. Thanks for all the details. To be seen indeed, not in the first steps of development ...

**Comment by jpivarski** [comment]
Looking at it now, the Python trickery and dependence on whether the user has some library installed but not explicitly imported doesn't sound like a good idea.

Instead, I'm going to take the Scikit-HEP definitions as establishing a duck-typing convention and making the TVector3 and TLorentzVector from ROOT 100% compatible with the Scikit-HEP version. Then Python functions and user code that accepts one will accept the other, even if they don't derive from the same class.

**Comment by jpivarski** [comment]
By the way (for watchers of this issue), the deserialization is done: the master version on GitHub can read your TLorentzVectors, if you don't mind the `fP`, `fE` stuff. I'm adding the convenience functions now.

**Comment by jpivarski** [comment]
So we are now in a weird position of being able to read `std::vector<UserClass>` for any user class, but not any user classes as single objects per event. (I'm calling `TLorentzVector` a user class because what I really implemented was anything with a streamer.) If you have any examples of `TLorentzVector` (or other unsplit classes) that are not in `std::vector`, please raise another issue and I'll implement it!

The main part of this work turned out to be just

```python
    def interpret(self, item):
        size, = item[6:10].view(JaggedObjects.indexdtype)
        source = uproot.source.source.Source(item)
        cursor = uproot.source.cursor.Cursor(10)
        out = [None] * size
        for i in range(size):
            out[i] = self._class.read(source, cursor, self._context, None)
        return out
```

and we just pick up the bytes-to-objects automatically in the auto-generated `self._class`. Almost nothing to do, and that's great! (ROOT streamers are nice.)

And then for convenience, I added the Sckit-HEP 3-vector and 4-vector methods.

**Comment by jpivarski** [comment]
@kpedro88

**Comment by kpedro88** [comment]
I don't have an example of single `TLorentzVector` branch on hand, but can probably make one easily. Will put it on my todo list.
