### ISSUE TITLE
uproot + pyroot conflict?

### ISSUE THREAD

**Issue by davidlange6** [scikit-hep/uproot#58]
Hi @jpivarski - We just added uproot to the CMSSW python stack. We have a unit test that basically imports everything in our python stack to make sure that installations are somewhat sane.  From this unit test it seems uproot conflicts with other things in our stack if imported in the same python session. Is this to be expected?

Eg

>>>import uproot

works, but

>>> import rootpy
>>> import uproot

ERROR:ROOT.TUnixSystem.DispatchSignals] segmentation violation
ERROR:stack] File "<stdin>", line 1, in <module>
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/lcg/root/6.10.09-omkpbe3/lib/ROOT.py", line 318, in _importhook
ERROR:stack]   return _orig_ihook( name, *args, **kwds )
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/uproot/__init__.py", line 33, in <module>
ERROR:stack]   from uproot.tree import iterate
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/lcg/root/6.10.09-omkpbe3/lib/ROOT.py", line 318, in _importhook
ERROR:stack]   return _orig_ihook( name, *args, **kwds )
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/uproot/tree.py", line 77, in <module>
ERROR:stack]   from uproot.interp.auto import interpret
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/lcg/root/6.10.09-omkpbe3/lib/ROOT.py", line 318, in _importhook
ERROR:stack]   return _orig_ihook( name, *args, **kwds )
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/uproot/interp/__init__.py", line 33, in <module>
ERROR:stack]   from uproot.interp.jagged import asjagged
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/lcg/root/6.10.09-omkpbe3/lib/ROOT.py", line 318, in _importhook
ERROR:stack]   return _orig_ihook( name, *args, **kwds )
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/uproot/interp/jagged.py", line 53, in <module>
ERROR:stack]   _compactify = numba.njit(_compactify)
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/numba/decorators.py", line 225, in njit
ERROR:stack]   return jit(*args, **kws)
ERROR:stack] File "/cvmfs/cms-ib.cern.ch/nweek-02514/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-omkpbe3/lib/python2.7/site-packages/numba/decorators.py", line 167, in jit

(very long set of tracebacks truncated - I can provide if useful)

**Comment by jpivarski** [comment]
I was going to say that there can't be a conflict between uproot and any ROOT things because uproot is just Python scripts. Certainly nothing that can cause a segmentation fault.

But the stack trace reminded me that if Numba is available, uproot will use it to accelerate functions where an action must be applied to each event, yet can't be handled by Numpy (string manipulation, mostly). It's failing when it's trying to compile those functions.

Most likely, then, this is an incompatibility between Numba and ROOT, since both use LLVM and they might be pulling in different versions of LLVM. It could be that nothing else in your software stack tests Numba. It's an error that might only be triggered by actually loading both in the same process, since it's probably a conflict of symbol versions or names.

Julia+ROOT had this same incompatibility, for the same reason. That issue was never resolved. Is it easy to try a build with uproot and ROOT/PyROOT, but no Numba? I may need to make Numba acceleration a user-controllable, opt-in feature if the combination is volatile.

**Comment by davidlange6** [comment]
> On Mar 5, 2018, at 2:42 PM, Jim Pivarski <notifications@github.com> wrote:
> 
> I was going to say that there can't be a conflict between uproot and any ROOT things because uproot is just Python scripts. Certainly nothing that can cause a segmentation fault.
> 
> But the stack trace reminded me that if Numba is available, uproot will use it to accelerate functions where an action must be applied to each event, yet can't be handled by Numpy (string manipulation, mostly). It's failing when it's trying to compile those functions.
> 
> Most likely, then, this is an incompatibility between Numba and ROOT, since both use LLVM and they might be pulling in different versions of LLVM. It could be that nothing else in your software stack tests Numba. It's an error that might only be triggered by actually loading both in the same process, since it's probably a conflict of symbol versions or names.

ah.....right there is llvm (etc) inside of root... I'm not sure you should regard that as your problem...
Thanks!
