### ISSUE TITLE
Iteration over files and Pandas dataframe

### ISSUE THREAD

**Issue by rdisipio** [scikit-hep/uproot#61]
Hi,
  
   I need to iterate over a number of files. In the examples, I do not understand if there's an easy way to convert the "chain" into a Pandas data frame. I may find a workaround but that may be a useful feature nonetheless.

Cheers,
Riccardo

**Comment by jpivarski** [comment]
That's a good idea. I put such a feature into [release 2.8.4](https://github.com/scikit-hep/uproot/releases/tag/2.8.4). The release notes have a few examples.

Instead of making a new DataFrame iteration method, I added `pandas.DataFrame` as a possible `outputtype` to all the existing methods. When building up an analysis, you can start with an iteration that yields dicts of Numpy arrays and then graduate to DataFrames, if need be.

The only problem with doing it this way is that methods to make lazy arrays also have an `outputtype` parameter (of the same meaning), and Pandas can't store lazy arrays. Dask can, and maybe that's the appropriate way to go with that.

It also leaves open the question of whether we need a `tree.pandas.df()` function, since the equivalent functionality is now provided by `tree.arrays(outputtype=pandas.DataFrame)`. Currently the old form has an optimization that the new form doesn't: it fills data directly from ROOT into Pandas without intermediate Numpy arrays. Nah, it's not good to have different calling conventions yield different behaviors... I need to make them the same...

**Comment by jpivarski** [comment]
I did the things mentioned above and called it [release 2.8.5](https://github.com/scikit-hep/uproot/releases/tag/2.8.5).

No matter how you ask for Pandas DataFrames, all applicable optimizations will be applied, and `tree.pandas.df(**args)` is now just a thin wrapper around `tree.arrays(outputtype=pandas.DataFrame, **args)`.
