### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by altavir** [scikit-hep/uproot#65]
The module relies on `fcntl` and therefore does not work on windows:
```
ModuleNotFoundError: No module named 'fcntl'
```
Could you please use a cross-platform alternative? The package of yours is especially important for Windows users, where you can't or won't install latest root distribution.

**Comment by jpivarski** [comment]
Could you try master now? I've removed `fcntl` as a load-time requirement; it's only used by DiskCache and that's a very optional part of the system. With this patch, DIskCache still won't be usable on Windows, but everything else in uproot should be. If this works for you, I'll publish it as version 2.8.12.

**Comment by jpivarski** [comment]
After commit fe81eb3664e0f5e8109c4217fcf07d261f6873b0, which removes DiskCache tests from the unit tests if `fcntl` is not available.

**Comment by altavir** [comment]
Thanks for the quick reply. Can't test it right now, but will try it as soon as possible.

**Comment by jpivarski** [comment]
This issue was something that I knew about and then forgot about, so I wanted to do it before I forgot again. Unfortunately, I can't test it because I don't have access to a Windows system.

**Comment by altavir** [comment]
Not working, but now I have different error, something more like a bug not related to Windows:
`>import uproot`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9f632cbcea14> in <module>()
----> 1 import uproot

C:\Users\darksnake\AppData\Roaming\Python\Python36\site-packages\uproot\__init__.py in <module>()
     30 
     31 # high-level entry points
---> 32 from uproot.rootio import open, xrootd
     33 from uproot.tree import iterate
     34 from uproot.hist import hist

C:\Users\darksnake\AppData\Roaming\Python\Python36\site-packages\uproot\rootio.py in <module>()
     44 import uproot.source.compressed
     45 from uproot.source.memmap import MemmapSource
---> 46 from uproot.source.xrootd import XRootDSource
     47 from uproot.source.http import HTTPSource
     48 from uproot.source.cursor import Cursor

C:\Users\darksnake\AppData\Roaming\Python\Python36\site-packages\uproot\source\xrootd.py in <module>()
     33 import numpy
     34 
---> 35 import uproot.source.chunked
     36 
     37 class XRootDSource(uproot.source.chunked.ChunkedSource):

C:\Users\darksnake\AppData\Roaming\Python\Python36\site-packages\uproot\source\chunked.py in <module>()
     34 import uproot.source.source
     35 
---> 36 class ChunkedSource(uproot.source.source.Source):
     37     # makes __doc__ attribute mutable before Python 3.3
     38     __metaclass__ = type.__new__(type, "type", (uproot.source.source.Source.__metaclass__,), {})

AttributeError: module 'uproot' has no attribute 'source'
```

**Comment by altavir** [comment]
Reinstalled it and now I have the another error:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-9f632cbcea14> in <module>()
----> 1 import uproot

C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\__init__.py in <module>()
     30 
     31 # high-level entry points
---> 32 from uproot.rootio import open, xrootd
     33 from uproot.tree import iterate
     34 from uproot.hist import hist

C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\rootio.py in <module>()
     44 import uproot.source.compressed
     45 from uproot.source.memmap import MemmapSource
---> 46 from uproot.source.xrootd import XRootDSource
     47 from uproot.source.http import HTTPSource
     48 from uproot.source.cursor import Cursor

ModuleNotFoundError: No module named 'uproot.source.xrootd'
```

Maybe I am doing something wrong when installing from the source? I just write `python setup.py install`. Not a lot of experience with python.

**Comment by jpivarski** [comment]
This is the right way to install it. It probably is related to Windows, but the actual error is hidden. Python sometimes hides installation errors by saying `No module named 'uproot.source.xrootd'` when `uproot/source/xrootd.py` is definitely present, but there's something it can't load inside `uproot/source/xrootd.py`.

Could you try this from the uproot directory you've git-cloned?

```bash
python uproot/source/xrootd.py
```

and if that doesn't work,

```bash
python uproot/source/chunked.py
```

(i.e. working up the import chain). Sorry that I have to debug through you because I don't have a system I can directly test. (If there was some way I could look over your shoulder, this would be more productive.)

**Comment by altavir** [comment]
It is OK. I have much more problems with installing root itself (and I dno't really need it, only to read the data).

So, `chunked` is broken. It requires `urllib2` and it it probably related to this: https://stackoverflow.com/questions/6594620/python-3-2-unable-to-import-urllib2-importerror-no-module-named-urllib2

**Comment by jpivarski** [comment]
(Once we're done with this, uproot should always be installable on Windows— we're working through my lack of knowledge about which libraries are available. In fact, maybe I could do this testing as part of the Travis matrix.)

While `urllib2` is Python 2-vs-3 specific, all of the `import urllib2` statements in uproot are in a try-catch block that switches between Python 2 and 3. Also, `chunked.py` doesn't import `urllib2` or import anything that imports `urllib2`. Could you post what you actually ran and the actual error?

**Comment by altavir** [comment]
OK, here is it:
```
> PS D:\Temp\uproot> python uproot/source/chunked.py

Traceback (most recent call last):
  File "D:\Temp\uproot\uproot\source\http.py", line 34, in <module>
    from urllib.request import urlopen, Request
ImportError: cannot import name 'urlopen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\source\http.py", line 34, in <module>
    from urllib.request import urlopen, Request
  File "C:\Anaconda3\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "D:\Temp\uproot\uproot\source\http.py", line 36, in <module>
    from urllib2 import urlopen, Request
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uproot/source/chunked.py", line 33, in <module>
    import uproot.cache.memorycache
  File "C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\__init__.py", line 32, in <module>
  File "C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\rootio.py", line 47, in <module>
  File "C:\Anaconda3\lib\site-packages\uproot-2.8.12-py3.6.egg\uproot\source\http.py", line 36, in <module>
    from urllib2 import urlopen, Request
ModuleNotFoundError: No module named 'urllib2'
```
It seems that catch block itself somehow calls this library.

**Comment by jpivarski** [comment]
(Nope; looks like Travis can't test Windows; only Linux and OSX.)

**Comment by chrisburr** [comment]
To jump in here, I think you can use [appveyor](https://www.appveyor.com/) to get free Windows CI.

**Comment by jpivarski** [comment]
Okay, I'll take a look at appveyor. In the meantime, I'd love to be able to try some experiments on the Windows Python prompt to find out what's so different about it.

I don't know why running `python uproot/source/chunked.py` imports `uproot.source.http`, since http depends on chunked, but chunked does not depend on http.

The try-catch block in `http.py` tries the Python 3 idiom first. Since @altavir is using Python 3.6, the `from urllib.request import urlopen, Request` should work and not go to the Python 2 fallback. The error message says, "cannot import name 'urlopen'." Python 3.6 _does indeed_ have a `urlopen` function in module `urllib.request`. I've googled it and some people have trouble _calling_ `urlopen` on Windows (usually because of proxies), but Windows absolutely should be able to _import_ this part of the standard library.

Anybody out there have any ideas? I'm going to try to add appveyor to the uproot continuous integration, but that won't help me debug. Maybe I can find someone who has a Windows laptop.

**Comment by chrisburr** [comment]
I can’t make sense of it either but I have a VM I can use to debug it, I’ll take a look later today.

**Comment by sbinet** [comment]
(@altavir if you only want to read ROOT files on Windows, you may (or may not) want to try [go-hep.org/x/hep/rootio](https://go-hep.org/x/hep/rootio). it's in Go, but has the same features (more or less) than uproot. it's cross-compiled daily to Windows :P)

`</shameless-plug>`

**Comment by jpivarski** [comment]
Another plug: uproot now builds on AppVeyor in Windows, at least for its default Python 2.7. I'm expanding the build matrix now. (https://ci.appveyor.com/project/jpivarski/uproot)

What @altavir is encountering is probably unrelated. Could it be that you're running Python 2 in a Miniconda 3, and something is getting confused? Like, a Python 2 executable with Python 3 libraries? It's very odd that `from urllib.request import urlopen` fails in Python 3 because that's a part of the standard library.

**Comment by altavir** [comment]
I work on Java/Kotlin actually, and I do not like python much, but I do not like Root much more. I have to work with python in order to be able to read latest root format (freehep reader sadly does not work with root 6). If I add Go to the mix, I will go crazy immediately.
It will be easier to ask my boss (who works in the same room) to just convert root files to ascii. But I would very like to see this library working, it will simplify life for a lot of people in future.

**Comment by altavir** [comment]
I use Anaconda 3 with python 3.6. I will try to set it up in a separate environment.

**Comment by jpivarski** [comment]
Actually, can you do the import of the urlopen function from the Python command line, without uproot? That's the weird thing.

**Comment by altavir** [comment]
I've installed separate python 2.7 environment and python 3.6 environment. Everything works fine in 2.7, but fails in 3.6. It is possible that my conda installation is messed up. It does not like mixed pip and conda packaging.

And answering your question, not `import urlopen` fails. There is a package with this name and I installed it and removed it later not to interfere with these tests.

**Comment by chrisburr** [comment]
I've just tried this in my VM with Python 3.6 and anaconda and uproot works, there is one test failure (I can debug it if needed @jpivarski?):

<img width="933" alt="screen shot 2018-03-27 at 11 58 27" src="https://user-images.githubusercontent.com/5220533/37963461-3f86aca2-31b6-11e8-8b12-cee7dedcda1a.png">

@altavir Can you try `from urllib.request import urlopen` in a fresh python prompt?

**Comment by altavir** [comment]
It works! Thanks everyone, you saved me a lot of trouble.

**Comment by jpivarski** [comment]
Okay, I don't know what exactly fixed @altavir's issue, but I've been putting in fixes for Windows building and he refreshed his setup, and whatever it was is gone.

uproot now gets a clean bill of health from AppVeyor: https://ci.appveyor.com/project/jpivarski/uproot/build/1.0.20

I don't know what's going wrong with @chrisburr's setup, but I would recommend cleanly checking out because the AppVeyor build matrix includes Python 3.6. You probably have some intermediate state. (Reopen this issue, which is generally about Windows compatibility, if it doesn't go away.)

The dust should be settling now. Incidentally, don't forget that @sbinet has a Go ROOT I/O system— it's a completely different system, but it's been working on Windows for a while now and depending on your needs, it could be a better solution. But as of these fixes and inclusion of Windows in continuous integration, Windows availability shouldn't be a distinguishing characteristic. (Go and Python are different enough that there are plenty of other differences that could matter for you.)
