### ISSUE TITLE
How do I use the object returned by countleaf ?

### ISSUE THREAD

**Issue by imandr** [scikit-hep/uproot#67]
I can not figure out how to use the object returned by tree[key].countleaf. It does not appear to have any useful attributes or methods. In particular, I do not see how to get the counting branch name.

```
pt = tree["Muon.pt"]
c = pt.countleaf
print type(c)
print c
print dir(c)
print c.fName

```
```
<class 'uproot.rootio.TLeafElement'>
<TLeafElement 'Muon_' at 0x7f658c5cc950>
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_classname', '_classversion', '_copycontext', '_fields', '_format1', '_postprocess', '_pycode', '_readinto', '_versions', 'fID', 'fIsRange', 'fIsUnsigned', 'fLeafCount', 'fLen', 'fLenType', 'fName', 'fOffset', 'fTitle', 'fType', 'read']
Muon_
```

**Comment by jpivarski** [comment]
You've found it. `TLeaf` hasn't been Pythonized the way `TBranch` has, so uproot defines a generic class from the streamer info and fills it with what it finds— in this case, `fID`, `fIsRange`, `fIsUnsigned`, `fLeafCount`, `fLen`, `fLenType`, `fName`, `fOffset`, `fTitle`, `fType` (ROOT class members all start with "f"). The name is `fName` and the title is `fTitle`. The other members are useful to uproot internally, but probably not a user. In fact, the `Interpretation` objects (`asdtype`, `asarray`, `asjagged`, `asstrings`) could be thought of as translated TLeaves, because the information that a TLeaf conveys is the data _type_, while the TBranch holds the data _values_ (has _nothing_ to do with trees).

But, knowing your application, you're probably more interested in `pt.countbranch`?
