### ISSUE TITLE
XRootD: I/O operation on closed file

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/uproot#71]
In `uproot/source/xrootd.py` there is a multithreading issue causing the XRootD `File` objects to be closed prematurely. This is caused by the connections closed inside `XRootDSource.__del__` despite being shared between instances of `XRootDSource`. If prevent this by changing [Line 78](https://github.com/scikit-hep/uproot/blob/ba1f86cbe9654092a7b87ff7fdcaf9a6b9866d16/uproot/source/xrootd.py#L78) to `out._source = None` everything works correctly.

For completeness, I'm using uproot 2.8.16, XRootD 4.8.2 and Python 3.6 and the simplest example of this bug I have is effectively:
```python
import uproot
from joblib import Parallel, delayed
fn = 'root://a_file_with_two_or_more_ttrees.root'
def process_file(fn, key):
    f = uproot.open(fn)
    arr = f[key].arrays()
a = Parallel(n_jobs=1, verbose=100, backend='threading')(delayed(process_file)(fn, key) for key in uproot.open(fn).keys())
```

**Comment by jpivarski** [comment]
That makes sense— thanks for catching it! Thanks also for making a proposed solution. If you don't need an official release with the bug-fix, I'll do it Monday because I can't get to my computer today. But if you need it today (and since you know how to fix it), you can make a pull request and then I can accept that and push it through to PyPI on my phone.  :)

**Comment by jpivarski** [comment]
Version 2.8.17 should do it— let me know if you still have problems!
